Repository iotaledger/firefly, pull requests merged in 2021-11, with the labels that each got.

#1613 Fix: Wrong error message on empty/corrupt stronghold import
  packages/shared/lib/shell/walletApi.ts
  packages/shared/routes/setup/import/Import.svelte
Labels: type:fix

#1209 fix: Profile deletion
  package.json
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/native/Cargo.lock
  packages/desktop/App.svelte
  packages/shared/components/modals/AccountActions.svelte
  packages/shared/components/popups/DeleteAccount.svelte
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/lib/app.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/wallet/views/CreateAccount.svelte
  packages/shared/routes/setup/Profile.svelte
Labels: type:fix

#1211 feat: System default theme
  packages/shared/lib/appSettings.ts
  packages/shared/lib/tests/currency.test.ts
  packages/shared/lib/tests/mocks/matchMedia.ts
  packages/shared/lib/typings/app.ts
  packages/shared/locales/en.json
  packages/shared/locales/ja.json
  packages/shared/routes/Splash.svelte
  packages/shared/routes/dashboard/settings/views/General.svelte
  packages/shared/routes/setup/Appearance.svelte
Labels: type:enhancement

#1604 feat: Developer profile
  packages/shared/components/ButtonCheckbox.svelte
  packages/shared/components/Profile.svelte
  packages/shared/components/Sidebar.svelte
  packages/shared/components/icon/icons.js
  packages/shared/components/inputs/Checkbox.svelte
  packages/shared/components/modals/NetworkIndicator.svelte
  packages/shared/components/popups/AddNode.svelte
  packages/shared/components/popups/Diagnostics.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/NodeInfo.svelte
  packages/shared/components/popups/RemoveNode.svelte
  packages/shared/components/popups/SwitchNetwork.svelte
  packages/shared/lib/network.ts
  packages/shared/lib/networkStatus.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/shell/walletApi.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/lib/tests/utils.test.ts
  packages/shared/lib/typings/client.ts
  packages/shared/lib/typings/icons.ts
  packages/shared/lib/typings/network.ts
  packages/shared/lib/typings/node.ts
  packages/shared/lib/typings/profile.ts
  packages/shared/lib/typings/routes.ts
  packages/shared/lib/typings/utils.ts
  packages/shared/lib/utils.ts
  packages/shared/lib/wallet.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/Advanced.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/login/Login.svelte
  packages/shared/routes/setup/Profile.svelte
  packages/shared/routes/setup/ledger/views/Connect.svelte
  packages/shared/routes/setup/ledger/views/GenerateNewAddress.svelte
  packages/shared/routes/setup/ledger/views/RestoreFromLedger.svelte
Labels: type:feature, scope:shared

#1624 hotfix: Unneeded code
  packages/shared/routes/dashboard/settings/views/Advanced.svelte
Labels: type:hotfix

#1635 Fixed a typo
  packages/backend/README.md
Labels: type:documentation, type:fix

#1625 chore(ci): Avoid using latest to specify CI platforms
  .github/workflows/build-desktop.yml
Labels: type:chore, scope:ci

#1496 chore(desktop): Update Electron to 12.2.1
  packages/desktop/package.json
  yarn.lock
Labels: scope:security, type:chore, status:blocked

#1605 chore(desktop): Update Electron to 11.5.0
  packages/desktop/package.json
  yarn.lock
Labels: scope:dependencies, scope:security, type:chore

#1606 feat: export transactions history in csv files for accounts within a profile
  .eslintrc.js
  packages/desktop/electron/preload.js
  packages/shared/components/SettingsNavigator.svelte
  packages/shared/components/Toast.svelte
  packages/shared/components/popups/ExportTransactionHistoryPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/electron.ts
  packages/shared/lib/transactionHistory.ts
  packages/shared/lib/typings/icons.ts
  packages/shared/lib/typings/routes.ts
  packages/shared/lib/wallet.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/Advanced.svelte
Labels: type:feature, scope:desktop, scope:shared

#1393 Fix: add missing tailwind dark focus variant
  packages/shared/components/inputs/Dropdown.svelte
  packages/shared/tailwind.config.js
Labels: type:fix

#1671 update(desktop): Get more accurate OS version info on macOS
  packages/desktop/electron/main.js
Labels: type:enhancement, platform:mac, scope:desktop
