Repository iotaledger/firefly, pull requests merged in 2021-09, with the labels that each got.

#1109 fix(desktop): Fix error in main process on first launch on macOS
  packages/desktop/electron/main.js
Labels: (platform) macOS

#1497 hotfix: `wallet.rs` branch
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/index.ts
  packages/backend/bindings/node/native/Cargo.lock
Labels: bug

#1470 feat: add ability to see precise iota balance
  packages/shared/components/BalanceSummary.svelte
  packages/shared/components/Tooltip.svelte
  packages/shared/routes/dashboard/wallet/views/Account.svelte
  packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
  packages/shared/routes/dashboard/wallet/views/WalletBalance.svelte
Labels: feat

#1431 feat: Send fiat amount
  packages/backend/Cargo.lock
  packages/backend/bindings/node/native/Cargo.lock
  packages/shared/components/inputs/Amount.svelte
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/popups/Transaction.svelte
  packages/shared/lib/currency.ts
  packages/shared/lib/tests/currency.test.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: feat

#1451 chore: Snyk integration
  .github/CONTRIBUTING.md
  .github/workflows/ci.snyk.yml
  .snyk
Labels: chore, ci

#1448 feat: Add miota to portfolio chart
  packages/shared/components/inputs/Dropdown.svelte
  packages/shared/lib/chart.ts
  packages/shared/lib/currency.ts
  packages/shared/lib/typings/chart.ts
  packages/shared/lib/typings/currency.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/LineChart.svelte
Labels: feat
