Repository iotaledger/firefly, pull requests merged in 2021-04, with the labels that each got.

#941 chore: Update keychain name
  packages/desktop/electron/lib/keychain.js
Labels: do not merge

#966 chore: add correct node endpoints
  packages/desktop/public/index.html
  packages/shared/lib/migration.ts
  packages/shared/lib/network.ts
Labels: do not merge

#942 chore: Update version
  .github/workflows/build-desktop.yml
  packages/desktop/package.json
  packages/desktop/scripts/notarize.macos.js
Labels: do not merge

#940 chore: Set official network
  packages/desktop/public/index.html
  packages/shared/lib/migration.ts
  packages/shared/lib/network.ts
  packages/shared/lib/typings/client.ts
  packages/shared/lib/wallet.ts
Labels: do not merge

#943 chore: Disable devtools in packaged version
  packages/desktop/electron/lib/menu.js
  packages/desktop/electron/main.js
Labels: do not merge

#944 chore: Update readme
  README.md
  header-beta.png
  header.png
Labels: do not merge

#1011 feature(ci): Add AppImage signing
  .github/workflows/build-desktop.yml
Labels: P - Linux

#1012 fix(ci): Set minimum macOS version to 10.12
  .github/workflows/build-desktop.yml
  packages/backend/bindings/node/native/.cargo/config.toml
Labels: P - macOS

#1043 chore: enable snapshot
  packages/shared/lib/chrysalis.json
Labels: do not merge

#1050 chore: snapshot complete
  packages/shared/lib/chrysalis.json
Labels: do not merge
