Repository iotaledger/firefly, pull requests merged in 2021-12, with the labels that each got.

#1654 feat: Capacitor iOS Plugin bindings
  packages/backend/bindings/capacitor/.gitignore
  packages/backend/bindings/capacitor/.npmignore
  packages/backend/bindings/capacitor/README.md
  packages/backend/bindings/capacitor/WalletActorSystemCapacitorBinding.podspec
  packages/backend/bindings/capacitor/ios/Plugin.xcodeproj/project.pbxproj
  packages/backend/bindings/capacitor/ios/Plugin/Libraries/libwallet.h
  packages/backend/bindings/capacitor/ios/Plugin/Libraries/module.modulemap
  packages/backend/bindings/capacitor/ios/Plugin/Plugin.m
  packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift
  packages/backend/bindings/capacitor/ios/PluginTests/PluginTests.swift
  packages/backend/bindings/capacitor/ios/Podfile
  packages/backend/bindings/capacitor/package.json
  packages/backend/bindings/capacitor/rollup.config.js
  packages/backend/bindings/capacitor/src/definitions.ts
  packages/backend/bindings/capacitor/src/index.ts
  packages/backend/bindings/capacitor/tsconfig.json
  packages/desktop/electron/preload.js
  packages/mobile/.gitignore
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/capacitor/lib/pincodeManager.ts
  packages/mobile/capacitor/walletPluginApi.ts
  packages/mobile/ios/App/App.xcodeproj/project.pbxproj
  packages/mobile/ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
  packages/mobile/ios/App/Podfile
  packages/mobile/lib/api.ts
  packages/mobile/lib/empty.ts
  packages/mobile/package.json
  packages/mobile/public/index.html
  packages/shared/lib/platform.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/shell/walletApi.ts
  packages/shared/lib/typings/platform.ts
  packages/shared/lib/typings/walletApi.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/setup/Password.svelte
Labels: type:feature, scope:backend, scope:desktop, scope:mobile, scope:shared

#1708 fix: make change of dev profile checkbox persistent
  packages/shared/routes/setup/Profile.svelte
Labels: type:fix, scope:shared

#1718 chore(ci): Update "verify download" link in release notes template
  .github/workflows/build-desktop.yml
Labels: scope:ci

#1725 fix: correct url to chrysalis documentation
  packages/desktop/electron/lib/menu.js
  packages/shared/routes/dashboard/settings/views/Help.svelte
Labels: type:fix

#1727 fix: zero value fiat conversion
  packages/shared/components/inputs/Amount.svelte
Labels: type:bug, scope:shared

#1724 fix: improve error message when trying to delete a non empty profile
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/Security.svelte
Labels: type:fix

#1730 chore: update dependencies
  package.json
  yarn.lock
Labels: scope:dependencies

#1720 fix: various export transaction history fixes
  packages/shared/components/modals/AccountActions.svelte
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/transactionHistory.ts
  packages/shared/lib/typings/routes.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/Advanced.svelte
Labels: type:fix

#1731 fix: airdrop selection for partial stake
  packages/shared/components/Text.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
Labels: scope:ux, type:fix

#1732 fix: partial staking UI disappearing
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/participation/stores.ts
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
Labels: type:fix

#1739 fix: reward formatting
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/utils.ts
Labels: scope:ux, type:fix

#1738 fix: amount input
  packages/shared/components/inputs/Amount.svelte
  packages/shared/lib/currency.ts
Labels: scope:ux, type:fix

#1735 feat: minimum reward time
  packages/shared/components/AccountTile.svelte
  packages/shared/components/StakingIndicator.svelte
  packages/shared/components/inputs/Amount.svelte
  packages/shared/lib/participation/api.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/participation/types.ts
  packages/shared/lib/units.ts
  packages/shared/locales/en.json
Labels: type:feature, scope:ux

#1747 fix: make close settings go back to previous tab
  packages/shared/components/Sidebar.svelte
  packages/shared/lib/router.ts
  packages/shared/routes/dashboard/settings/Settings.svelte
Labels: type:fix, scope:desktop, scope:shared

#1745 fix: remove warning on logout
  packages/shared/routes/dashboard/wallet/views/LineChart.svelte
Labels: type:fix, scope:desktop

#1746 fix: set primary node on new profile
  packages/shared/lib/network.ts
Labels: type:fix, scope:shared

#1749 fix: prevent staking on an account while it has unconfirmed transactions
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/participation/participation.ts
  packages/shared/lib/participation/types.ts
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
Labels: type:fix, scope:desktop

#1762 fix: close popup on inactive state
  packages/shared/routes/dashboard/staking/Staking.svelte
Labels: type:fix

#1753 fix: minimum reward time
  packages/backend/Cargo.lock
  packages/shared/components/AccountTile.svelte
  packages/shared/components/StakingAirdropIndicator.svelte
  packages/shared/components/StakingIndicator.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/network.ts
  packages/shared/lib/participation/participation.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/participation/stores.ts
  packages/shared/lib/participation/types.ts
  packages/shared/lib/units.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
Labels: scope:ux, type:fix

#1776 fix: decimal separator in amount
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: scope:ux, type:fix

#1791 fix: disable accounts with pending transactions
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/participation/participation.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/wallet.ts
  packages/shared/locales/en.json
Labels: scope:ux, type:fix

#1794 fix: zen guy for both airdrops
  packages/shared/locales/ja.json
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: scope:ux, type:fix

#1800 fix: locale time formatting
  packages/shared/lib/tests/mocks/i18n.ts
  packages/shared/lib/tests/time.test.ts
  packages/shared/lib/time.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/Security.svelte
Labels: type:fix, scope:shared

#1792 fix: use locale agnostic UI logic
  packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
Labels: type:fix

#1786 chore(shared): Sync source strings for staking
  packages/shared/locales/en.json
Labels: type:chore, scope:shared

#1798 fix: consistent icon sizes
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/components/popups/StakingManager.svelte
Labels: type:fix, scope:desktop

#1799 fix: format multiple messages in tooltip
  packages/shared/components/AccountTile.svelte
Labels: type:fix, scope:desktop

#1808 update: remove balance tooltip
  packages/shared/components/BalanceSummary.svelte
Labels: type:enhancement, scope:desktop

#1809 fix: staking notification badge logic and colour
  packages/shared/components/Sidebar.svelte
  packages/shared/lib/participation/stores.ts
Labels: type:fix, scope:desktop

#1810 fix: close popup on settings navigation
  packages/shared/lib/router.ts
Labels: type:fix, scope:desktop

#1811 fix: improve account tile styling
  packages/shared/components/AccountTile.svelte
  packages/shared/routes/dashboard/wallet/views/WalletActions.svelte
Labels: type:fix, scope:desktop

#1820 fix: minimum staking reward calculation
  packages/shared/components/AccountTile.svelte
  packages/shared/lib/participation/staking.ts
Labels: type:fix, scope:shared

#1824 fix: merge staking selection logic
  packages/shared/components/popups/StakingConfirmation.svelte
Labels: type:fix, scope:desktop

#1910 fix(shared): Fix issue changing node URL
  packages/shared/components/popups/AddNode.svelte
  packages/shared/routes/dashboard/settings/views/Advanced.svelte
Labels: type:fix, scope:shared

#1826 hotfix: best time duration function
  packages/shared/lib/tests/time.test.ts
  packages/shared/lib/time.ts
Labels: type:hotfix, scope:shared
