Repository iotaledger/firefly, pull requests merged in 2021-10, with the labels that each got.

#1590 chore: Update bug report form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: type:chore

#1596 fix: Close Button instead of cancel
  packages/shared/components/popups/Version.svelte
Labels: type:fix

#1492 feat: add deep links
  packages/desktop/App.svelte
  packages/desktop/electron/lib/deepLinkManager.js
  packages/desktop/electron/main.js
  packages/desktop/electron/preload.js
  packages/shared/components/Toast.svelte
  packages/shared/components/inputs/Amount.svelte
  packages/shared/lib/address.ts
  packages/shared/lib/app.ts
  packages/shared/lib/bech32.ts
  packages/shared/lib/deepLinking.ts
  packages/shared/lib/deepLinking/contextHandlers/walletContextHandler.ts
  packages/shared/lib/deepLinking/deepLinking.ts
  packages/shared/lib/electron.ts
  packages/shared/lib/notifications.ts
  packages/shared/lib/router.ts
  packages/shared/lib/typings/deepLinking/deepLinking.ts
  packages/shared/lib/typings/deepLinking/walletContext.ts
  packages/shared/lib/typings/routes.ts
  packages/shared/lib/utils.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/Settings.svelte
  packages/shared/routes/dashboard/settings/views/Advanced.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:feature
