Repository iotaledger/firefly, pull requests merged in 2022-01, with the labels that each got.

#1990 fix(shared): Localize "Advanced options" label
  packages/shared/locales/en.json
  packages/shared/routes/setup/Profile.svelte
Labels: type:fix, scope:shared

#1743 chore: allow change of install directory windows
  packages/desktop/package.json
Labels: platform:windows, type:chore

#2008 fix: Update links to wiki
  packages/desktop/electron/lib/menu.js
  packages/shared/routes/dashboard/settings/views/Help.svelte
Labels: type:fix

#2022 chore: improve issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/create-task.yml
Labels: type:chore

#2023 chore: add action Assign Bugs to Project
  .github/workflows/add-bugs-to-project.yml
Labels: type:chore

#2034 feat: close dropdown on click outside
  packages/shared/components/inputs/Dropdown.svelte
Labels: type:enhancement, scope:desktop

#2033 feat: searchable dropdown options
  packages/shared/components/inputs/Dropdown.svelte
Labels: type:enhancement, scope:desktop

#1813 feat: keep track of the last logged in profile
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/lib/app.ts
  packages/shared/lib/profile.ts
  packages/shared/routes/login/Login.svelte
  packages/shared/routes/login/views/EnterPin.svelte
Labels: type:enhancement, scope:desktop

#2164 feat: add governance to sidebar
  packages/shared/components/Sidebar.svelte
  packages/shared/components/icon/icons.js
  packages/shared/lib/typings/routes.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/governance/Governance.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceHeader.svelte
  packages/shared/routes/dashboard/governance/views/index.js
  packages/shared/routes/index.js
Labels: type:feature, scope:desktop, scope:voting

#2125 enhancement: remove conversion when unit changes on send form
  packages/shared/components/inputs/Amount.svelte
  packages/shared/lib/tests/network.test.ts
  packages/shared/tsconfig.json
Labels: type:enhancement, scope:shared

#1712 Feat: Mobile Pincode manager
  packages/mobile/capacitor/lib/pincodeManager.ts
  packages/mobile/package.json
Labels: type:feature, scope:mobile

#2178 feat: (UI) Voting dashboard: power, info & single event
  packages/shared/components/popups/GovernanceVotingPowerInfo.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/governance/Governance.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceInfo.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceVotingPower.svelte
  packages/shared/routes/dashboard/governance/views/index.js
Labels: type:feature, scope:desktop, scope:voting

#2155 Feat: Refactor settings to individual files
  packages/desktop/electron/lib/menu.js
  packages/shared/components/SettingsMenu.svelte
  packages/shared/components/SettingsNavigator.svelte
  packages/shared/lib/typings/routes.ts
  packages/shared/routes/dashboard/settings/Settings.svelte
  packages/shared/routes/dashboard/settings/views/Advanced.svelte
  packages/shared/routes/dashboard/settings/views/General.svelte
  packages/shared/routes/dashboard/settings/views/Help.svelte
  packages/shared/routes/dashboard/settings/views/Security.svelte
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
  packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
  packages/shared/routes/dashboard/settings/views/advanced/Advanced.svelte
  packages/shared/routes/dashboard/settings/views/advanced/BalanceFinder.svelte
  packages/shared/routes/dashboard/settings/views/advanced/DeepLinks.svelte
  packages/shared/routes/dashboard/settings/views/advanced/Diagnostics.svelte
  packages/shared/routes/dashboard/settings/views/advanced/ErrorLog.svelte
  packages/shared/routes/dashboard/settings/views/advanced/HiddenAccounts.svelte
  packages/shared/routes/dashboard/settings/views/advanced/MigrateLedgerIndex.svelte
  packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
  packages/shared/routes/dashboard/settings/views/advanced/NodeConfigOptions.svelte
  packages/shared/routes/dashboard/settings/views/advanced/index.js
  packages/shared/routes/dashboard/settings/views/general/Currency.svelte
  packages/shared/routes/dashboard/settings/views/general/General.svelte
  packages/shared/routes/dashboard/settings/views/general/Language.svelte
  packages/shared/routes/dashboard/settings/views/general/NetworkStatus.svelte
  packages/shared/routes/dashboard/settings/views/general/Notifications.svelte
  packages/shared/routes/dashboard/settings/views/general/Theme.svelte
  packages/shared/routes/dashboard/settings/views/general/index.js
  packages/shared/routes/dashboard/settings/views/help/Help.svelte
  packages/shared/routes/dashboard/settings/views/help/HelpSection.svelte
  packages/shared/routes/dashboard/settings/views/index.js
  packages/shared/routes/dashboard/settings/views/security/AppLock.svelte
  packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
  packages/shared/routes/dashboard/settings/views/security/ChangePincode.svelte
  packages/shared/routes/dashboard/settings/views/security/DeleteProfile.svelte
  packages/shared/routes/dashboard/settings/views/security/ExportStronghold.svelte
  packages/shared/routes/dashboard/settings/views/security/Security.svelte
  packages/shared/routes/dashboard/settings/views/security/index.js
Labels: type:refactor

#2186 Feat: Mobile Popup
  packages/mobile/App.svelte
  packages/shared/components/popups/Index.svelte
Labels: type:feature, scope:mobile

#2210 hotfix: bump wallet rs rev
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/native/Cargo.lock
  packages/desktop/package.json
Labels: type:hotfix

#2235 feat: add wallet log to desktop for dev environment
  packages/desktop/electron/preload.js
Labels: type:feature

#2241 fix: resolve crash after deleting profile
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/native/Cargo.lock
Labels: scope:dependencies, type:fix

#2244 fix: setting title consistency
  packages/shared/locales/en.json
Labels: scope:ux, platform:windows, platform:mac, platform:linux, type:fix

#2245 enhancement: setting hints
  packages/shared/components/TextHint.svelte
  packages/shared/components/index.js
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/general/Theme.svelte
Labels: type:enhancement, scope:ux, platform:windows, platform:mac, platform:linux

#2233 fix: allow delete profile with balance
  packages/backend/bindings/node/index.ts
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/lib/app.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/shell/walletApi.ts
  packages/shared/lib/typings/wallet.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/settings/views/security/DeleteProfile.svelte
Labels: type:fix

#2248 Fix: match theme colours with FF colour palette
  packages/shared/tailwind.config.js
Labels: type:fix

#2112 Feat: polish ui mobile onboarding
  packages/shared/components/OnboardingLayout.svelte
  packages/shared/components/RecoveryPhrase.svelte
  packages/shared/routes/setup/Appearance.svelte
  packages/shared/routes/setup/Welcome.svelte
  packages/shared/routes/setup/backup/views/RecoveryPhrase.svelte
  packages/shared/routes/setup/backup/views/VerifyRecoveryPhrase.svelte
  packages/shared/routes/setup/legal/Legal.svelte
Labels: scope:mobile
