Repository iotaledger/firefly, pull requests merged in 2022-04, with the labels that each got.

#2503 feat: add global back button
  packages/mobile/App.svelte
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/routes/dashboard/TopNavigation.svelte
  packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
Labels: platform:desktop, context:navigation, type:ui

#2703 fix: disallow account switching
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, platform:desktop

#2709 feat: add notification on new staking event
  packages/shared/assets/illustrations/staking/staking-notification.svg
  packages/shared/components/Illustration.svelte
  packages/shared/components/Sidebar.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/NewStakingPeriodNotification.svelte
  packages/shared/components/popups/StakingNotice.svelte
  packages/shared/lib/participation/constants.ts
  packages/shared/lib/typings/profile.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/staking/Staking.svelte
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
Labels: type:feature, context:staking

#2715 chore: use alpha in development
  packages/desktop/package.json
Labels: type:chore

#2721 chore: upload PDB files when building Windows
  .github/workflows/build-desktop.yml
Labels: type:chore, scope:ci

#2720 fix: rename account issues for 1.4.0
  packages/desktop/App.svelte
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/lib/appSettings.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/settings/views/general/ChangeProfileName.svelte
  packages/shared/routes/login/views/EnterPin.svelte
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/Profile.svelte
Labels: type:fix, 1.4.0-beta

#2702 fix: place receive at the top instead of middle
  packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
  packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
Labels: context:wallet, platform:desktop, type:ui

#2727 fix: retain original error structure when sending error to Sentry
  packages/desktop/electron/main.js
Labels: type:fix, package:desktop

#2711 fix: reactivity issue when cancelling particpation
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:fix, context:staking, platform:desktop

#2754 fix: inset window controls on mac
  packages/desktop/electron/main.js
Labels: type:fix

#2762 feat: adjust staking manager UI for single account
  packages/shared/components/TextHint.svelte
  packages/shared/components/popups/NewStakingPeriodNotification.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/locales/en.json
Labels: context:staking, type:ui

#2705 feat: query staking result files
  packages/desktop/public/index.html
  packages/shared/lib/ed25519.ts
  packages/shared/lib/migration.ts
  packages/shared/lib/participation/constants.ts
  packages/shared/lib/participation/index.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/participation/types.ts
  packages/shared/lib/tests/utils.test.ts
  packages/shared/lib/typings/profile.ts
  packages/shared/lib/utils.ts
  packages/shared/routes/dashboard/Dashboard.svelte
Labels: type:feature, context:staking

#2761 enhancement: make staking confirmation dynamic to number of airdrops
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, context:staking

#2763 fix: refactors modal
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/Sidebar.svelte
  packages/shared/components/modals/AccountActions.svelte
  packages/shared/components/modals/AccountSwitcher.svelte
  packages/shared/components/modals/Modal.svelte
  packages/shared/components/modals/NetworkIndicator.svelte
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
Labels: type:fix

#2772 fix: set selected account to newly created one
  packages/shared/routes/dashboard/Dashboard.svelte
Labels: context:wallet

#2773 fix: select unhidden account when hiding one
  packages/shared/components/modals/AccountActions.svelte
Labels: context:wallet

#2780 feat: single wallet UI polish
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/components/inputs/Toggle.svelte
  packages/shared/components/modals/AccountSwitcher.svelte
Labels: type:feature, type:ui

#2785 chore: update wallet.rs to fix Unicode paths on Windows
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/native/Cargo.lock
Labels: type:chore, type:fix, package:backend

#2768 enhancement: change airdrop tile for multiple periods
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/native/Cargo.lock
  packages/desktop/public/index.html
  packages/shared/components/Sidebar.svelte
  packages/shared/components/StakingAirdropIndicator.svelte
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/components/StakingIndicator.svelte
  packages/shared/components/index.js
  packages/shared/components/popups/NewStakingPeriodNotification.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/components/popups/Transaction.svelte
  packages/shared/lib/assets.ts
  packages/shared/lib/ed25519.ts
  packages/shared/lib/participation/constants.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/participation/stores.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/staking/Staking.svelte
  packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
Labels: type:enhancement, context:staking

#2787 enhancement: re cache all staking rewards on balance finder
  packages/shared/components/popups/BalanceFinder.svelte
Labels: type:enhancement, context:settings

#2790 fix: check if an onClick handler is defined before calling it
  packages/shared/components/Profile.svelte
Labels: type:fix, package:shared

#2786 feat: adds single account guide
  packages/desktop/App.svelte
  packages/mobile/App.svelte
  packages/shared/assets/illustrations/onboarding/single-account-guide-desktop.svg
  packages/shared/assets/illustrations/onboarding/white-arrow.svg
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/Illustration.svelte
  packages/shared/components/popups/CrashReporting.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/SingleAccountGuide.svelte
  packages/shared/lib/popup.ts
  packages/shared/lib/typings/profile.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/TopNavigation.svelte
  packages/shared/routes/login/views/EnterPin.svelte
  packages/shared/routes/login/views/SelectProfile.svelte
Labels: context:wallet

#2796 fix: error handling of invalid timestamps
  packages/shared/components/ActivityDetail.svelte
  packages/shared/components/ActivityRow.svelte
  packages/shared/lib/transactionHistory.ts
  packages/shared/lib/wallet.ts
  packages/shared/locales/en.json
Labels: type:fix

#2812 fix: missing duration arguments during staking
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:fix, context:staking

#2813 fix: moves prevent account switch logic to account buttons
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/modals/AccountSwitcher.svelte
Labels: context:wallet

#2814 fix: adds responsiveness to receive qr code
  packages/shared/components/QR.svelte
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
Labels: context:wallet

#2816 fix: changes modal interaction timeout
  packages/shared/components/modals/Modal.svelte
Labels: context:wallet

#2817 fix: adds issue report url to allowed list
  packages/desktop/electron/main.js
Labels: context:wallet

#2818 fix: adds reset and focus function to repeat pin on mount
  packages/shared/routes/setup/protect/views/RepeatPin.svelte
Labels: context:onboarding

#2819 fix: only inset window controls on mac
  packages/desktop/electron/main.js
Labels: type:fix

#2820 chore: merge desktop 1.4.2 into develop
  packages/backend/Cargo.lock
  packages/desktop/package.json
  packages/shared/components/ActivityDetail.svelte
  packages/shared/components/ActivityRow.svelte
  packages/shared/components/Profile.svelte
  packages/shared/lib/transactionHistory.ts
  packages/shared/locales/en.json
Labels: type:chore

#2827 enhancement: improve balance finder UX and wording
  packages/shared/components/popups/BalanceFinder.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, type:fix

#2846 fix: wording of backup notification title
  packages/shared/locales/en.json
Labels: type:fix

#2839 enhancement: add warning emphasis for asset tile
  packages/shared/components/ActivityRow.svelte
  packages/shared/components/StakingAssetTile.svelte
Labels: type:fix, context:staking

#2847 fix: update spacing and styling of staking manager
  packages/shared/components/popups/StakingManager.svelte
Labels: type:fix

#2845 fix: single account guide opening before accounts loaded
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/routes/dashboard/Dashboard.svelte
Labels: type:fix

#2849 fix: make account naming consistent
  packages/shared/lib/wallet.ts
Labels: type:fix

#2844 fix: single account guide wording
  packages/shared/components/popups/SingleAccountGuide.svelte
  packages/shared/locales/en.json
Labels: type:fix

#2852 fix: ledger migration not working because of missing ledger object on platform api
  packages/desktop/electron/electronApi.js
Labels: type:fix

#2859 enhancement: persist send and recieve form when switching wallet
  packages/shared/components/modals/AccountSwitcher.svelte
  packages/shared/components/popups/HideAccount.svelte
  packages/shared/lib/app.ts
  packages/shared/lib/common/deep-links/types/wallet-context.type.ts
  packages/shared/lib/common/deep-links/wallet-context-handler.ts
  packages/shared/lib/core/router/helper.ts
  packages/shared/lib/typings/sendParams.ts
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:enhancement

#2864 chore: Re-enable Crowdin translations on `develop` branch
  .github/workflows/crowdin.yml
Labels: type:chore, scope:ci

#2862 fix: adjust logic for constructing duration args
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:fix, context:staking

#2866 fix: leaving dust error message
  packages/shared/lib/shell/walletErrors.ts
  packages/shared/lib/typings/events.ts
Labels: type:fix

#2868 fix: decapatilise some translation strings
  packages/shared/locales/en.json
Labels: type:fix

#2863 fix: use dynamic date for staking event
  packages/shared/components/popups/NewStakingPeriodNotification.svelte
  packages/shared/lib/participation/constants.ts
  packages/shared/locales/en.json
Labels: type:fix, context:staking

#2877 fix: improve formatting on staking asset tile
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/lib/assets.ts
Labels: type:fix

#2875 refactor: pass assembly event id to participationOverview call
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/index.ts
  packages/backend/bindings/node/native/Cargo.lock
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/participation/api.ts
  packages/shared/lib/participation/bridge.ts
  packages/shared/lib/participation/participation.ts
  packages/shared/lib/typings/walletApi.ts
  packages/shared/lib/walletApiListeners.ts
  packages/shared/routes/dashboard/staking/Staking.svelte
Labels: type:refactor, package:backend, package:shared, context:staking

#2885 enhancement: add new staking animations
  packages/shared/assets/animations/staking/ended.json
  packages/shared/assets/animations/staking/info-commencing.json
  packages/shared/assets/animations/staking/info-ended.json
  packages/shared/assets/animations/staking/info-holding-0.json
  packages/shared/assets/animations/staking/info-holding-1.json
  packages/shared/assets/animations/staking/info-holding-2.json
  packages/shared/assets/animations/staking/info-holding-3.json
  packages/shared/assets/animations/staking/info-upcoming.json
  packages/shared/assets/animations/staking/prestaking.json
  packages/shared/assets/animations/staking/staking-assembly-with-shimmer-rewards.json
  packages/shared/assets/animations/staking/staking-assembly-without-shimmer-rewards.json
  packages/shared/assets/animations/staking/staking-both.json
  packages/shared/assets/animations/staking/staking-neither.json
  packages/shared/assets/animations/staking/staking-shimmer-with-assembly-rewards.json
  packages/shared/assets/animations/staking/staking-shimmer-without-assembly-rewards.json
  packages/shared/components/Animation.svelte
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:enhancement, context:staking

#2887 fix: use total rewards for staking animations
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:fix, context:staking

#2888 fix: handle null participation overview object
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:fix, context:staking

#2892 chore: bump Crowdin action to 1.4.8
  .github/workflows/crowdin.yml
Labels: type:chore, scope:ci

#2899 feat: polish wallet switcher css
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/modals/AccountSwitcher.svelte
Labels: type:ui

#2905 chore: removed scss and css files from lint-staged
  package.json
Labels: type:chore

#2908 Feat: polish profile modal
  packages/shared/components/modals/Modal.svelte
  packages/shared/components/modals/ProfileActions.svelte
Labels: type:ui

#2909 enhancement: add dynamic dates in staking info
  packages/shared/lib/participation/constants.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:enhancement, context:staking

#2889 fix: change reactivity in merge stake flow
  packages/shared/components/popups/StakingManager.svelte
Labels: type:fix, context:staking

#2902 fix: attempt rename profile folder everytime app is run
  packages/desktop/App.svelte
  packages/desktop/electron/electronApi.js
  packages/shared/lib/appSettings.ts
  packages/shared/lib/profile.ts
Labels: type:fix

#2901 fix: enable merging of assembly stake after restoring
  packages/shared/components/popups/StakingConfirmation.svelte
Labels: type:fix, context:staking

#2865 fix: ignore Chromium network errors
  packages/desktop/electron/lib/errorHandling.js
  packages/desktop/electron/main.js
  packages/desktop/index.js
Labels: type:fix

#2917 fix: missing auto subscription in StakingInfo
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:fix

#2918 chore: update wallet.rs rev
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/native/Cargo.lock
Labels: type:chore

#2921 fix: improve loading of event state
  packages/shared/lib/participation/stores.ts
  packages/shared/routes/dashboard/Dashboard.svelte
Labels: type:fix, context:staking

#2926 fix: reactivity issue on tx history icon & color
  packages/shared/components/ActivityRow.svelte
Labels: type:fix

#2932 enhancement: remove staking animation when participation not detected
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:enhancement, context:staking

#2934 enhancement: improve transaction history
  packages/shared/components/ActivityRow.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet

#2938 update: staking blog link with new link
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:enhancement, context:staking

#2941 chore: prepare constants for staking period 2
  packages/shared/lib/participation/constants.ts
Labels: type:chore

#2940 chore: add staking result file urls
  packages/desktop/public/index.html
  packages/shared/lib/participation/constants.ts
Labels: type:enhancement

#2936 fix: minimum reward warning logic
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/components/popups/Transaction.svelte
Labels: type:fix, context:staking

#2945 chore: bump wallet.rs rev to fix account discovery
  packages/backend/Cargo.lock
  packages/backend/Cargo.toml
  packages/backend/bindings/node/native/Cargo.lock
Labels: type:chore, type:fix

#2944 enhancement: add video to single account guide
  packages/shared/assets/videos/single-account-guide.mp4
  packages/shared/components/popups/SingleAccountGuide.svelte
Labels: context:navigation

#2948 chore: increment desktop version number to 1.5.0
  packages/desktop/package.json
Labels: type:chore

#2953 fix: fix reward calc
  packages/shared/lib/participation/staking.ts
Labels: type:fix

#2957 fix: windows top resize
  packages/shared/components/TitleBar.svelte
Labels: type:fix

#2620 feat: adds voting tx locale/icon
  packages/shared/components/ActivityRow.svelte
  packages/shared/components/icon/icons.js
  packages/shared/lib/participation/api.ts
  packages/shared/lib/participation/participation.ts
  packages/shared/lib/participation/stores.ts
  packages/shared/lib/participation/types.ts
  packages/shared/locales/en.json
Labels: context:voting

#2890 feat: adds voting info tooltips
  packages/shared/components/GovernanceInfoTooltip.svelte
  packages/shared/components/index.js
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
Labels: context:voting

#3015 feat: add voting app notifications
  packages/shared/lib/walletApiListeners.ts
  packages/shared/locales/en.json
Labels: context:voting

#3016 Feat: update voting flows
  packages/shared/components/popups/GovernanceManager.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/lib/participation/account.ts
  packages/shared/routes/dashboard/governance/views/GovernanceDashboard.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceInfo.svelte
Labels: context:voting

#3033 fix: handle undefined name in account switcher
  packages/shared/components/AccountSwitcher.svelte
Labels: type:fix

#3017 enhancement: add backup for retrieving previous airdrop rewards
  packages/desktop/public/index.html
  packages/shared/lib/participation/constants.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:staking

#3013 enhancement: improve wallet switcher by showing balance
  packages/shared/components/Button.svelte
  packages/shared/components/icon/icons.js
  packages/shared/components/inputs/Number.svelte
  packages/shared/components/modals/AccountSwitcher.svelte
  packages/shared/components/popups/CreateAccount.svelte
  packages/shared/locales/en.json
  packages/shared/routes/login/views/SelectProfile.svelte
  packages/shared/routes/setup/Setup.svelte
  packages/shared/routes/setup/ledger/views/InstallationGuide.svelte
Labels: type:enhancement, context:wallet, context:navigation

#3048 chore: bump linting dependencies as we have upgraded svelte version
  .eslintrc.js
  package.json
  packages/shared/components/Text.svelte
  packages/shared/package.json
  yarn.lock
Labels: scope:dependencies, type:chore

#3049 feat: basic transaction details popup
  packages/shared/components/ActivityDetail.svelte
  packages/shared/components/Text.svelte
  packages/shared/components/atoms/KeyValueBlock.svelte
  packages/shared/components/atoms/index.js
  packages/shared/components/atoms/pills/ActivityTypePill.svelte
  packages/shared/components/atoms/pills/Pill.svelte
  packages/shared/components/atoms/pills/index.js
  packages/shared/components/index.js
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/utils/transactionObject.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
Labels: type:feature, context:wallet

#3036 feat: move receive form to popup
  packages/desktop/electron/lib/menu.js
  packages/desktop/electron/lib/menuState.js
  packages/desktop/lib/helpers.ts
  packages/shared/components/atoms/boxes/AddressBox.svelte
  packages/shared/components/atoms/boxes/Box.svelte
  packages/shared/components/atoms/boxes/KeyValueBox.svelte
  packages/shared/components/atoms/boxes/index.js
  packages/shared/components/atoms/index.js
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/ReceiveAddressPopup.svelte
  packages/shared/components/popups/ReceivePopup.svelte
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/lib/utils/transactionObject.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
  packages/shared/routes/dashboard/wallet/views/index.js
Labels: type:feature, type:refactor, context:wallet
