Repository iotaledger/firefly, pull requests merged in 2022-11, with the labels that each got.

#5005 enhancement: add nft store
  packages/shared/components/atoms/tiles/tileFooters/AsyncActivityTileFooter.svelte
  packages/shared/components/modals/NftSelector.svelte
  packages/shared/components/molecules/NftDetails.svelte
  packages/shared/components/popups/MintNftFormPopup.svelte
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/lib/core/nfts/actions/addNftInAllAccountNfts.ts
  packages/shared/lib/core/nfts/actions/addOrUpdateNftInAllAccountNfts.ts
  packages/shared/lib/core/nfts/actions/getNftByIdFromAllAccountNfts.ts
  packages/shared/lib/core/nfts/actions/index.ts
  packages/shared/lib/core/nfts/actions/loadNftsForActiveProfile.ts
  packages/shared/lib/core/nfts/actions/setAccountNftsInAllAccountNfts.ts
  packages/shared/lib/core/nfts/actions/updateNftInAllAccountNfts.ts
  packages/shared/lib/core/nfts/constants/default-nft-name.constant.ts
  packages/shared/lib/core/nfts/constants/index.ts
  packages/shared/lib/core/nfts/index.ts
  packages/shared/lib/core/nfts/interfaces/index.ts
  packages/shared/lib/core/nfts/interfaces/irc27-metadata.interface.ts
  packages/shared/lib/core/nfts/interfaces/nft.interface.ts
  packages/shared/lib/core/nfts/stores/all-account-nfts.store.ts
  packages/shared/lib/core/nfts/stores/index.ts
  packages/shared/lib/core/nfts/stores/selected-account-nfts.store.ts
  packages/shared/lib/core/nfts/types/index.ts
  packages/shared/lib/core/nfts/types/mime-type.type.ts
  packages/shared/lib/core/nfts/utils/buildNftFromNftOutput.ts
  packages/shared/lib/core/nfts/utils/getIsOwnedFromUnspentNftOutput.ts
  packages/shared/lib/core/nfts/utils/index.ts
  packages/shared/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/lib/core/profile-manager/actions/events-handlers/handleNewOutputEvent.ts
  packages/shared/lib/core/profile-manager/actions/events-handlers/handleSpentOutputEvent.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/wallet/actions/activities/generateActivitiesFromProcessedTransactions.ts
  packages/shared/lib/core/wallet/actions/activities/preprocessOutputsForAccount.ts
  packages/shared/lib/core/wallet/actions/activities/preprocessTransactionsForAccount.ts
  packages/shared/lib/core/wallet/actions/activities/setAsyncStatusOfAccountActivities.ts
  packages/shared/lib/core/wallet/actions/mintNft.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/nft-activity-data.interface.ts
  packages/shared/lib/core/wallet/stores/mint-nft-details.store.ts
  packages/shared/lib/core/wallet/types/index.ts
  packages/shared/lib/core/wallet/utils/buildNftOutputData.ts
  packages/shared/lib/core/wallet/utils/outputs/getExpirationDateFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getIssuerFromNftOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getMetadataFromNftOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getNftActivityData.ts
  packages/shared/lib/core/wallet/utils/outputs/getNftId.ts
  packages/shared/lib/core/wallet/utils/outputs/index.ts
Labels: type:enhancement, context:wallet, stardust

#5076 fix: transaction details
  packages/shared/components/ActivityRow.svelte
  packages/shared/lib/wallet.ts
Labels: bug report, type:fix, package:desktop, package:mobile, desktop-1.7.0

#5085 fix: correct recipient address
  packages/shared/components/ActivityRow.svelte
  packages/shared/lib/wallet.ts
Labels: type:fix

#5019 feat: setup add wallet feature for stardust mobile
  packages/mobile/components/ColorPicker.svelte
  packages/mobile/components/Drawer.svelte
  packages/mobile/components/StrongholdUnlock.svelte
  packages/mobile/components/index.js
  packages/mobile/features/features.ts
  packages/mobile/lib/routers/enums/account-switcher-route.enum.ts
  packages/mobile/lib/routers/enums/index.ts
  packages/mobile/lib/routers/helper.ts
  packages/mobile/lib/routers/subrouters/account-switcher-router.ts
  packages/mobile/lib/routers/subrouters/index.ts
  packages/mobile/views/dashboard/DashboardRouter.svelte
  packages/mobile/views/dashboard/DashboardView.svelte
  packages/mobile/views/dashboard/drawers/AccountSwitcherDrawer.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/AccountSwitcherDrawer.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/AccountSwitcherRouter.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/index.js
  packages/mobile/views/dashboard/drawers/account-switcher/views/AccountSwitcher.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/views/CreateAccount.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/views/index.js
  packages/mobile/views/dashboard/drawers/index.js
  packages/mobile/views/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte
Labels: platform:mobile, package:mobile, type:ui, stardust

#5086 fix: stardust mobile utils imports
  packages/mobile/components/ColorPicker.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/views/CreateAccount.svelte
Labels: type:fix, platform:mobile, package:mobile, stardust

#5075 feat: tag & metadata support for deep links
  packages/shared/lib/address.ts
  packages/shared/lib/common/deep-links/enums/wallet-context.enum.ts
  packages/shared/lib/common/deep-links/types/deep-link-request.type.ts
  packages/shared/lib/common/deep-links/types/wallet-context.type.ts
  packages/shared/lib/common/deep-links/wallet-context-handler.ts
  packages/shared/lib/tests/address.test.ts
  packages/shared/lib/typings/sendParams.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/wallet/Wallet.svelte
Labels: desktop-1.7.0

#5090 feat/add NftPlaceholder component with rough outline
  packages/shared/components/atoms/tiles/tileContents/NftActivityTileContent.svelte
  packages/shared/components/enums/index.ts
  packages/shared/components/enums/nft-media-size.enum.ts
  packages/shared/components/molecules/NftMediaContainer.svelte
  packages/shared/components/molecules/NftPlaceholderIcon.svelte
  packages/shared/components/molecules/index.js
  packages/shared/components/popups/send/SendNftFormPopup.svelte
  packages/shared/lib/auxiliary/icon/constants/icon-svg.ts
  packages/shared/lib/auxiliary/icon/enums/icon.enum.ts
  packages/shared/lib/auxiliary/icon/svgs/index.ts
  packages/shared/lib/auxiliary/icon/svgs/picture.svg.ts
  packages/shared/lib/core/nfts/enums/index.ts
  packages/shared/lib/core/nfts/enums/parent-mime-type.enum.ts
  packages/shared/lib/core/nfts/index.ts
  packages/shared/tailwind.config.js
Labels: type:feature, stardust, context:collectibles

#5088 chore: remove electron dep from mobile `App.svelte`
  packages/mobile/App.svelte
Labels: type:chore, platform:mobile, package:mobile, stardust

#5018 enhancement: merge send forms
  packages/mobile/views/dashboard/drawers/send/views/RecipientView.svelte
  packages/shared/components/atoms/Tabs.svelte
  packages/shared/components/atoms/buttons/SendButton.svelte
  packages/shared/components/atoms/index.js
  packages/shared/components/molecules/NftDetails.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/send/SendConfirmationPopup.svelte
  packages/shared/components/popups/send/SendFormPopup.svelte
  packages/shared/components/popups/send/SendNftConfirmationPopup.svelte
  packages/shared/components/popups/send/SendNftFormPopup.svelte
  packages/shared/components/popups/send/index.js
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendFormOperation.ts
  packages/shared/lib/contexts/onboarding/actions/claimShimmerRewards.ts
  packages/shared/lib/core/collectibles/enums/index.ts
  packages/shared/lib/core/collectibles/enums/mime-type.enum.ts
  packages/shared/lib/core/ledger/helpers/deconstructLedgerVerificationProps.ts
  packages/shared/lib/core/ledger/utils/handleLedgerError.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/sendNft.ts
  packages/shared/lib/core/wallet/actions/sendOutput.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/new-nft-transaction-details.interface.ts
  packages/shared/lib/core/wallet/interfaces/new-transaction-details.interface.ts
  packages/shared/lib/core/wallet/interfaces/nft-activity-data.interface.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/stores/new-nft-transaction-details.store.ts
  packages/shared/lib/core/wallet/stores/new-transaction-details.store.ts
  packages/shared/lib/core/wallet/types/index.ts
  packages/shared/lib/core/wallet/types/new-transaction-details.type.ts
  packages/shared/lib/core/wallet/utils/buildNftOutputData.ts
  packages/shared/lib/core/wallet/utils/getOutputOptions.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/outputs/getNftActivityData.ts
  packages/shared/lib/core/wallet/utils/outputs/getStorageDepositFromOutput.ts
  packages/shared/locales/en.json
Labels: type:enhancement, type:refactor, context:wallet, stardust

#5097 feat-mobile: setup profile actions drawer
  packages/mobile/components/Drawer.svelte
  packages/mobile/components/buttons/ProfileActionsButton.svelte
  packages/mobile/lib/routers/enums/dashboard-route.enum.ts
  packages/mobile/views/dashboard/DashboardRouter.svelte
  packages/mobile/views/dashboard/drawers/index.js
  packages/mobile/views/dashboard/drawers/profile-actions/ProfileActionsDrawer.svelte
  packages/mobile/views/dashboard/drawers/profile-actions/index.js
Labels: type:feature, platform:mobile, context:wallet, package:mobile, stardust

#5082 refactor: transaction history lib file
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/transactionHistory.ts
Labels: type:refactor, stardust

#5096 refactor: `device` lib file
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/capacitor/lib/barcodeManager.ts
  packages/mobile/components/QRScanner.svelte
  packages/mobile/components/index.js
  packages/mobile/lib/auxiliary/scanner/actions/index.ts
  packages/mobile/lib/auxiliary/scanner/actions/startScanner.ts
  packages/mobile/lib/auxiliary/scanner/actions/stopScanner.ts
  packages/mobile/lib/auxiliary/scanner/classes/barcode-scanner.class.ts
  packages/mobile/lib/auxiliary/scanner/classes/index.ts
  packages/mobile/lib/auxiliary/scanner/constants/index.ts
  packages/mobile/lib/auxiliary/scanner/constants/open-scanner-body-class.constant.ts
  packages/mobile/lib/auxiliary/scanner/index.ts
  packages/mobile/lib/auxiliary/scanner/stores/index.ts
  packages/mobile/lib/auxiliary/scanner/stores/show-camera-scanner.store.ts
  packages/shared/components/index.js
  packages/shared/lib/device.ts
  packages/shared/lib/tests/__mocks__/platform.mock.ts
  packages/shared/lib/typings/barcodeManager.ts
  packages/shared/lib/typings/platform.ts
Labels: type:refactor, stardust

#5094 refactor: `electron` lib file
  packages/desktop/App.svelte
  packages/desktop/index.js
  packages/desktop/lib/electron.ts
  packages/desktop/sentry.js
  packages/desktop/tsconfig.json
Labels: type:refactor, stardust

#5008 enhancement: display amount transaction details
  packages/shared/components/atoms/AmountBox.svelte
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/lib/core/utils/string.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts
Labels: type:enhancement, stardust

#5140 fix: add default date to expiration date picker
  packages/shared/components/inputs/ExpirationDateTimePicker.svelte
Labels: type:fix, context:wallet, stardust

#5049 chore: move shared features to desktop
  packages/desktop/components/AccountActivity.svelte
  packages/desktop/components/SendButton.svelte
  packages/desktop/components/SettingsMenu.svelte
  packages/desktop/components/index.js
  packages/desktop/electron/lib/menu.js
  packages/desktop/electron/main.js
  packages/desktop/features/developer-tools.features.ts
  packages/desktop/features/features.ts
  packages/desktop/features/onboarding.features.ts
  packages/desktop/tsconfig.json
  packages/desktop/views/dashboard/settings/views/SettingsHome.svelte
  packages/desktop/views/dashboard/settings/views/advanced/Advanced.svelte
  packages/desktop/views/dashboard/settings/views/general/General.svelte
  packages/desktop/views/dashboard/settings/views/help/Help.svelte
  packages/desktop/views/dashboard/settings/views/security/Security.svelte
  packages/desktop/views/dashboard/wallet/Wallet.svelte
  packages/desktop/webpack.config.js
  packages/mobile/components/TopBar.svelte
  packages/mobile/lib/contexts/dashboard/constants/initial-active-dashboard-tab.constant.ts
  packages/mobile/views/dashboard/DashboardRouter.svelte
  packages/mobile/views/dashboard/DashboardView.svelte
  packages/mobile/views/dashboard/drawers/AccountSwitcherDrawer.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/views/AccountSwitcher.svelte
  packages/mobile/views/dashboard/tabs/TabNavigator.svelte
  packages/mobile/views/onboarding/views/app-setup/views/WelcomeView.svelte
  packages/mobile/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/mobile/views/onboarding/views/network-setup/views/ChooseProtocolView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupRecoveredView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupView.svelte
  packages/shared/components/atoms/buttons/index.js
  packages/shared/components/index.js
  packages/shared/components/organisms/index.js
  packages/shared/tsconfig.json
Labels: type:chore, stardust

#5144 refactor: `platform` lib file
  packages/desktop/lib/electron.ts
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/desktop/views/dashboard/settings/views/advanced/DeepLinks.svelte
  packages/desktop/views/dashboard/settings/views/help/HelpSection.svelte
  packages/desktop/views/dashboard/settings/views/security/ChangePincode.svelte
  packages/desktop/views/login/views/EnterPinView.svelte
  packages/desktop/views/onboarding/views/app-setup/views/ConditionsOfUse.svelte
  packages/mobile/App.svelte
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/capacitor/lib/deepLinkManager.ts
  packages/mobile/capacitor/lib/notificationManager.ts
  packages/mobile/capacitor/lib/pincodeManager.ts
  packages/mobile/lib/auxiliary/scanner/classes/barcode-scanner.class.ts
  packages/mobile/views/login/views/EnterPinView.svelte
  packages/shared/components/TitleBar.svelte
  packages/shared/components/molecules/NftDetails.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/Diagnostics.svelte
  packages/shared/components/popups/LedgerConnectionGuidePopup.svelte
  packages/shared/components/popups/LegalUpdate.svelte
  packages/shared/components/popups/Version.svelte
  packages/shared/lib/auxiliary/deep-link/actions/resetDeepLink.ts
  packages/shared/lib/auxiliary/deep-link/index.ts
  packages/shared/lib/auxiliary/deep-link/interfaces/index.ts
  packages/shared/lib/auxiliary/notification/actions/showNotification.ts
  packages/shared/lib/auxiliary/notification/interfaces/index.ts
  packages/shared/lib/contexts/onboarding/actions/backupInitialStronghold.ts
  packages/shared/lib/contexts/onboarding/actions/destroyShimmerClaimingProfileManager.ts
  packages/shared/lib/contexts/onboarding/actions/initialisePincodeManager.ts
  packages/shared/lib/contexts/onboarding/helpers/copyStrongholdFileToProfileDirectory.ts
  packages/shared/lib/contexts/settings/actions/exportStronghold.ts
  packages/shared/lib/core/app/actions/cancelAppUpdateDownload.ts
  packages/shared/lib/core/app/actions/downloadAppUpdate.ts
  packages/shared/lib/core/app/actions/registerAppUpdateEvents.ts
  packages/shared/lib/core/app/classes/index.ts
  packages/shared/lib/core/app/classes/platform.class.ts
  packages/shared/lib/core/app/index.ts
  packages/shared/lib/core/app/interfaces/index.ts
  packages/shared/lib/core/app/interfaces/managers/deep-link-manager.interface.ts
  packages/shared/lib/core/app/interfaces/managers/index.ts
  packages/shared/lib/core/app/interfaces/managers/notification-manager.interface.ts
  packages/shared/lib/core/app/interfaces/managers/pincode-manager.interface.ts
  packages/shared/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/lib/core/app/interfaces/platform.interface.ts
  packages/shared/lib/core/app/stores/app-version-details.store.ts
  packages/shared/lib/core/app/utils/checkForAppUpdate.ts
  packages/shared/lib/core/app/utils/installAppUpdate.ts
  packages/shared/lib/core/profile/actions/active-profile/resetActiveProfile.ts
  packages/shared/lib/core/profile/actions/active-profile/setActiveProfile.ts
  packages/shared/lib/core/profile/actions/profiles/cleanupEmptyProfiles.ts
  packages/shared/lib/core/profile/utils/getStorageDirectoryOfProfiles.ts
  packages/shared/lib/core/profile/utils/removeProfileFolder.ts
  packages/shared/lib/core/utils/os.ts
  packages/shared/lib/platform.ts
  packages/shared/lib/tests/__mocks__/platform.mock.ts
  packages/shared/lib/typings/events.ts
  packages/shared/lib/typings/validator.ts
Labels: type:refactor, stardust

#5157 enhancement: nft send form improvements
  packages/shared/components/popups/send/SendConfirmationPopup.svelte
  packages/shared/components/popups/send/SendFormPopup.svelte
  packages/shared/lib/core/network/constants/network-address.constant.ts
  packages/shared/lib/core/network/enums/destination-network.enum.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, stardust

#5145 refactor: `typings` lib folder
  packages/mobile/capacitor/walletPluginApi.ts
  packages/shared/components/Button.svelte
  packages/shared/components/Link.svelte
  packages/shared/lib/core/account/actions/buildAccountState.ts
  packages/shared/lib/core/account/enums/index.ts
  packages/shared/lib/core/account/enums/signer-type.enum.ts
  packages/shared/lib/core/account/interfaces/account-state.interface.ts
  packages/shared/lib/core/utils/interfaces/element.interface.ts
  packages/shared/lib/core/utils/interfaces/index.ts
  packages/shared/lib/core/utils/ui.ts
  packages/shared/lib/typings/events.ts
  packages/shared/lib/typings/index.ts
  packages/shared/lib/typings/message.ts
  tsconfig.lint.json
Labels: type:refactor, stardust

#5091 refactor: improve profile object migration
  packages/desktop/App.svelte
  packages/desktop/views/onboarding/views/profile-backup/views/BackupStrongholdView.svelte
  packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingFlow.ts
  packages/shared/lib/contexts/onboarding/helpers/convertOnboardingProfileToPersistedProfile.ts
  packages/shared/lib/contexts/onboarding/helpers/sanitizeOnboardingProfile.ts
  packages/shared/lib/core/error/actions/logAndNotifyError.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/profile/actions/active-profile/isActiveProfileOutdated.ts
  packages/shared/lib/core/profile/actions/active-profile/migrateActiveProfile.ts
  packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/profile/actions/profiles/index.ts
  packages/shared/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/lib/core/profile/constants/index.ts
  packages/shared/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/lib/core/profile/stores/current-profile-version.store.ts
  packages/shared/lib/core/profile/stores/index.ts
  packages/shared/lib/core/utils/object.ts
  packages/shared/lib/core/utils/tests/utils.test.ts
Labels: type:refactor, stardust

#5021 enhancement: nft developer tool
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/inputs/TextInput.svelte
  packages/shared/components/molecules/NftDetails.svelte
  packages/shared/components/popups/MintNftConfirmationPopup.svelte
  packages/shared/components/popups/MintNftFormPopup.svelte
  packages/shared/lib/core/collectibles/index.ts
  packages/shared/lib/core/nfts/enums/index.ts
  packages/shared/lib/core/nfts/enums/supported-mime-type.enum.ts
  packages/shared/locales/en.json
Labels: type:enhancement, stardust

#5162 feat-mobile: header section for profile action view
  packages/mobile/App.svelte
  packages/mobile/views/dashboard/drawers/account-switcher/views/AccountSwitcher.svelte
  packages/mobile/views/dashboard/drawers/profile-actions/ProfileActionsDrawer.svelte
Labels: type:feature, platform:mobile, context:wallet, package:mobile

#5161 fix: send flow polishing
  packages/desktop/components/SendButton.svelte
  packages/shared/components/popups/send/SendConfirmationPopup.svelte
  packages/shared/components/popups/send/SendFormPopup.svelte
  packages/shared/locales/en.json
Labels: context:wallet, type:ui, stardust

#5137 refactor: extract validations for selection inputs
  docs/specifications/activities/class-diagram.md
  packages/shared/components/index.js
  packages/shared/components/inputs/AliasInput.svelte
  packages/shared/components/inputs/NetworkInput.svelte
  packages/shared/components/inputs/NftInput.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/interfaces/index.ts
  packages/shared/components/interfaces/option.interface.ts
  packages/shared/components/modals/AliasSelector.svelte
  packages/shared/components/modals/NetworkSelector.svelte
  packages/shared/components/modals/NftSelector.svelte
  packages/shared/components/modals/index.js
  packages/shared/components/molecules/SelectorInput.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/send/SendFormPopup.svelte
  packages/shared/lib/core/utils/constants/index.ts
  packages/shared/lib/core/utils/constants/max-bytes.constant.ts
  packages/shared/lib/core/utils/crypto.ts
  packages/shared/lib/core/wallet/constants/address-letter.constants.ts
  packages/shared/lib/core/wallet/constants/address-type-map.constant.ts
  packages/shared/lib/core/wallet/constants/index.ts
  packages/shared/locales/en.json
Labels: type:refactor, context:wallet, stardust

#5195 fix: fix update popup props function
  packages/shared/lib/auxiliary/popup/stores/popup-state.store.ts
Labels: type:fix, stardust

#5146 refactor: remove routing logic for core modules
  packages/desktop/App.svelte
  packages/desktop/components/SidebarTab.svelte
  packages/desktop/lib/routers/actions/index.ts
  packages/desktop/lib/routers/actions/initialiseRouters.ts
  packages/desktop/lib/routers/actions/openSettings.ts
  packages/desktop/lib/routers/actions/resetRouterForAppContext.ts
  packages/desktop/lib/routers/actions/resetRouters.ts
  packages/desktop/lib/routers/index.ts
  packages/desktop/lib/routers/interfaces/index.ts
  packages/desktop/lib/routers/interfaces/sidebar-tab.interface.ts
  packages/desktop/lib/routers/utils/getRouterForAppContext.ts
  packages/desktop/lib/routers/utils/getSubroutersForAppContext.ts
  packages/desktop/lib/routers/utils/index.ts
  packages/desktop/views/dashboard/Sidebar.svelte
  packages/shared/components/modals/AccountActionsMenu.svelte
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingFlow.ts
  packages/shared/lib/core/app/enums/app-context.enum.ts
  packages/shared/lib/core/app/enums/index.ts
  packages/shared/lib/core/app/interfaces/platform-event-map.interface.ts
  packages/shared/lib/core/app/interfaces/platform.interface.ts
  packages/shared/lib/core/profile-manager/actions/deleteAccount.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/lib/core/router/actions/index.ts
  packages/shared/lib/core/router/actions/initialiseRouterManager.ts
  packages/shared/lib/core/router/actions/resetWalletRoute.ts
  packages/shared/lib/core/router/enums/index.ts
  packages/shared/lib/core/router/enums/router-manager-extension-name.enum.ts
  packages/shared/lib/core/router/index.ts
  packages/shared/lib/core/router/interfaces/index.ts
  packages/shared/lib/core/router/interfaces/router-manager-options.interface.ts
  packages/shared/lib/core/router/interfaces/router-manager.interface.ts
  packages/shared/lib/core/router/stores/index.ts
  packages/shared/lib/core/router/stores/router-manager.store.ts
  packages/shared/lib/core/router/types/index.ts
  packages/shared/lib/core/router/types/router-manager-extension-function.type.ts
  packages/shared/lib/core/router/types/router-manager-extension.type.ts
Labels: type:refactor, stardust

#5169 feat: burn native tokens
  packages/desktop/features/features.ts
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/lib/core/wallet/actions/burnAsset.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/locales/en.json
Labels: type:feature, context:wallet, stardust

#5207 fix: filter selected wallet from recipient input
  packages/shared/components/inputs/RecipientInput.svelte
Labels: type:fix, stardust

#5200 refactor: remove routing logic for `context` modules
  packages/desktop/App.svelte
  packages/desktop/lib/routers/actions/goToAppContext.ts
  packages/desktop/lib/routers/actions/index.ts
  packages/desktop/lib/routers/helpers/getAppRouteForContext.ts
  packages/desktop/lib/routers/helpers/index.ts
  packages/desktop/lib/routers/utils/getAppRouter.ts
  packages/desktop/lib/routers/utils/index.ts
  packages/desktop/views/login/views/SelectProfileView.svelte
  packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingFlow.ts
  packages/shared/lib/contexts/settings/actions/deleteProfile.ts
  packages/shared/lib/core/router/enums/router-manager-extension-name.enum.ts
  packages/shared/lib/core/router/interfaces/router-manager.interface.ts
Labels: type:refactor, stardust

#5210 fix: remove persistence of app window position
  packages/desktop/electron/main.js
Labels: type:fix, stardust

#5182 fix: align action menus
  packages/shared/components/atoms/buttons/AccountActionsButton.svelte
  packages/shared/components/atoms/buttons/AssetActionsButton.svelte
  packages/shared/components/atoms/buttons/NodeActionsButton.svelte
  packages/shared/components/atoms/iconButtons/MeatballMenuButton.svelte
  packages/shared/components/modals/AccountActionsMenu.svelte
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
Labels: type:fix, type:ui, stardust

#5212 enhancement: show key and value in selector
  packages/shared/components/Text.svelte
  packages/shared/components/inputs/ClosableInput.svelte
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/inputs/InputContainer.svelte
  packages/shared/components/inputs/NumberInput.svelte
  packages/shared/components/inputs/TextInput.svelte
  packages/shared/components/molecules/SelectorInput.svelte
Labels: type:enhancement, stardust

#5205 enhancement: add icon to nft selector
  packages/shared/components/inputs/NftInput.svelte
  packages/shared/components/molecules/NftMediaContainer.svelte
  packages/shared/components/molecules/SelectorInput.svelte
Labels: type:enhancement, context:wallet, type:ui, stardust

#5211 enhancement: add account colour to recipient input
  packages/shared/components/atoms/ColoredCircle.svelte
  packages/shared/components/atoms/index.js
  packages/shared/components/atoms/labels/AccountLabel.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/interfaces/option.interface.ts
  packages/shared/components/molecules/SelectorInput.svelte
  packages/shared/lib/core/account/utils/getAccountColorById.ts
  packages/shared/lib/core/account/utils/index.ts
Labels: type:enhancement, stardust

#5214 fix: subject not shown on activity details
  packages/shared/components/popups/ActivityDetailsPopup.svelte
Labels: type:fix, context:wallet, stardust

#5183 feat: tabbed nft activity details
  packages/shared/components/molecules/ActivityInformation.svelte
  packages/shared/components/molecules/NftActivityDetails.svelte
  packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte
  packages/shared/components/molecules/activity-info/NftActivityInformation.svelte
  packages/shared/components/molecules/activity-info/index.js
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/MintNftConfirmationPopup.svelte
  packages/shared/components/popups/send/SendConfirmationPopup.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, stardust

#5231 fix: fixes for minting NFT related issues
  packages/shared/components/popups/MintNftConfirmationPopup.svelte
  packages/shared/components/popups/MintNftFormPopup.svelte
  packages/shared/lib/core/nfts/constants/current-irc27-version.constant.ts
  packages/shared/lib/core/nfts/constants/index.ts
  packages/shared/lib/core/utils/validation.ts
  packages/shared/lib/core/wallet/actions/mintNft.ts
Labels: type:fix, stardust

#5217 feat: initial output consolidation feature
  packages/shared/components/popups/ConfirmationPopup.svelte
  packages/shared/components/popups/StorageDepositBreakdownPopup.svelte
  packages/shared/lib/core/error/constants/wallet-rs-error-parameters.constant.ts
  packages/shared/lib/core/error/handlers/handleError.ts
  packages/shared/lib/core/error/handlers/walletRs/handleWalletRsError.ts
  packages/shared/lib/core/error/handlers/walletRs/subhandlers/handleNoOutputsToConsolidateError.ts
  packages/shared/lib/core/error/handlers/walletRs/subhandlers/index.ts
  packages/shared/lib/core/wallet/actions/consolidateOutputs.ts
  packages/shared/locales/en.json
Labels: type:feature, context:wallet, stardust

#5224 enhancement: add correct calculation for SDRUC on storage deposit breakdown
  packages/shared/components/atoms/BalanceSummarySection.svelte
  packages/shared/components/popups/StorageDepositBreakdownPopup.svelte
  packages/shared/lib/contexts/onboarding/actions/cleanupOnboardingProfileManager.ts
  packages/shared/lib/core/nfts/utils/buildNftFromNftOutput.ts
Labels: type:enhancement, stardust

#5228 fix: remove collection id form NFT minting
  packages/shared/components/popups/MintNftConfirmationPopup.svelte
  packages/shared/lib/core/nfts/interfaces/irc27-metadata.interface.ts
  packages/shared/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/lib/core/wallet/stores/mint-nft-details.store.ts
Labels: type:fix, stardust

#5239 feat-mobile: setup activity flow
  packages/mobile/components/ActivityTile.svelte
  packages/mobile/components/AsyncActivityTileFooter.svelte
  packages/mobile/components/index.js
  packages/mobile/features/features.ts
  packages/mobile/lib/routers/actions/initialiseRouters.ts
  packages/mobile/lib/routers/actions/resetRouters.ts
  packages/mobile/lib/routers/enums/activity-route.enum.ts
  packages/mobile/lib/routers/enums/dashboard-route.enum.ts
  packages/mobile/lib/routers/enums/index.ts
  packages/mobile/lib/routers/subrouters/activity-router.ts
  packages/mobile/lib/routers/subrouters/index.ts
  packages/mobile/lib/routers/utils/getSubroutersForAppContext.ts
  packages/mobile/lib/wallet/index.ts
  packages/mobile/lib/wallet/stores/index.ts
  packages/mobile/lib/wallet/stores/selected-activity.store.ts
  packages/mobile/views/dashboard/DashboardRouter.svelte
  packages/mobile/views/dashboard/drawers/activity/ActivityDrawer.svelte
  packages/mobile/views/dashboard/drawers/activity/ActivityRouter.svelte
  packages/mobile/views/dashboard/drawers/activity/index.js
  packages/mobile/views/dashboard/drawers/index.js
Labels: platform:mobile, context:wallet, package:mobile, stardust

#5237 enhancement: nft metadata display
  packages/shared/components/molecules/ActivityInformation.svelte
  packages/shared/components/molecules/NftActivityDetails.svelte
  packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte
  packages/shared/components/molecules/activity-info/NftActivityInformation.svelte
  packages/shared/components/molecules/activity-info/NftMetadataInformation.svelte
  packages/shared/components/molecules/activity-info/index.js
  packages/shared/components/popups/MintNftConfirmationPopup.svelte
  packages/shared/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/locales/en.json
Labels: type:ui, stardust

#5233 enhancement: foundry tab
  packages/shared/components/inputs/AliasInput.svelte
  packages/shared/components/molecules/ActivityInformation.svelte
  packages/shared/components/molecules/FoundryActivityDetails.svelte
  packages/shared/components/molecules/activity-info/FoundryActivityInformation.svelte
  packages/shared/components/molecules/activity-info/TokenActivityInformation.svelte
  packages/shared/components/molecules/activity-info/index.js
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/MintNativeTokenConfirmationPopup.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/MintNftFormPopup.svelte
  packages/shared/lib/core/wallet/helpers/buildPersistedAssetFromIrc30Metadata.ts
  packages/shared/lib/core/wallet/interfaces/token-metadata.interface.ts
  packages/shared/lib/core/wallet/types/activities/foundry-activity.type.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateFoundryActivity.ts
  packages/shared/locales/af.json
  packages/shared/locales/ar.json
  packages/shared/locales/bg.json
  packages/shared/locales/ca.json
  packages/shared/locales/cs.json
  packages/shared/locales/da.json
  packages/shared/locales/de.json
  packages/shared/locales/el.json
  packages/shared/locales/en.json
  packages/shared/locales/eo.json
  packages/shared/locales/es-ES.json
  packages/shared/locales/es-LA.json
  packages/shared/locales/et.json
  packages/shared/locales/fa.json
  packages/shared/locales/fi.json
  packages/shared/locales/fr.json
  packages/shared/locales/he.json
  packages/shared/locales/hi.json
  packages/shared/locales/hr.json
  packages/shared/locales/hu.json
  packages/shared/locales/id.json
  packages/shared/locales/it.json
  packages/shared/locales/ja.json
  packages/shared/locales/ko.json
  packages/shared/locales/ku.json
  packages/shared/locales/lv.json
  packages/shared/locales/mk.json
  packages/shared/locales/nl.json
  packages/shared/locales/no.json
  packages/shared/locales/pl.json
  packages/shared/locales/pt-BR.json
  packages/shared/locales/pt-PT.json
  packages/shared/locales/ro.json
  packages/shared/locales/ru.json
  packages/shared/locales/si.json
  packages/shared/locales/sk.json
  packages/shared/locales/sl.json
  packages/shared/locales/sq.json
  packages/shared/locales/sr.json
  packages/shared/locales/sv.json
  packages/shared/locales/tr.json
  packages/shared/locales/uk.json
  packages/shared/locales/ur.json
  packages/shared/locales/vi.json
  packages/shared/locales/zh-CN.json
  packages/shared/locales/zh-TW.json
Labels: type:enhancement, context:wallet, stardust

#5252 fix: force refresh assets on first login
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
Labels: type:fix, context:wallet, stardust

#5246 feat-mobile: add amount to send flow and basic send functionality working
  packages/mobile/components/TokenUnitSwapper.svelte
  packages/mobile/components/index.js
  packages/mobile/features/features.ts
  packages/mobile/lib/routers/subrouters/send-router.ts
  packages/mobile/views/dashboard/drawers/send/SendDrawer.svelte
  packages/mobile/views/dashboard/drawers/send/SendRouter.svelte
  packages/mobile/views/dashboard/drawers/send/views/AmountView.svelte
  packages/mobile/views/dashboard/drawers/send/views/ConfirmView.svelte
  packages/mobile/views/dashboard/drawers/send/views/RecipientView.svelte
  packages/mobile/views/dashboard/drawers/send/views/TokenView.svelte
  packages/mobile/views/dashboard/drawers/send/views/index.js
Labels: platform:mobile, package:mobile, stardust

#5280 fix: fix shown rejected activities
  packages/shared/lib/core/wallet/utils/generateActivity/generateAliasActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateFoundryActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateNftActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateTransactionActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/getAsyncDataFromOutput.ts
Labels: type:fix, context:wallet, stardust

#5247 feat-mobile: add basic activity details and actions
  packages/mobile/components/ActivityList.svelte
  packages/mobile/components/ActivityTile.svelte
  packages/mobile/components/Confirmation.svelte
  packages/mobile/components/index.js
  packages/mobile/features/features.ts
  packages/mobile/lib/contexts/dashboard/enums/activity-action.enum.ts
  packages/mobile/lib/contexts/dashboard/enums/index.ts
  packages/mobile/lib/routers/index.ts
  packages/mobile/lib/routers/interfaces/index.ts
  packages/mobile/lib/routers/interfaces/router-event.interface.ts
  packages/mobile/lib/routers/subrouters/activity-router.ts
  packages/mobile/views/dashboard/DashboardRouter.svelte
  packages/mobile/views/dashboard/drawers/activity/ActivityDrawer.svelte
  packages/mobile/views/dashboard/drawers/activity/ActivityRouter.svelte
  packages/mobile/views/dashboard/drawers/activity/index.js
  packages/mobile/views/dashboard/drawers/activity/views/ActivityDetails.svelte
  packages/mobile/views/dashboard/drawers/activity/views/index.js
  packages/mobile/views/dashboard/tabs/ActivityTab.svelte
Labels: type:feature, platform:mobile, context:wallet, package:mobile, stardust

#5278 feat-mobile: fix drawer close reset current router delay
  packages/mobile/components/Drawer.svelte
  packages/mobile/lib/contexts/dashboard/constants/drawer-component.constants.ts
  packages/mobile/lib/contexts/dashboard/constants/index.ts
  packages/mobile/lib/contexts/dashboard/stores/index.ts
  packages/mobile/lib/contexts/dashboard/stores/selected-activity.store.ts
  packages/mobile/lib/routers/subrouters/activity-router.ts
  packages/mobile/lib/wallet/index.ts
  packages/mobile/lib/wallet/stores/index.ts
  packages/mobile/views/dashboard/DashboardRouter.svelte
Labels: type:fix, platform:mobile, package:mobile, stardust

#5235 refactor: update basic transaction structure
  docs/specifications/activities/class-diagram.md
  packages/mobile/components/ActivityTile.svelte
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/molecules/ActivityInformation.svelte
  packages/shared/components/molecules/BasicActivityDetails.svelte
  packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/send/SendConfirmationPopup.svelte
  packages/shared/components/popups/send/SendFormPopup.svelte
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendFormOperation.ts
  packages/shared/lib/contexts/onboarding/actions/claimShimmerRewards.ts
  packages/shared/lib/core/layer-2/actions/getLayer2MetadataForTransfer.ts
  packages/shared/lib/core/ledger/helpers/deconstructLedgerVerificationProps.ts
  packages/shared/lib/core/profile-manager/actions/events-handlers/handleNewOutputEvent.ts
  packages/shared/lib/core/wallet/actions/activities/hideActivitiesForHiddenAssets.ts
  packages/shared/lib/core/wallet/actions/activities/loadAssetsForAllAccounts.ts
  packages/shared/lib/core/wallet/actions/activities/updateClaimingTransactionInclusion.ts
  packages/shared/lib/core/wallet/enums/activity-type.enum.ts
  packages/shared/lib/core/wallet/stores/new-transaction-details.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
  packages/shared/lib/core/wallet/types/activities/transaction-activity.type.ts
  packages/shared/lib/core/wallet/types/new-transaction-details.type.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateTransactionActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/updateActivityFromPartialActivity.ts
  packages/shared/lib/core/wallet/utils/getActivityType.ts
  packages/shared/lib/core/wallet/utils/isVisibleActivity.ts
  packages/shared/lib/core/wallet/utils/outputs/getFormattedAmountFromActivity.ts
  packages/shared/locales/en.json
Labels: type:chore, context:wallet, stardust

#5284 feat-mobile: add review screen to send flow
  packages/mobile/lib/routers/enums/send-route.enum.ts
  packages/mobile/lib/routers/interfaces/activity-router-event.interface.ts
  packages/mobile/lib/routers/interfaces/index.ts
  packages/mobile/lib/routers/interfaces/send-router-event.interface.ts
  packages/mobile/lib/routers/subrouters/activity-router.ts
  packages/mobile/lib/routers/subrouters/send-router.ts
  packages/mobile/lib/routers/utils/index.ts
  packages/mobile/lib/routers/utils/resetRouterWithDrawerDelay.ts
  packages/mobile/views/dashboard/DashboardRouter.svelte
  packages/mobile/views/dashboard/drawers/send/SendDrawer.svelte
  packages/mobile/views/dashboard/drawers/send/SendRouter.svelte
  packages/mobile/views/dashboard/drawers/send/views/AmountView.svelte
  packages/mobile/views/dashboard/drawers/send/views/ConfirmView.svelte
  packages/mobile/views/dashboard/drawers/send/views/ReviewView.svelte
  packages/mobile/views/dashboard/drawers/send/views/index.js
Labels: type:feature, platform:mobile, package:mobile, stardust

#5288 feat-mobile: add activity details for foundries, aliases and NFTs
  packages/mobile/views/dashboard/drawers/activity/views/ActivityDetails.svelte
Labels: type:feature, platform:mobile, package:mobile, stardust

#5285 feat-mobile: add references view to send flow
  packages/mobile/lib/routers/enums/send-route.enum.ts
  packages/mobile/lib/routers/subrouters/send-router.ts
  packages/mobile/views/dashboard/drawers/send/SendDrawer.svelte
  packages/mobile/views/dashboard/drawers/send/SendRouter.svelte
  packages/mobile/views/dashboard/drawers/send/views/AmountView.svelte
  packages/mobile/views/dashboard/drawers/send/views/ReferenceView.svelte
  packages/mobile/views/dashboard/drawers/send/views/ReviewView.svelte
  packages/mobile/views/dashboard/drawers/send/views/TokenView.svelte
  packages/mobile/views/dashboard/drawers/send/views/index.js
  packages/shared/locales/en.json
Labels: platform:mobile, package:mobile, stardust

#5281 fix: address validation error behavior
  packages/mobile/components/inputs/RecipientInput.svelte
  packages/shared/components/inputs/AliasInput.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/popups/MintNftFormPopup.svelte
  packages/shared/lib/core/layer-2/errors/index.ts
  packages/shared/lib/core/layer-2/errors/layer1-recipient.error.ts
  packages/shared/lib/core/layer-2/utils/index.ts
  packages/shared/lib/core/layer-2/utils/validateEthereumAddress.ts
  packages/shared/lib/core/network/utils/isShimmerNetworkProtocol.ts
  packages/shared/lib/core/nfts/stores/all-account-nfts.store.ts
  packages/shared/lib/core/nfts/stores/selected-account-nfts.store.ts
  packages/shared/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/lib/core/utils/convert.ts
  packages/shared/lib/core/utils/crypto.ts
  packages/shared/lib/core/utils/crypto/classes/bech32-helper.class.ts
  packages/shared/lib/core/utils/crypto/classes/index.ts
  packages/shared/lib/core/utils/crypto/constants/index.ts
  packages/shared/lib/core/utils/crypto/constants/keccak-hash-size.constant.ts
  packages/shared/lib/core/utils/crypto/index.ts
  packages/shared/lib/core/utils/crypto/utils/index.ts
  packages/shared/lib/core/utils/crypto/utils/validateBech32Address.ts
  packages/shared/lib/core/utils/crypto/utils/validateEthereumAddress.ts
  packages/shared/lib/core/utils/index.ts
  packages/shared/lib/core/utils/tests/crypto.test.ts
  packages/shared/lib/core/utils/tests/utils.test.ts
  packages/shared/lib/core/wallet/actions/activities/generateAndStoreActivitiesForAccount.ts
  packages/shared/lib/core/wallet/actions/activities/preprocessOutputsForAccount.ts
  packages/shared/lib/core/wallet/actions/generateAndStoreActivitiesForAllAccounts.ts
  packages/shared/lib/core/wallet/utils/convertBech32ToHexAddress.ts
  packages/shared/lib/core/wallet/utils/convertHexAddressToBech32.ts
  packages/shared/lib/core/wallet/utils/getBech32AddressFromAddressTypes.ts
  packages/shared/lib/core/wallet/utils/outputs/getRecipientAddressFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/preprocessGroupedOutputs.ts
  packages/shared/locales/en.json
Labels: type:refactor, stardust

#5293 fix: fix send on token-info-popup
  packages/shared/components/popups/TokenInformationPopup.svelte
Labels: type:fix, context:wallet, stardust

#5294 fix: NetworkInput initial value given by network address
  packages/shared/components/inputs/NetworkInput.svelte
  packages/shared/lib/core/utils/crypto/utils/validateEthereumAddress.ts
Labels: type:fix, context:wallet, stardust

#5244 fix: various NFT fixes
  packages/shared/components/inputs/Dropdown.svelte
  packages/shared/components/popups/MintNftFormPopup.svelte
  packages/shared/components/popups/send/SendFormPopup.svelte
  packages/shared/lib/core/profile-manager/actions/events-handlers/handleTransactionInclusionEvent.ts
  packages/shared/lib/core/wallet/actions/activities/setAsyncStatusOfAccountActivities.ts
  packages/shared/lib/core/wallet/actions/mintNft.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/getAsyncDataFromOutput.ts
  packages/shared/lib/core/wallet/utils/transactions/outputContainsValue.ts
Labels: type:fix, stardust

#5296 enhancement: improve gallery view UI
  packages/desktop/components/AccountActivity.svelte
  packages/desktop/views/dashboard/collectibles/Collectibles.svelte
  packages/desktop/views/dashboard/collectibles/views/GalleryView.svelte
  packages/shared/components/inputs/TogglableButton.svelte
  packages/shared/components/molecules/NftGalleryItem.svelte
  packages/shared/components/molecules/NftMediaContainer.svelte
  packages/shared/locales/en.json
Labels: context:wallet, type:ui, stardust

#5297 enhancement: add content if no nfts are owned
  packages/desktop/views/dashboard/collectibles/Collectibles.svelte
  packages/desktop/views/dashboard/collectibles/views/DetailsView.svelte
  packages/desktop/views/dashboard/collectibles/views/GalleryView.svelte
  packages/shared/assets/illustrations/wallet/empty-collectibles.svg
  packages/shared/components/Illustration.svelte
  packages/shared/components/atoms/buttons/ReceiveButton.svelte
  packages/shared/components/popups/ReceiveAddressPopup.svelte
  packages/shared/locales/en.json
Labels: context:wallet, type:ui, stardust

#5292 feat: input asset amount for burning
  packages/shared/components/inputs/AssetAmountSliderInput.svelte
  packages/shared/components/inputs/SliderInput.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/components/popups/BurnNativeTokensPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/core/wallet/actions/burnAsset.ts
  packages/shared/lib/core/wallet/utils/convertToRawAmount.ts
  packages/shared/locales/en.json
Labels: type:fix, context:wallet, stardust

#5298 feat: add searchbar to collectible tabs
  packages/desktop/views/dashboard/collectibles/views/GalleryView.svelte
  packages/shared/assets/illustrations/wallet/empty-collectibles-darkmode.svg
  packages/shared/components/Illustration.svelte
  packages/shared/lib/core/nfts/stores/selected-account-nfts.store.ts
  packages/shared/locales/en.json
Labels: type:feature, context:wallet, stardust

#5301 enhancement: improve nft details view
  packages/desktop/views/dashboard/collectibles/views/DetailsView.svelte
  packages/shared/components/molecules/NftMediaContainer.svelte
Labels: context:wallet, type:ui, stardust

#5277 feat: add validation l1 -> l2
  packages/shared/components/inputs/NetworkInput.svelte
  packages/shared/components/popups/send/SendFormPopup.svelte
Labels: status:do-not-merge, type:feature, context:wallet, stardust

#5295 feat: parsed smart contract metadata UI
  packages/shared/components/atoms/tiles/tileContents/TransactionActivityTileContent.svelte
  packages/shared/components/enums/index.ts
  packages/shared/components/enums/tab.enum.ts
  packages/shared/components/molecules/ActivityInformation.svelte
  packages/shared/components/molecules/BasicActivityDetails.svelte
  packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte
  packages/shared/components/molecules/activity-info/SmartContractActivityInformation.svelte
  packages/shared/components/molecules/activity-info/index.js
  packages/shared/components/popups/send/SendConfirmationPopup.svelte
  packages/shared/lib/core/layer-2/actions/getLayer2MetadataForTransfer.ts
  packages/shared/lib/core/layer-2/index.ts
  packages/shared/lib/core/layer-2/interfaces/layer2-parameters.interface.ts
  packages/shared/lib/core/layer-2/types/index.ts
  packages/shared/lib/core/layer-2/types/layer2-metadata.interface.ts
  packages/shared/lib/core/layer-2/utils/getDestinationNetworkFromAddress.ts
  packages/shared/lib/core/layer-2/utils/index.ts
  packages/shared/lib/core/layer-2/utils/parseLayer2Metadata.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/enums/token-standard.enum.ts
  packages/shared/lib/core/wallet/interfaces/base-token-metadata.interface.ts
  packages/shared/lib/core/wallet/types/activities/base-activity.type.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateTransactionActivity.ts
  packages/shared/locales/en.json
Labels: type:feature, context:wallet, stardust

#5225 feat: update wallet.rs dependency
  packages/shared/package.json
  yarn.lock
Labels: package:wallet.rs, stardust
