Repository iotaledger/firefly, pull requests merged in 2022-07, with the labels that each got.

#3756 style: unify mobile horizontal paddings to `20px`
  packages/shared/components/AccountNavigation.svelte
  packages/shared/components/ActivityDetail.svelte
  packages/shared/components/MainMenu.svelte
  packages/shared/components/inputs/Checkbox.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/routes/dashboard/settings/Settings.svelte
  packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
  packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
  packages/shared/routes/setup/Welcome.svelte
Labels: type:enhancement, platform:mobile, type:ui

#3757 feat: initialize firefly theme to `system` by default on every platform
  packages/shared/lib/appSettings.ts
Labels: platform:mobile, platform:desktop

#3758 fix: send drawer
  packages/shared/assets/illustrations/send-mobile-darkmode.svg
  packages/shared/assets/illustrations/send-mobile.svg
  packages/shared/components/Illustration.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:fix, platform:mobile, type:ui

#3718 ui: create OnboardingButton component for Onboarding views
  packages/shared/components/atoms/buttons/OnboardingButton.svelte
  packages/shared/components/atoms/buttons/index.js
  packages/shared/routes/onboarding/CreateView.svelte
  packages/shared/routes/onboarding/OnboardingNetworkView.svelte
  packages/shared/routes/onboarding/OnboardingProtocolView.svelte
  packages/shared/routes/onboarding/SetupView.svelte
  packages/shared/routes/onboarding/import/views/ImportView.svelte
  packages/shared/routes/onboarding/import/views/LedgerView.svelte
  packages/shared/tailwind.config.js
Labels: context:onboarding, type:ui, stardust

#3741 fix: initialize logger
  packages/desktop/electron/preload.js
Labels: type:chore, type:fix, stardust

#3755 ui: update darkmode styles in wallet tab
  packages/shared/components/atoms/buttons/AddInputButton.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/inputs/ClosableInputContainer.svelte
  packages/shared/components/inputs/Dropdown2.svelte
  packages/shared/components/molecules/ExpirationTimePicker.svelte
Labels: context:wallet, type:ui, stardust

#3737 fix: top account navigation horizontal alignment
  packages/shared/components/AccountNavigation.svelte
Labels: type:fix, platform:mobile, type:ui

#3759 chore: Snyk CI changes
  .github/workflows/ci.snyk.yml
Labels: type:chore

#3772 chore: add path alias for features
  packages/desktop/tsconfig.json
  packages/mobile/tsconfig.json
  packages/shared/tsconfig.json
Labels: type:chore, stardust

#3769 fix: update wallet.rs
  packages/shared/lib/contexts/onboarding/actions/initProfileManagerFromNewProfile.ts
  packages/shared/lib/contexts/onboarding/actions/setNewProfileClientOptions.ts
  packages/shared/lib/core/account/actions/createNewAccount.ts
  packages/shared/lib/core/profile-manager/actions/initialiseProfileManager.ts
  packages/shared/package.json
  packages/shared/routes/login/views/EnterPinView.svelte
  yarn.lock
Labels: package:wallet.rs, stardust

#3765 chore: center wallet action headers and adjust paddings
  packages/shared/components/drawerContent/AccountSwitcher.svelte
  packages/shared/components/drawerContent/AddressHistory.svelte
  packages/shared/components/drawerContent/ExportTransactionHistory.svelte
  packages/shared/components/drawerContent/HideAccount.svelte
  packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte
Labels: type:chore, platform:mobile

#3736 feat: disable text selection in displayed mnemonic
  packages/shared/components/RecoveryPhrase.svelte
Labels: type:feature, platform:mobile

#3776 chore: hide settings for mobile
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
Labels: type:chore, platform:mobile, type:ui

#3771 fix: send confirmation popup close
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/stronghold.ts
Labels: type:fix, package:shared, stardust

#3785 chore: store uncompressed libs on apk
  packages/mobile/android/app/build.gradle
Labels: type:chore, platform:mobile

#3781 fix: bindings capacitor login crash
  packages/backend/bindings/capacitor/android/src/main/java/org/iota/fireflyactorsystem/WalletPlugin.java
  packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift
Labels: type:fix, platform:mobile

#3784 enhancement: UX of adding an account
  packages/shared/components/popups/CreateAccountPopup.svelte
  packages/shared/lib/popup.ts
Labels: type:enhancement, package:shared, stardust

#3809 chore: copy ci.snyk.yml onto stardust-develop
  .github/workflows/ci.snyk.yml
Labels: type:chore, scope:ci

#3766 refactor: deeplinks for stardust send flow
  packages/desktop/electron-builder-config.js
  packages/desktop/electron/main.js
  packages/desktop/package.json
  packages/desktop/webpack.config.js
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/popups/HideAccount.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/lib/address.ts
  packages/shared/lib/app.ts
  packages/shared/lib/common/deep-links/actions/index.ts
  packages/shared/lib/common/deep-links/actions/resetDeepLink.ts
  packages/shared/lib/common/deep-links/deep-link-handler.ts
  packages/shared/lib/common/deep-links/enums/index.ts
  packages/shared/lib/common/deep-links/enums/send-operation-parameter.enum.ts
  packages/shared/lib/common/deep-links/enums/wallet-operation.enum.ts
  packages/shared/lib/common/deep-links/handlers/handleDeepLink.ts
  packages/shared/lib/common/deep-links/handlers/index.ts
  packages/shared/lib/common/deep-links/handlers/wallet/handleDeepLinkWalletContext.ts
  packages/shared/lib/common/deep-links/handlers/wallet/index.ts
  packages/shared/lib/common/deep-links/handlers/wallet/operations/handleDeepLinkSendOperation.ts
  packages/shared/lib/common/deep-links/handlers/wallet/operations/index.ts
  packages/shared/lib/common/deep-links/index.ts
  packages/shared/lib/common/deep-links/wallet-context-handler.ts
  packages/shared/lib/core/account/actions/setNextSelectedAccount.ts
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/lib/core/router/helper.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/send-form-parameters.interface.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/stores/send-form-parameters.store.ts
  packages/shared/lib/typings/sendParams.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/advanced/DeepLinks.svelte
  packages/shared/routes/dashboard/settings/views/advanced/HiddenAccounts.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
  yarn.lock
Labels: type:refactor, context:wallet, stardust

#3817 chore: disable accessibility text size changes
  packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/WebViewSettingsPlugin.java
Labels: type:chore, platform:mobile

#3813 chore: disable csv export of transaction history
  packages/shared/components/drawerContent/AccountSwitcher.svelte
Labels: type:chore, platform:mobile

#3814 chore: add title to transaction details
  packages/shared/components/ActivityDetail.svelte
  packages/shared/locales/de.json
  packages/shared/locales/en.json
Labels: type:chore, platform:mobile

#3815 chore: remove iota links from settings
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
Labels: type:chore, platform:mobile

#3816 style: change address input style to display the entire address
  packages/shared/components/inputs/Address.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:chore, platform:mobile

#3824 chore: change app icon for stardust
  packages/desktop/public/assets/icons/alpha/icon1024x1024.png
  packages/desktop/public/assets/icons/beta/icon1024x1024.png
  packages/desktop/public/assets/icons/prod/icon1024x1024.png
Labels: type:chore, stardust

#3819 fix: drawer close animation
  packages/shared/components/Drawer.svelte
Labels: type:fix, platform:mobile

#3822 fix: custom date picker selecting wrong date
  packages/shared/components/inputs/DateTimePicker.svelte
  packages/shared/components/inputs/ExpirationDateTimePicker.svelte
Labels: type:fix, package:shared, stardust

#3763 fix: settings ios scroll padding
  packages/shared/components/AccountNavigation.svelte
  packages/shared/components/MainMenu.svelte
  packages/shared/components/SettingsMenu.svelte
  packages/shared/routes/dashboard/settings/Settings.svelte
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
  packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
Labels: type:fix, platform:mobile

#3827 chore: add touch padding to QR code button
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:chore, platform:mobile

#3833 fix: send screen scroll
  packages/shared/components/Illustration.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:fix, platform:mobile

#3835 chore: pair CSP as desktop for beta
  packages/mobile/public/index.html
Labels: type:chore, platform:mobile

#3830 chore: update latest walletrs package
  package.json
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
  packages/shared/components/organisms/AccountSummary.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/components/popups/StorageDepositBreakdownPopup.svelte
  packages/shared/lib/core/account/actions/buildAccountState.ts
  packages/shared/lib/core/account/api/claimOutputs.ts
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/core/account/utils/sumBalanceForAccounts.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivitiesFromTransactions.ts
  packages/shared/lib/core/wallet/actions/sendOutput.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/utils/send/validateSendConfirmation.ts
  packages/shared/lib/participation/participation.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/lib/tests/__mocks__/accountBalance.mock.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: type:chore, stardust

#3836 chore: adjust qr code scanner style to figma design
  packages/mobile/App.svelte
  packages/mobile/public/index.html
  packages/shared/components/QRScanner.svelte
  packages/shared/locales/en.json
Labels: type:chore, platform:mobile, type:ui

#3839 fix: action sheet crash
  packages/shared/components/drawerContent/AccountSwitcher.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:fix, platform:mobile

#3829 feat: replace voting asset with generic iota governance
  packages/shared/assets/illustrations/governance/iota-governance.png
  packages/shared/assets/illustrations/governance/treasury.png
  packages/shared/components/Illustration.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
Labels: context:voting

#3831 Feat: adapt governance to new texts
  packages/desktop/electron/main.js
  packages/shared/lib/helpers.ts
  packages/shared/routes/dashboard/governance/views/GovernanceEventInfo.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceEvents.svelte
Labels: context:voting

#3844 fix: add spinner profile deletion
  packages/shared/components/popups/DeleteProfile.svelte
Labels: type:fix, package:shared, stardust

#3811 chore: accessible onboarding views
  packages/shared/components/Button.svelte
  packages/shared/components/OnboardingLayout.svelte
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/inputs/PinInput.svelte
  packages/shared/components/organisms/NodeConfigurationForm.svelte
  packages/shared/components/popups/AddNodePopup.svelte
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/lib/contexts/onboarding/actions/backupInitialStronghold.ts
  packages/shared/lib/contexts/onboarding/actions/clearStrongholdPasswordForOnboarding.ts
  packages/shared/lib/contexts/onboarding/actions/index.ts
  packages/shared/lib/core/error/classes/index.ts
  packages/shared/lib/core/error/classes/stronghold/index.ts
  packages/shared/lib/core/error/classes/stronghold/invalid-backup-destination-error.class.ts
  packages/shared/locales/en.json
  packages/shared/routes/onboarding/views/CongratulationsView.svelte
  packages/shared/routes/onboarding/views/network-setup/views/OnboardingCustomNetworkView.svelte
  packages/shared/routes/onboarding/views/password-setup/views/SetPasswordView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/BackupToFileView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/RecoveryPhraseView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/VerifyRecoveryPhraseView.svelte
  packages/shared/routes/onboarding/views/profile-recovery/views/FileImportView.svelte
  packages/shared/routes/onboarding/views/profile-recovery/views/TextImportView.svelte
  packages/shared/routes/onboarding/views/protection/views/SetupPinProtectionView.svelte
Labels: type:enhancement, type:chore, type:fix, package:shared, context:onboarding, stardust

#3858 update: update wallet.rs version alpha 5
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
  packages/shared/package.json
Labels: type:fix, context:wallet, stardust

#3515 ui: adjust animations
  packages/shared/assets/animations/import-from-file-success-desktop-darkmode.json
  packages/shared/assets/animations/import-from-file-success-desktop.json
  packages/shared/assets/animations/import-from-text-success-desktop-darkmode.json
  packages/shared/assets/animations/import-from-text-success-desktop.json
  packages/shared/assets/animations/onboarding-desktop-darkmode.json
  packages/shared/assets/animations/onboarding-desktop.json
  packages/shared/assets/animations/profile-desktop-darkmode.json
  packages/shared/assets/animations/profile-desktop.json
  packages/shared/assets/animations/setup-desktop-darkmode.json
  packages/shared/assets/animations/setup-desktop.json
  packages/shared/assets/animations/success-desktop-darkmode.json
  packages/shared/assets/animations/success-desktop.json
  packages/shared/components/Animation.svelte
  packages/shared/components/OnboardingLayout.svelte
  packages/shared/routes/onboarding/OnboardingCustomNetworkView.svelte
  packages/shared/routes/onboarding/OnboardingNetworkView.svelte
  packages/shared/routes/onboarding/OnboardingProtocolView.svelte
  packages/shared/routes/onboarding/ProfileView.svelte
  packages/shared/routes/onboarding/SetupView.svelte
  packages/shared/routes/onboarding/import/views/SuccessView.svelte
Labels: context:onboarding, type:ui, stardust

#3848 fix: activity status for incoming transactions
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/utils/isSubjectInternal.ts
  yarn.lock
Labels: type:fix, context:wallet, stardust

#3859 Revert "chore: update electron"
  packages/desktop/electron/main.js
  packages/desktop/package.json
  yarn.lock
Labels: type:hotfix, stardust

#3857 update: update balance if transaction expires
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/setAsyncStatusOfAccountActivities.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
Labels: type:enhancement, context:wallet, stardust

#3845 fix: adds stronghold check in claim transaction
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/stronghold.ts
Labels: type:fix, package:shared, stardust

#3850 chore: import Stronghold screen as figma
  packages/shared/locales/en.json
  packages/shared/routes/setup/import/views/FileImport.svelte
Labels: type:chore, platform:mobile

#3865 chore: bump alpha version to `0.1.3`
  packages/desktop/package.json
Labels: type:chore, stardust

#3863 fix: fix unknown sender address
  packages/shared/lib/core/account/actions/index.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
Labels: type:fix, context:wallet, stardust

#3866 fix: node config inputs
  packages/shared/components/organisms/NodeConfigurationForm.svelte
  packages/shared/routes/onboarding/OnboardingCustomNetworkView.svelte
Labels: type:fix, stardust

#3871 enhancement: determine if async activity is claimed
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/lib/core/profile-manager/api/events/spentOutput.ts
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/utils/convert.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/actions/linkActivityAndClaimingTransaction.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivies.ts
  packages/shared/lib/core/wallet/actions/setAsyncActivitiesToClaimed.ts
  packages/shared/lib/core/wallet/actions/setAsyncStatusOfAccountActivities.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
  packages/shared/lib/core/wallet/utils/outputs/index.ts
  packages/shared/lib/core/wallet/utils/outputs/outputIdFromTransactionData.ts
  packages/shared/lib/core/wallet/utils/transactions/getNonRemainderOutputFromTransaction.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromTransaction.ts
Labels: type:enhancement, type:fix, context:wallet, stardust

#3867 feat: IOTA profile manager
  packages/desktop/electron/preload.js
  packages/shared/features/onboardingFeatures.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupOnboarding.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupProtectionOnboarding.ts
  packages/shared/lib/contexts/onboarding/actions/createIotaProfileManager.ts
  packages/shared/lib/contexts/onboarding/actions/destroyIotaProfileManager.ts
  packages/shared/lib/contexts/onboarding/actions/index.ts
  packages/shared/lib/contexts/onboarding/stores/index.ts
  packages/shared/lib/contexts/onboarding/stores/iota-profile-manager.store.ts
  packages/shared/lib/core/profile-manager/actions/destroyProfileManager.ts
  packages/shared/lib/core/profile-manager/actions/initialiseProfileManager.ts
  packages/shared/lib/core/profile-manager/api/getAccount.ts
  packages/shared/lib/core/profile-manager/interfaces/api.interface.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/tests/__mocks__/api.ts
  packages/shared/lib/tests/__mocks__/crypto.mock.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/lib/tests/api.test.ts
  packages/shared/routes/onboarding/OnboardingRouter.svelte
  packages/shared/routes/onboarding/views/password-setup/views/SetPasswordView.svelte
  packages/shared/routes/onboarding/views/profile-recovery/views/BackupPasswordView.svelte
  packages/shared/routes/onboarding/views/profile-setup/views/SetupClaimedView.svelte
Labels: type:feature, stardust

#3890 chore: merge `release/desktop-2.0.0-beta-1.0.0` into `stardust-develop`
  packages/desktop/package.json
  packages/shared/features/onboardingFeatures.ts
  packages/shared/lib/core/network/constants/explorer-urls.constant.ts
  packages/shared/lib/core/network/constants/network.constant.ts
  packages/shared/lib/core/network/constants/official-node-urls.constant.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
  packages/shared/routes/onboarding/CreateView.svelte
Labels: type:chore, stardust

#3884 fix: adds the shimmer explorer url to the list of allowed urls
  packages/desktop/electron/main.js
Labels: type:fix, package:desktop, stardust

#3907 fix: set default expiration time if storage deposit is required
  packages/shared/components/molecules/ExpirationTimePicker.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
Labels: type:fix, context:wallet, stardust

#3923 docs: update spec and coding conventions
  docs/guides/coding-conventions/components.md
  docs/guides/coding-conventions/modules.md
  docs/retype.yml
  docs/specifications/account-activity.md
  docs/specifications/modules.md
Labels: type:documentation, stardust

#3924 chore: refactor `wordlists` module
  packages/desktop/tsconfig.json
  packages/mobile/tsconfig.json
  packages/shared/components/inputs/ImportTextfield.svelte
  packages/shared/jest.config.js
  packages/shared/lib/auxiliary/wordlists/english.ts
  packages/shared/lib/auxiliary/wordlists/index.ts
  packages/shared/routes/onboarding/backup/views/VerifyRecoveryPhraseView.svelte
  packages/shared/tsconfig.json
  packages/shared/tsconfig.test.json
  tsconfig.lint.json
Labels: type:refactor, stardust

#3860 fix: add capture & passive props to events
  packages/shared/components/Drawer.svelte
Labels: type:fix, platform:mobile

#3852 feat: implement android back action
  packages/mobile/App.svelte
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/package.json
  packages/shared/components/popups/ConfirmCloseApp.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/locales/en.json
  yarn.lock
Labels: type:feature, platform:mobile

#3869 fix: qr scanner corners
  packages/shared/components/QRScanner.svelte
Labels: type:fix, platform:mobile

#3896 chore: update wallet to alpha 7
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#3925 fix: capacitor iOS bindings listen & destoy functions
  packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift
Labels: type:fix, platform:mobile

#3812 feat: initial native token support for unknown token standard
  package.json
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/core/account/actions/setSelectedAccount.ts
  packages/shared/lib/core/account/actions/syncBalance.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/actions/refreshNativeTokens.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/interfaces/asset.interface.ts
  packages/shared/lib/core/wallet/interfaces/assets-state.interface.ts
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts
  packages/shared/lib/core/wallet/utils/generateRawAmount.ts
  packages/shared/lib/core/wallet/utils/getOutputOptions.ts
  packages/shared/lib/core/wallet/utils/outputs/getNativeTokenFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/index.ts
  packages/shared/lib/core/wallet/utils/parseRawAmount.ts
  packages/shared/lib/helpers.ts
  packages/shared/locales/en.json
Labels: type:feature, context:wallet, stardust

#3929 chore: close drawer upon send
  packages/shared/routes/dashboard/wallet/Wallet.svelte
Labels: type:chore, platform:mobile

#3932 chore: pair send & receive drawer design
  packages/shared/components/Drawer.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:chore, platform:mobile

#3922 chore: refactor `error` module
  packages/desktop/App.svelte
  packages/shared/components/popups/ErrorLog.svelte
  packages/shared/lib/common/deep-links/handlers/handleDeepLink.ts
  packages/shared/lib/common/deep-links/handlers/wallet/handleDeepLinkWalletContext.ts
  packages/shared/lib/common/deep-links/handlers/wallet/operations/handleDeepLinkSendOperation.ts
  packages/shared/lib/contexts/wallet/errors/index.ts
  packages/shared/lib/contexts/wallet/errors/insufficient-funds-for-storage-deposit-error.class.ts
  packages/shared/lib/contexts/wallet/errors/invalid-expiration-date-time-error.class.ts
  packages/shared/lib/contexts/wallet/index.ts
  packages/shared/lib/core/error/classes/base-error.class.ts
  packages/shared/lib/core/error/classes/index.ts
  packages/shared/lib/core/error/index.ts
  packages/shared/lib/core/error/interfaces/error-parameters.interface.ts
  packages/shared/lib/core/error/interfaces/error.interface.ts
  packages/shared/lib/core/error/interfaces/index.ts
  packages/shared/lib/core/error/stores/error-log.store.ts
  packages/shared/lib/core/error/stores/index.ts
  packages/shared/lib/core/profile-manager/errors/remove-account-with-balance.error.ts
  packages/shared/lib/core/profile-manager/errors/remove-not-last-account.error.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/utils/send/validateSendConfirmation.ts
  packages/shared/lib/errors.ts
  packages/shared/lib/stronghold.ts
  packages/shared/lib/tests/__mocks__/platform.ts
  packages/shared/lib/tests/errors.test.ts
  packages/shared/lib/typings/error.ts
  packages/shared/lib/typings/index.ts
  packages/shared/lib/typings/platform.ts
Labels: type:enhancement, type:refactor, stardust

#3952 docs: update error coding conventions
  docs/guides/coding-conventions/errors.md
Labels: type:documentation, stardust

#3926 Add feature flag for developer tools
  packages/desktop/electron/lib/menu.js
  packages/desktop/electron/main.js
  packages/shared/features/features.ts
Labels: type:enhancement, platform:desktop, context:settings

#3981 feat: add metadata to native tokens
  packages/shared/lib/core/wallet/actions/refreshNativeTokens.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/native-token-metadata.interface.ts
  packages/shared/lib/core/wallet/utils/getTokenMetadataFromFoundryOutput.ts
  packages/shared/lib/core/wallet/utils/index.ts
Labels: type:enhancement, type:feature, context:wallet, stardust

#3988 fix: SMR token amount formatting
  packages/shared/lib/participation/staking.ts
Labels: type:fix, context:staking

#3927 chore: center drawer popup titles
  packages/shared/components/popups/CreateAccount.svelte
  packages/shared/components/popups/Password.svelte
  packages/shared/components/popups/Transaction.svelte
Labels: type:chore, platform:mobile

#3933 fix: account switcher various
  packages/shared/components/drawerContent/AccountSwitcher.svelte
Labels: type:fix, platform:mobile

#3912 enhancement: add decimal validation to amount input
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/locales/en.json
Labels: type:fix, context:wallet, stardust

#3979 fix: handle error message wallet creation
  packages/shared/lib/core/account/actions/createNewAccount.ts
  packages/shared/lib/core/account/actions/tryCreateAdditionalAccount.ts
Labels: type:fix, stardust

#4001 Adds Crowdin
  .github/workflows/crowdin.yml
Labels: type:chore, stardust

#4005 enhancement: cache token metadata
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/organisms/AccountAssetsList.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/converter.ts
  packages/shared/lib/core/account/actions/setSelectedAccount.ts
  packages/shared/lib/core/account/actions/syncBalance.ts
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/wallet/actions/getAccountAssetsForSelectedAccount.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivities.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/actions/refreshNativeTokens.ts
  packages/shared/lib/core/wallet/actions/requestAndStorePersistedAsset.ts
  packages/shared/lib/core/wallet/actions/tryGetAndStoreAssetFromPersistedAssets.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/helpers/buildPersistedAssetFromIrc30Metadata.ts
  packages/shared/lib/core/wallet/helpers/index.ts
  packages/shared/lib/core/wallet/interfaces/account-assets.interface.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/interfaces/asset.interface.ts
  packages/shared/lib/core/wallet/interfaces/base-token-metadata.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/irc30-metadata.interface.ts
  packages/shared/lib/core/wallet/interfaces/persisted-asset.interface.ts
  packages/shared/lib/core/wallet/interfaces/persisted-assets.interface.ts
  packages/shared/lib/core/wallet/interfaces/token-metadata.interface.ts
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/stores/persisted-assets.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-assets.store.ts
  packages/shared/lib/core/wallet/utils/getAssetFromPersistedAssets.ts
  packages/shared/lib/core/wallet/utils/getIrc30MetadataFromFoundryOutput.ts
  packages/shared/lib/core/wallet/utils/getMetadataFromFoundryOutput.ts
  packages/shared/lib/core/wallet/utils/getOutputOptions.ts
  packages/shared/lib/core/wallet/utils/getTokenMetadataFromFoundryOutput.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/validateIrc30Metadata.ts
Labels: type:enhancement, context:wallet, stardust

#3885 fix: truncate long tx metadata
  packages/shared/components/atoms/boxes/KeyValueBox.svelte
Labels: type:fix, package:shared, stardust

#3984 fix: unit selection shows undefined
  packages/shared/components/inputs/Dropdown2.svelte
  packages/shared/components/inputs/UnitInput.svelte
Labels: type:enhancement, context:wallet, stardust

#4009 fix: revert to Cocoapods 1.11.2
  packages/mobile/ios/App/Podfile
  packages/mobile/ios/App/Podfile.lock
Labels: type:fix, platform:mobile

#3962 docs: update `README`s
  README.md
  packages/desktop/README.md
  packages/mobile/README.md
Labels: type:documentation

#3963 chore: refactor unit tests
  package.json
  packages/shared/jest.config.js
  packages/shared/lib/core/error/tests/errors.test.ts
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/core/profile-manager/tests/api.test.ts
  packages/shared/lib/core/utils/tests/time.test.ts
  packages/shared/lib/core/utils/tests/utils.test.ts
  packages/shared/lib/tests/__mocks__/account-balance.mock.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/lib/tests/__mocks__/api.mock.ts
  packages/shared/lib/tests/__mocks__/i18n.mock.ts
  packages/shared/lib/tests/__mocks__/match-media.mock.ts
  packages/shared/lib/tests/__mocks__/platform.mock.ts
  packages/shared/lib/tests/__mocks__/profile-manager.mock.ts
  packages/shared/lib/tests/currency.test.ts
  packages/shared/lib/tests/setup.ts
  packages/shared/tsconfig.test.json
Labels: type:chore, type:refactor, stardust

#3990 feat: native token information popup
  packages/shared/components/atoms/Icon.svelte
  packages/shared/components/atoms/MenuItem.svelte
  packages/shared/components/atoms/buttons/AssetActionsButton.svelte
  packages/shared/components/atoms/buttons/index.js
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/components/modals/index.js
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/molecules/VerificationBadge.svelte
  packages/shared/components/molecules/index.js
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
  packages/shared/lib/auxiliary/icon/constants/icon-svg.ts
  packages/shared/lib/auxiliary/icon/enums/icon.enum.ts
  packages/shared/lib/auxiliary/icon/interfaces/svg-path.interface.ts
  packages/shared/lib/auxiliary/icon/svgs/index.ts
  packages/shared/lib/auxiliary/icon/svgs/not-verified.svg.ts
  packages/shared/lib/auxiliary/icon/svgs/verified.svg.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/enums/index.ts
  packages/shared/lib/core/wallet/enums/verification-status.enum.ts
  packages/shared/lib/core/wallet/helpers/buildPersistedAssetFromIrc30Metadata.ts
  packages/shared/lib/core/wallet/interfaces/base-token-metadata.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/persisted-asset.interface.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/stores/persisted-assets.store.ts
  packages/shared/locales/en.json
  packages/shared/tailwind.config.js
Labels: type:feature, context:wallet, stardust

#3915 fix: show info for self transaction
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/utils/transactions/getNonRemainderOutputFromTransaction.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromTransaction.ts
Labels: type:enhancement, type:fix, context:wallet, stardust

#3958 fix: decimal amounts german
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/CreateAccountPopup.svelte
  packages/shared/components/popups/DeleteAccount.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/core/wallet/utils/formatTokenAmountBestMatch.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts
Labels: type:fix, context:wallet, stardust

#4018 update: walletrs alpha 10
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: context:wallet, package:wallet.rs, stardust

#4014 fix: adapt code to not show recovery phrase success on mobile
  packages/shared/routes/setup/backup/views/VerifyRecoveryPhrase.svelte
Labels: type:fix, platform:mobile, package:shared

#3991 feat: mint native tokens
  packages/shared/components/Sidebar.svelte
  packages/shared/components/atoms/buttons/OnboardingButton.svelte
  packages/shared/components/inputs/ClosableInput.svelte
  packages/shared/components/inputs/ClosableTextInput.svelte
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/features/features.ts
  packages/shared/lib/converter.ts
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/mintNativeToken.ts
  packages/shared/lib/core/wallet/actions/sendOutput.ts
  packages/shared/lib/core/wallet/helpers/buildPersistedAssetFromIrc30Metadata.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/developerTools/DeveloperTools.svelte
  packages/shared/routes/dashboard/index.js
  packages/shared/tailwind.config.js
Labels: type:feature, context:wallet, stardust

#3983 feature: implement back button routing
  packages/mobile/App.svelte
  packages/shared/components/AccountNavigation.svelte
  packages/shared/components/Drawer.svelte
  packages/shared/components/MainMenu.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/core/router/backbutton-history.ts
  packages/shared/lib/core/router/index.ts
  packages/shared/lib/core/router/router.ts
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/login/views/SelectProfile.svelte
  packages/shared/routes/setup/Welcome.svelte
Labels: type:feature, platform:mobile

#3853 chore: copy paste detection for import textfield
  packages/shared/components/inputs/ImportTextfield.svelte
Labels: type:chore, platform:mobile

#4024 enhancement: hide activity if token is not irc30
  packages/shared/components/atoms/Icon.svelte
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/lib/core/wallet/actions/hideActivitiesForHiddenAssets.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
Labels: type:enhancement, context:wallet, stardust

#4020 fix: Android exit app without crashing
  packages/mobile/App.svelte
  packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/WebViewSettingsPlugin.java
  packages/shared/components/Drawer.svelte
Labels: type:fix, platform:mobile

#3992 feat: token faucet button
  packages/desktop/public/index.html
  packages/shared/assets/animations/special-token.json
  packages/shared/components/Alert.svelte
  packages/shared/components/Animation.svelte
  packages/shared/components/TextHint.svelte
  packages/shared/components/ToastContainer.svelte
  packages/shared/components/atoms/buttons/FaucetRequestButton.svelte
  packages/shared/components/atoms/buttons/MintNativeTokenButton.svelte
  packages/shared/components/atoms/buttons/RefreshTokenMetadataButton.svelte
  packages/shared/components/atoms/buttons/index.js
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/index.js
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/ConfirmationPopup.svelte
  packages/shared/components/popups/FaucetRequestPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/contexts/developer/actions/index.ts
  packages/shared/lib/contexts/developer/actions/requestTokensFromFaucet.ts
  packages/shared/lib/contexts/developer/index.ts
  packages/shared/lib/core/network/constants/faucet-urls.constant.ts
  packages/shared/lib/core/network/constants/index.ts
  packages/shared/lib/core/wallet/actions/mintNativeToken.ts
  packages/shared/lib/core/wallet/actions/requestAndStorePersistedAsset.ts
  packages/shared/lib/core/wallet/constants/index.ts
  packages/shared/lib/core/wallet/constants/special-token-id.constant.ts
  packages/shared/lib/typings/notification.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/developerTools/DeveloperTools.svelte
Labels: type:feature, stardust, context:developer

#3994 fix: problems with account action titles for delete and hide an account
  packages/shared/components/drawerContent/DeleteAccount.svelte
  packages/shared/components/drawerContent/HideAccount.svelte
Labels: type:fix, platform:mobile

#4036 feat: generate custom asset logo when not available
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/lib/core/account/utils/getIconColorFromString.ts
  packages/shared/lib/core/account/utils/index.ts
  packages/shared/lib/core/wallet/constants/index.ts
  packages/shared/lib/core/wallet/constants/max-asset-displayed-initials.constant.ts
  packages/shared/lib/core/wallet/helpers/buildPersistedAssetFromIrc30Metadata.ts
  packages/shared/lib/core/wallet/utils/getAssetInitials.ts
  packages/shared/lib/core/wallet/utils/index.ts
Labels: type:feature, context:wallet, stardust

#4042 fix: send asset dropdown squished icon and truncate
  packages/shared/components/inputs/AssetDropdown.svelte
Labels: type:fix, type:ui, stardust

#4037 enhancement: add minting to activity list
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/enums/activity-type.enum.ts
  packages/shared/lib/core/wallet/utils/getActivityType.ts
  packages/shared/lib/core/wallet/utils/transactions/containsFoundryOutput.ts
  packages/shared/lib/core/wallet/utils/transactions/getRelevantOutputFromTransaction.ts
  packages/shared/lib/core/wallet/utils/transactions/index.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, stardust

#4043 ui: reduce padding for scrollbar
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/organisms/AccountActivity.svelte
Labels: context:wallet, type:ui, stardust

#4027 enhancement: add tooltip for glow units
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
Labels: type:enhancement

#4051 chore: update wallet to `2.0.2-alpha.11`
  packages/shared/components/popups/NodeInfoPopup.svelte
  packages/shared/features/onboardingFeatures.ts
  packages/shared/lib/core/network/stores/network-hrp.store.ts
  packages/shared/lib/core/network/stores/node-info.store.ts
  packages/shared/lib/tests/__mocks__/profile-manager.mock.ts
  packages/shared/locales/af.json
  packages/shared/locales/ar.json
  packages/shared/locales/bg.json
  packages/shared/locales/ca.json
  packages/shared/locales/cs.json
  packages/shared/locales/da.json
  packages/shared/locales/de.json
  packages/shared/locales/el.json
  packages/shared/locales/en.json
  packages/shared/locales/eo.json
  packages/shared/locales/es-ES.json
  packages/shared/locales/es-LA.json
  packages/shared/locales/et.json
  packages/shared/locales/fa.json
  packages/shared/locales/fi.json
  packages/shared/locales/fr.json
  packages/shared/locales/he.json
  packages/shared/locales/hi.json
  packages/shared/locales/hr.json
  packages/shared/locales/hu.json
  packages/shared/locales/id.json
  packages/shared/locales/it.json
  packages/shared/locales/ja.json
  packages/shared/locales/ko.json
  packages/shared/locales/ku.json
  packages/shared/locales/lv.json
  packages/shared/locales/mk.json
  packages/shared/locales/nl.json
  packages/shared/locales/no.json
  packages/shared/locales/pl.json
  packages/shared/locales/pt-BR.json
  packages/shared/locales/pt-PT.json
  packages/shared/locales/ro.json
  packages/shared/locales/ru.json
  packages/shared/locales/si.json
  packages/shared/locales/sk.json
  packages/shared/locales/sl.json
  packages/shared/locales/sq.json
  packages/shared/locales/sr.json
  packages/shared/locales/sv.json
  packages/shared/locales/tr.json
  packages/shared/locales/uk.json
  packages/shared/locales/ur.json
  packages/shared/locales/vi.json
  packages/shared/locales/zh-CN.json
  packages/shared/locales/zh-TW.json
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#4055 fix: validation of minting
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
Labels: type:fix, context:wallet, stardust

#4057 fix: verification badge on new assets only
  packages/shared/components/molecules/VerificationBadge.svelte
Labels: type:fix, context:wallet, stardust

#4056 fix: title of `TokenInfoPopup` for long asset names
  packages/shared/components/popups/TokenInformationPopup.svelte
Labels: type:fix, type:ui, stardust

#4060 enhancement: activity tile for native tokens
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/components/molecules/AssetIcon.svelte
Labels: context:wallet, type:ui, stardust

#4061 fix: text hint colours and styles
  packages/shared/components/TextHint.svelte
  packages/shared/components/popups/ConfirmationPopup.svelte
Labels: type:ui, stardust

#4038 enhancement: make token info copyable
  packages/shared/components/atoms/boxes/CopyableBox.svelte
  packages/shared/components/atoms/boxes/KeyValueBox.svelte
  packages/shared/components/atoms/buttons/AssetActionsButton.svelte
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
  packages/shared/lib/core/network/constants/base-token.constant.ts
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, stardust

#4066 fix: use asset icon in dropdown
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/molecules/AssetIcon.svelte
Labels: type:fix, type:ui, stardust

#4065 enhancement: claim / view flow of unknown tokens
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
  packages/shared/lib/core/profile-manager/api/events/newOutput.ts
  packages/shared/lib/core/wallet/actions/hideActivitiesForHiddenAssets.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivities.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivitiesFromOutputs.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivitiesFromTransactions.ts
  packages/shared/lib/core/wallet/actions/mintNativeToken.ts
  packages/shared/lib/core/wallet/actions/sendOutput.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, stardust

#4069 update: sync outputs with transactions
  packages/shared/lib/core/profile-manager/api/events/newOutput.ts
  packages/shared/lib/core/profile-manager/api/types/newOutputEvent.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivitiesFromOutputs.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromInputs.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromTransaction.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromTransactionInputs.ts
  packages/shared/lib/core/wallet/utils/transactions/index.ts
Labels: type:enhancement, context:wallet, stardust

#4071 update: native tokens in transaction popup
  packages/shared/components/molecules/TransactionDetails.svelte
Labels: type:enhancement, context:wallet, type:ui, stardust

#4076 release: desktop 2.0.0 alpha 2.0
  .github/workflows/build-desktop.yml
  packages/desktop/package.json
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/routes/login/views/EnterPinView.svelte
Labels: type:chore, stardust

#4041 fix: pincode android edge case
  packages/shared/components/inputs/Pin.svelte
Labels: type:fix, platform:mobile

#3856 chore: change header animation
  packages/shared/components/AccountNavigation.svelte
  packages/shared/components/MainMenu.svelte
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
Labels: type:chore, platform:mobile

#4099 chore: merge `release/desktop-2.0.0-beta-2` into `stardust-develop`
  packages/desktop/package.json
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/features/onboardingFeatures.ts
  packages/shared/lib/core/profile-manager/api/events/newOutput.ts
  packages/shared/lib/core/wallet/constants/special-token-id.constant.ts
  packages/shared/routes/login/views/EnterPinView.svelte
Labels: type:chore, stardust

#4091 fix: revert electron-builder version
  packages/desktop/package.json
  yarn.lock
Labels: type:fix, package:desktop, stardust

#4090 fix: moves no recent history positioning to the top
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
Labels: type:fix, platform:mobile, package:shared

#4088 fix: adds margin bottom to address and increase its font size
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
Labels: type:fix, platform:mobile, package:shared
