Repository iotaledger/firefly, pull requests merged in 2022-05, with the labels that each got.

#3080 feat: add merge votes && fix pending participations
  packages/shared/components/popups/GovernanceManager.svelte
  packages/shared/lib/participation/account.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
Labels: context:voting

#3074 feat: basic send confirmation popup for stardust profiles
  packages/shared/components/atoms/pills/ActivityTypePill.svelte
  packages/shared/components/index.js
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/molecules/index.js
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/Transaction.svelte
  packages/shared/lib/typings/activity.ts
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:feature, type:refactor, context:wallet

#3082 refactor: change syncing to per account
  packages/backend/bindings/node/index.ts
  packages/mobile/capacitor/walletPluginApi.ts
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/components/modals/AccountActions.svelte
  packages/shared/components/modals/AccountSwitcher.svelte
  packages/shared/components/popups/BalanceFinder.svelte
  packages/shared/components/popups/NewStakingPeriodNotification.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/assets.ts
  packages/shared/lib/errors.ts
  packages/shared/lib/networkStatus.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/participation/stores.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/typings/account.ts
  packages/shared/lib/typings/walletApi.ts
  packages/shared/lib/wallet.ts
  packages/shared/lib/walletApiListeners.ts
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
  packages/shared/routes/dashboard/wallet/views/BarChart.svelte
  packages/shared/routes/dashboard/wallet/views/LineChart.svelte
  packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:enhancement, type:refactor

#3039 feat: onboarding with new bindings
  packages/desktop/electron/preload.js
  packages/shared/components/inputs/ImportTextfield.svelte
  packages/shared/components/popups/Backup.svelte
  packages/shared/components/popups/BalanceFinder.svelte
  packages/shared/components/popups/DeleteAccount.svelte
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/HideAccount.svelte
  packages/shared/components/popups/Password.svelte
  packages/shared/components/popups/SwitchNetwork.svelte
  packages/shared/lib/app.ts
  packages/shared/lib/core/router/subrouters/backup-router.ts
  packages/shared/lib/core/router/subrouters/import-router.ts
  packages/shared/lib/core/router/subrouters/protect-router.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/wallet.ts
  packages/shared/lib/walletApiListeners.ts
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/setup/Password.svelte
  packages/shared/routes/setup/Profile.svelte
  packages/shared/routes/setup/backup/Backup.svelte
  packages/shared/routes/setup/backup/views/VerifyRecoveryPhrase.svelte
Labels: type:feature, context:onboarding

#3086 fix: refactors getColor
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/ActivityDetail.svelte
  packages/shared/components/ColorPicker.svelte
  packages/shared/components/WalletPill.svelte
  packages/shared/components/charts/Bar.svelte
  packages/shared/components/charts/Line.svelte
  packages/shared/components/modals/AccountSwitcher.svelte
  packages/shared/components/popups/CreateAccount.svelte
  packages/shared/lib/chart.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/typings/chart.ts
  packages/shared/lib/typings/color.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/wallet/views/ManageAccount.svelte
Labels: type:fix

#3139 feat: stardust sidebar network indicator
  packages/shared/components/NetworkIndicator.svelte
  packages/shared/components/Sidebar.svelte
  packages/shared/components/index.js
  packages/shared/components/modals/NetworkIndicator.svelte
  packages/shared/components/modals/NetworkSummaryModal.svelte
  packages/shared/components/modals/index.js
  packages/shared/lib/typings/profile.ts
  packages/shared/locales/en.json
Labels: type:feature

#3059 feat: stardust shimmer network
  packages/shared/lib/network.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/lib/typings/assets.ts
  packages/shared/lib/typings/network.ts
Labels: type:feature, stardust

#3149 refactor: wallet tab components
  packages/shared/components/index.js
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/molecules/index.js
  packages/shared/components/organisms/AccountAssetsList.svelte
  packages/shared/components/organisms/AccountHistory.svelte
  packages/shared/components/organisms/AccountSummary.svelte
  packages/shared/components/organisms/index.js
  packages/shared/components/panes/Pane.svelte
  packages/shared/components/panes/index.js
  packages/shared/components/panes/wallet/AccountHistoryPane.svelte
  packages/shared/components/panes/wallet/AccountSummaryAndAssetsPane.svelte
  packages/shared/components/panes/wallet/AssetsPane.svelte
  packages/shared/components/panes/wallet/BarChartPane.svelte
  packages/shared/components/panes/wallet/LineChartPane.svelte
  packages/shared/components/panes/wallet/index.js
  packages/shared/lib/walletApiListeners.ts
  packages/shared/routes/dashboard/staking/Staking.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/index.js
Labels: type:refactor, context:wallet, type:ui, stardust

#3163 fix: handle different decimal separators for deep links
  packages/shared/lib/common/deep-links/wallet-context-handler.ts
  packages/shared/lib/tests/utils.test.ts
  packages/shared/lib/utils.ts
Labels: type:fix

#3156 Feat: add partial vote sidebar notification
  packages/shared/components/Sidebar.svelte
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/components/popups/NewStakingPeriodNotification.svelte
  packages/shared/components/popups/Transaction.svelte
  packages/shared/lib/participation/account.ts
  packages/shared/lib/participation/constants.ts
  packages/shared/lib/participation/stores.ts
  packages/shared/routes/dashboard/staking/views/StakingAirdrop.svelte
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
Labels: context:voting

#3150 refactor: network status for stardust
  packages/mobile/App.svelte
  packages/shared/components/NetworkIndicator.svelte
  packages/shared/components/modals/NetworkSummaryModal.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/AddNode.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/jest.config.js
  packages/shared/lib/assets.ts
  packages/shared/lib/core/network/actions/getAndUpdateNodeInfo.ts
  packages/shared/lib/core/network/actions/index.ts
  packages/shared/lib/core/network/actions/network-polling.ts
  packages/shared/lib/core/network/actions/showNetworkIssueNotification.ts
  packages/shared/lib/core/network/constants/index.ts
  packages/shared/lib/core/network/constants/network-health-colours.constant.ts
  packages/shared/lib/core/network/constants/network-status-description.enum.ts
  packages/shared/lib/core/network/constants/network-status-poll-interval.constant.ts
  packages/shared/lib/core/network/enums/index.ts
  packages/shared/lib/core/network/enums/network-health.enum.ts
  packages/shared/lib/core/network/helpers/getNetworkStatusFromNodeInfo.ts
  packages/shared/lib/core/network/helpers/index.ts
  packages/shared/lib/core/network/index.ts
  packages/shared/lib/core/network/interfaces/index.ts
  packages/shared/lib/core/network/interfaces/network-status.interface.ts
  packages/shared/lib/core/network/interfaces/node-info-response.interface.ts
  packages/shared/lib/core/network/interfaces/node-info.interface.ts
  packages/shared/lib/core/network/stores/index.ts
  packages/shared/lib/core/network/stores/network-status.store.ts
  packages/shared/lib/core/network/stores/node-info.store.ts
  packages/shared/lib/core/network/utils/checkNodeUrlValidity.ts
  packages/shared/lib/core/network/utils/cleanNodeAuth.ts
  packages/shared/lib/core/network/utils/doesNodeHavePlugin.ts
  packages/shared/lib/core/network/utils/ensureSinglePrimaryNode.ts
  packages/shared/lib/core/network/utils/getNetwork.ts
  packages/shared/lib/core/network/utils/getNetworkType.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/lib/networkStatus.ts
  packages/shared/lib/participation/staking.ts
  packages/shared/lib/participation/stores.ts
  packages/shared/lib/profile.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/lib/typings/network.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
  packages/shared/routes/setup/Profile.svelte
  packages/shared/routes/setup/ledger/views/Connect.svelte
  packages/shared/routes/setup/ledger/views/GenerateNewAddress.svelte
  packages/shared/routes/setup/ledger/views/RestoreFromLedger.svelte
Labels: type:refactor, package:shared, stardust

#2459 feat: mobile implement secure filesystem access Capacitor plugin
  packages/mobile/capacitor/plugins/secure-filesystem-access/CapacitorSecureFilesystemAccess.podspec
  packages/mobile/capacitor/plugins/secure-filesystem-access/README.md
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/.gitignore
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/build.gradle
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/gradle.properties
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/gradle/wrapper/gradle-wrapper.jar
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/gradle/wrapper/gradle-wrapper.properties
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/gradlew
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/gradlew.bat
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/proguard-rules.pro
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/settings.gradle
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/androidTest/java/com/getcapacitor/android/ExampleInstrumentedTest.java
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/AndroidManifest.xml
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/Mediastore.java
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/SecureFilesystemAccessPlugin.java
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/res/.gitkeep
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/test/java/com/getcapacitor/ExampleUnitTest.java
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin.xcodeproj/project.pbxproj
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin.xcworkspace/contents.xcworkspacedata
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin/Info.plist
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin/Plugin.h
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin/Plugin.m
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Plugin/Plugin.swift
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/PluginTests/Info.plist
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/PluginTests/PluginTests.swift
  packages/mobile/capacitor/plugins/secure-filesystem-access/ios/Podfile
  packages/mobile/capacitor/plugins/secure-filesystem-access/package.json
  packages/mobile/capacitor/plugins/secure-filesystem-access/rollup.config.js
  packages/mobile/capacitor/plugins/secure-filesystem-access/src/definitions.ts
  packages/mobile/capacitor/plugins/secure-filesystem-access/src/index.ts
  packages/mobile/capacitor/plugins/secure-filesystem-access/tsconfig.json
  packages/mobile/ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme
  packages/mobile/ios/App/App/Info.plist
Labels: type:feature, platform:mobile

#3164 feat: stardust profile login changes
  packages/shared/components/Chip.svelte
  packages/shared/components/NetworkIcon.svelte
  packages/shared/components/NetworkIconBadge.svelte
  packages/shared/components/Profile.svelte
  packages/shared/components/atoms/pills/ActivityAsyncStatusPill.svelte
  packages/shared/components/atoms/pills/ActivityStatusPill.svelte
  packages/shared/components/atoms/pills/DeveloperIndicatorPill.svelte
  packages/shared/components/atoms/pills/Pill.svelte
  packages/shared/components/atoms/pills/index.js
  packages/shared/components/index.js
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/routes/login/views/EnterPin.svelte
  packages/shared/routes/login/views/SelectProfile.svelte
  packages/shared/tailwind.config.js
Labels: type:feature, context:onboarding, stardust

#2460 feat: mobile export Stronghold
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/package.json
  packages/shared/components/popups/Backup.svelte
  packages/shared/lib/core/router/subrouters/backup-router.ts
  packages/shared/lib/tests/mocks/platform.ts
  packages/shared/lib/typings/platform.ts
  packages/shared/routes/dashboard/settings/views/security/Security.svelte
  packages/shared/routes/setup/import/views/FileImport.svelte
  yarn.lock
Labels: type:feature, package:desktop, platform:mobile

#2471 feat: mobile save recovery kit PDF
  packages/mobile/capacitor/capacitorApi.ts
Labels: type:feature, platform:mobile

#2506 feat: mobile delete profile folder
  packages/mobile/capacitor/capacitorApi.ts
Labels: type:feature, platform:mobile

#3100 fix: tests fixed and new bindings tests added
  packages/desktop/package.json
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/wallet.ts
  packages/shared/lib/walletApiListeners.ts
  packages/shared/package.json
  yarn.lock
Labels: type:tests, stardust

#3177 fix: adjust bindings for node info
  packages/shared/lib/typings/profileManager.ts
  packages/shared/lib/wallet.ts
Labels: type:fix, stardust

#3185 chore: fix prettier warnings in mobile
  packages/mobile/capacitor/capacitorApi.ts
Labels: type:chore, package:mobile

#3189 fix: locale reactivity in back button
  packages/shared/components/Sidebar.svelte
  packages/shared/routes/dashboard/TopNavigation.svelte
Labels: type:fix

#3159 fix: receive qr responsiveness
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
Labels: type:fix, type:ui

#3032 fix: add reactivity for cached staking rewards
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/lib/assets.ts
Labels: type:fix, context:staking, context:wallet

#3184 chore: sync strings from Desktop 1.5.2 to develop
  packages/shared/locales/en.json
Labels: type:chore

#3183 enhancement: RecipientInput validation
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/lib/core/network/stores/index.ts
  packages/shared/lib/core/profile/actions/logout.ts
  packages/shared/lib/tests/__mocks__/i18n.ts
  packages/shared/lib/tests/utils.test.ts
  packages/shared/lib/utils.ts
  packages/shared/tsconfig.test.json
Labels: type:enhancement, context:wallet, stardust

#2512 feat: mobile rename profile
  packages/backend/bindings/capacitor/android/src/main/java/org/iota/walletactorsystem/WalletPlugin.java
  packages/backend/bindings/capacitor/ios/Plugin/Plugin.swift
  packages/backend/bindings/capacitor/src/definitions.ts
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/capacitor/walletPluginApi.ts
Labels: type:feature, platform:mobile

#3226 feat: stardust modify developer profile onboarding
  packages/desktop/App.svelte
  packages/desktop/electron/lib/menu.js
  packages/desktop/electron/lib/menuState.js
  packages/desktop/lib/helpers.ts
  packages/shared/lib/typings/events.ts
  packages/shared/locales/en.json
  packages/shared/routes/login/views/SelectProfile.svelte
  packages/shared/routes/setup/Profile.svelte
  yarn.lock
Labels: type:enhancement, type:refactor, stardust

#3228 chore: upgrade @iota/wallet to 1.0.8
  packages/desktop/package.json
  packages/shared/lib/core/network/actions/updateClientOptions.ts
  packages/shared/lib/core/network/constants/network.constant.ts
  packages/shared/lib/core/network/helpers/buildClientOptions.ts
  packages/shared/lib/core/network/helpers/index.ts
  packages/shared/lib/core/network/interfaces/network.interface.ts
  packages/shared/lib/core/network/interfaces/node.interface.ts
  packages/shared/lib/core/network/interfaces/rent-structure.ts
  packages/shared/lib/core/network/utils/ensureSinglePrimaryNode.ts
  packages/shared/lib/core/network/utils/getDefaultClientOptions.ts
  packages/shared/lib/core/network/utils/getNodeCandidates.ts
  packages/shared/lib/core/network/utils/getOfficialNodes.ts
  packages/shared/lib/core/profile-manager/actions/initialiseProfileManager.ts
  packages/shared/lib/core/profile-manager/api/restoreBackup.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/profile/actions/active-profile.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/lib/tests/api.test.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/lib/typings/account.ts
  packages/shared/package.json
  packages/shared/routes/setup/Profile.svelte
  yarn.lock
Labels: scope:dependencies, type:chore, type:refactor, package:wallet.rs

#3233 fix: remove duplicate import
  packages/mobile/capacitor/capacitorApi.ts
Labels: type:fix, platform:mobile

#3230 chore: Disable horizontal rotation of the device
  packages/mobile/android/app/src/main/AndroidManifest.xml
  packages/mobile/ios/App/App/Info.plist
Labels: type:chore, platform:mobile

#3242 refactor: account summary stardust
  packages/shared/components/AssetTile.svelte
  packages/shared/components/StakingAssetTile.svelte
  packages/shared/components/Text.svelte
  packages/shared/components/atoms/buttons/AccountActionsButton.svelte
  packages/shared/components/atoms/buttons/ReceiveButton.svelte
  packages/shared/components/atoms/buttons/SendButton.svelte
  packages/shared/components/atoms/buttons/index.js
  packages/shared/components/atoms/index.js
  packages/shared/components/atoms/labels/AccountLabel.svelte
  packages/shared/components/atoms/labels/TogglableAmountLabel.svelte
  packages/shared/components/atoms/labels/index.js
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/modals/AccountActionsModal.svelte
  packages/shared/components/modals/Modal.svelte
  packages/shared/components/modals/RecipientAccountSelector.svelte
  packages/shared/components/modals/index.js
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/organisms/AccountAssetsList.svelte
  packages/shared/components/organisms/AccountSummary.svelte
  packages/shared/lib/core/network/constants/base-token.constant.ts
  packages/shared/lib/core/network/interfaces/network.interface.ts
  packages/shared/lib/core/router/SelectProfile.svelte
  packages/shared/lib/core/wallet/index.ts
  packages/shared/lib/core/wallet/interfaces/asset-balance.interface.ts
  packages/shared/lib/core/wallet/interfaces/asset.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/token-metadata.interface.ts
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/utils/formatBestMatchTokenAmount.ts
  packages/shared/lib/core/wallet/utils/formatDefaultTokenAmount.ts
  packages/shared/lib/core/wallet/utils/formatPreciseTokenAmount.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/lib/typings/assets.ts
  packages/shared/routes/dashboard/staking/views/StakingInfo.svelte
Labels: type:refactor, context:wallet, stardust

#3260 fix: logout issues
  packages/shared/lib/core/profile-manager/actions/destroyProfileManager.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
Labels: package:desktop, context:wallet, stardust

#3188 chore: strip Linux backend debug info and upload to Sentry
  .github/workflows/build-desktop.yml
Labels: scope:ci, package:backend

#3257 chore: Launch screen on Android is not keeping aspect ratio
  packages/mobile/.gitignore
  packages/mobile/android/app/src/main/res/drawable/launch_splash.xml
  packages/mobile/capacitor/assets/assetgen.sh
Labels: type:chore, platform:mobile

#3231 feat: Shimmer reward claiming views
  packages/desktop/App.svelte
  packages/shared/components/OnboardingLayout.svelte
  packages/shared/components/atoms/index.js
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/components/atoms/tiles/ButtonTile.svelte
  packages/shared/components/atoms/tiles/RewardClaimTile.svelte
  packages/shared/components/atoms/tiles/Tile.svelte
  packages/shared/components/atoms/tiles/index.js
  packages/shared/components/index.js
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/molecules/RewardClaimList.svelte
  packages/shared/components/molecules/index.js
  packages/shared/components/organisms/AccountAssetsList.svelte
  packages/shared/lib/core/router/app-router.ts
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/locales/en.json
  packages/shared/routes/index.js
  packages/shared/routes/setup/ClaimRewards.svelte
Labels: type:feature, stardust

#3250 feat: improve voting info pane (questions)
  packages/shared/components/icon/icons.js
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/governance/views/GovernanceEventInfo.svelte
Labels: context:voting

#3288 fix: fix back button on Stronghold password screen
  packages/shared/routes/setup/import/views/BackupPassword.svelte
Labels: type:fix, package:shared

#3234 fix, refactor: Stronghold import screen
  packages/shared/components/inputs/Dropzone.svelte
  packages/shared/routes/setup/import/views/FileImport.svelte
Labels: type:fix, platform:mobile, package:shared, platform:desktop

#3284 refactor: clean up transaction history search and filter
  packages/shared/components/inputs/IconTextInput.svelte
  packages/shared/components/inputs/TogglableButton.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/organisms/AccountHistory.svelte
  packages/shared/components/organisms/index.js
  packages/shared/components/panes/wallet/AccountActivityPane.svelte
  packages/shared/components/panes/wallet/AccountHistoryPane.svelte
  packages/shared/components/panes/wallet/index.js
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/searchTransactions.ts
  packages/shared/routes/dashboard/wallet/Wallet.svelte
Labels: type:enhancement, type:refactor, context:wallet, stardust

#3306 fix: add lacking function to Electron API
  packages/desktop/electron/electronApi.js
Labels: type:fix, platform:desktop

#3308 fix: add missing `unstyled` prop to button component
  packages/shared/components/Button.svelte
Labels: type:fix

#3310 Fix: `isAccountVoting` included staking participations
  packages/shared/components/popups/Transaction.svelte
Labels: type:fix, context:voting

#3301 feat: move voting results to tooltip & update CSS
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/governance/views/GovernanceEventResults.svelte
Labels: context:voting

#3303 feat: disable add new wallet while participating
  packages/shared/components/modals/AccountSwitcher.svelte
  packages/shared/locales/en.json
Labels: context:voting

#3314 fix: voting flows for ledger device
  packages/shared/components/popups/GovernanceManager.svelte
  packages/shared/routes/dashboard/governance/views/GovernanceEventDetails.svelte
  packages/shared/routes/dashboard/staking/Staking.svelte
Labels: scope:ledger, type:fix, context:voting

#3321 fix: voting CSS winner&selected not visible in light mode
  packages/shared/routes/dashboard/governance/views/GovernanceEventInfo.svelte
Labels: context:voting

#3324 feat: implement storage deposit breakdown popup
  packages/shared/components/HR.svelte
  packages/shared/components/atoms/BalanceSummarySection.svelte
  packages/shared/components/atoms/index.js
  packages/shared/components/modals/AccountActionsMenu.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/StorageDepositBreakdownPopup.svelte
  packages/shared/lib/typings/icons.ts
  packages/shared/locales/en.json
Labels: type:feature, context:wallet, stardust

#3322 enhancement: polish send form for stardust
  packages/desktop/App.svelte
  packages/shared/components/atoms/labels/TogglableAmountLabel.svelte
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/components/atoms/tiles/RewardClaimTile.svelte
  packages/shared/components/inputs/Amount.svelte
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/inputs/UnitInput.svelte
  packages/shared/components/modals/AccountSwitcherModal.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
  packages/shared/components/popups/HideAccount.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/lib/app.ts
  packages/shared/lib/chart.ts
  packages/shared/lib/common/deep-links/types/wallet-context.type.ts
  packages/shared/lib/common/deep-links/wallet-context-handler.ts
  packages/shared/lib/core/account/actions/setNextSelectedAccount.ts
  packages/shared/lib/core/profile/actions/active-profile/resetActiveProfile.ts
  packages/shared/lib/core/wallet/index.ts
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/types/index.ts
  packages/shared/lib/core/wallet/types/recipient.type.ts
  packages/shared/lib/core/wallet/utils/formatBestMatchTokenAmount.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountBestMatch.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountPrecise.ts
  packages/shared/lib/core/wallet/utils/generateRawAmount.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/parseRawAmount.ts
  packages/shared/lib/typings/sendParams.ts
  packages/shared/lib/units.ts
  packages/shared/locales/en.json
  packages/shared/routes/Splash.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:enhancement, type:refactor, context:wallet, stardust

#3330 feat: prevent back button text from breaking words into multiple lines
  packages/shared/routes/dashboard/TopNavigation.svelte
Labels: type:fix, type:ui

#3331 feat: remove governance router reset on tab selection
  packages/shared/components/Sidebar.svelte
Labels: context:voting

#3333 fix: fix app icon alignment
  packages/desktop/public/assets/icons/prod/icon1024x1024.png
Labels: type:fix, platform:desktop

#3300 Update UI of activity list items
  packages/shared/components/ActivityRow.svelte
  packages/shared/components/atoms/pills/ActivityAsyncStatusPill.svelte
  packages/shared/components/atoms/pills/ActivityStatusPill.svelte
  packages/shared/components/inputs/TogglableButton.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/wallet/actions/filterQueriedActivities.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/searchQueriedActivities.ts
  packages/shared/lib/core/wallet/enums/activity-async-status.enum.ts
  packages/shared/lib/core/wallet/enums/activity-direction.enum.ts
  packages/shared/lib/core/wallet/enums/activity-status.enum.ts
  packages/shared/lib/core/wallet/enums/activity-type.enum.ts
  packages/shared/lib/core/wallet/enums/index.ts
  packages/shared/lib/core/wallet/index.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/stores/activities.store.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/parseTransactionsToActivities.ts
  packages/shared/lib/core/wallet/utils/searchTransactions.ts
  packages/shared/lib/typings/activity.ts
  packages/shared/lib/utils.ts
  packages/shared/locales/en.json
Labels: type:enhancement, type:refactor, context:wallet, stardust

#3329 refactor: initial sendAmount logic for stardust
  packages/shared/components/popups/Password.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/core/profile-manager/actions/initialiseProfileManager.ts
  packages/shared/lib/core/profile-manager/api/clearStrongholdPassword.ts
  packages/shared/lib/core/profile-manager/api/index.ts
  packages/shared/lib/core/profile-manager/api/isStrongholdUnlocked.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/profile/actions/active-profile/lockStronghold.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/unlockStronghold.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/trySend.ts
  packages/shared/lib/send.ts
  packages/shared/lib/stronghold.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/routes/login/views/EnterPin.svelte
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/Profile.svelte
  packages/shared/routes/setup/migrate/views/Migrate.svelte
  packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Labels: type:refactor, context:wallet, stardust

#3337 chore: update Tangle Bay node
  packages/shared/lib/network.ts
Labels: type:chore

#3361 fix: changes wrong mainnet url
  packages/shared/lib/tests/network.test.ts
Labels: type:fix

#3352 Enhancement/update activityrows for async transactions
  packages/shared/components/ActivityRow.svelte
  packages/shared/components/ActivityTile.svelte
  packages/shared/components/atoms/pills/ActivityStatusPill.svelte
  packages/shared/components/index.js
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/lib/core/wallet/actions/filterQueriedActivities.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/loadAllAccountActivies.ts
  packages/shared/lib/core/wallet/actions/searchQueriedActivities.ts
  packages/shared/lib/core/wallet/actions/trySend.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/classes/index.ts
  packages/shared/lib/core/wallet/enums/inclusion-state.enum.ts
  packages/shared/lib/core/wallet/enums/index.ts
  packages/shared/lib/core/wallet/index.ts
  packages/shared/lib/core/wallet/interfaces/account-activities.interface.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/stores/activities.store.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
  packages/shared/lib/core/wallet/stores/index.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/parseTransactionsToActivities.ts
  packages/shared/lib/core/wallet/utils/receiverAddressesFromTransactionPayload.ts
  packages/shared/lib/core/wallet/utils/sendAddressFromTransactionPayload.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/locales/en.json
Labels: type:enhancement, type:refactor, context:wallet, stardust

#3362 enhancement: bottom tab navigation for mobile
  packages/shared/components/BottomNavigation.svelte
  packages/shared/components/BottomNavigationTab.svelte
  packages/shared/components/icon/icons.js
  packages/shared/components/index.js
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/lib/core/router/helper.ts
  packages/shared/lib/core/router/index.ts
  packages/shared/lib/core/router/types/bottom-navigation.ts
  packages/shared/lib/core/router/types/index.ts
  packages/shared/lib/core/router/wallet-router.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/wallet/Wallet.svelte
Labels: type:enhancement, platform:mobile, context:navigation

#3335 chore: fix building DMG on macOS 12.3+
  packages/desktop/README.md
  patches/dmg-builder+22.9.1.patch
Labels: type:documentation, os:mac, type:chore
