Repository iotaledger/firefly, pull requests merged in 2022-09, with the labels that each got.

#4362 fix: hard return at possible scrolling
  packages/shared/lib/actions.ts
Labels: platform:mobile

#4381 fix: mobile migration UI
  packages/shared/components/Toast.svelte
  packages/shared/routes/setup/Balance.svelte
  packages/shared/routes/setup/import/views/TextImport.svelte
  packages/shared/routes/setup/migrate/views/BundleMiningWarning.svelte
Labels: platform:mobile

#4349 enhancement: add feature flags for developer tools
  packages/shared/components/Sidebar.svelte
  packages/shared/features/developer-tools.features.ts
  packages/shared/features/features.ts
  packages/shared/features/onboarding.features.ts
  packages/shared/routes/dashboard/developer/Developer.svelte
Labels: type:enhancement, context:wallet, stardust

#4377 enhancement: shimmer claiming activity type
  packages/shared/components/atoms/tiles/TransactionActivityTile.svelte
  packages/shared/lib/core/wallet/interfaces/transaction-activity-data.interface.ts
  packages/shared/lib/core/wallet/utils/outputs/getTransactionActivityData.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, type:ui, stardust

#4320 enhancement: add error handling during login
  packages/shared/lib/core/account/actions/createNewAccount.ts
  packages/shared/lib/core/error/actions/index.ts
  packages/shared/lib/core/error/actions/logAndNotifyError.ts
  packages/shared/lib/core/error/constants/error-regex.constant.ts
  packages/shared/lib/core/error/constants/index.ts
  packages/shared/lib/core/error/constants/wallet-rs-error-parameters.constant.ts
  packages/shared/lib/core/error/enums/client-error.enum.ts
  packages/shared/lib/core/error/enums/index.ts
  packages/shared/lib/core/error/enums/wallet-rs-error.enum.ts
  packages/shared/lib/core/error/handlers/handleError.ts
  packages/shared/lib/core/error/handlers/handleGenericError.ts
  packages/shared/lib/core/error/handlers/index.ts
  packages/shared/lib/core/error/handlers/walletRs/handleWalletRsError.ts
  packages/shared/lib/core/error/handlers/walletRs/index.ts
  packages/shared/lib/core/error/handlers/walletRs/subhandlers/handleClientError.ts
  packages/shared/lib/core/error/handlers/walletRs/subhandlers/index.ts
  packages/shared/lib/core/error/handlers/walletRs/walletRs/handleClientError.ts
  packages/shared/lib/core/error/index.ts
  packages/shared/lib/core/error/interfaces/error-parameters.interface.ts
  packages/shared/lib/core/error/interfaces/error.interface.ts
  packages/shared/lib/core/network/actions/getAndUpdateNodeInfo.ts
  packages/shared/lib/core/profile-manager/api/createStardustAccount.ts
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/locales/en.json
Labels: type:enhancement, stardust, context:login

#4330 chore: upgrade electron
  packages/desktop/App.svelte
  packages/desktop/electron/electronApi.js
  packages/desktop/electron/lib/Ledger.js
  packages/desktop/electron/main.js
  packages/desktop/electron/preload.js
  packages/desktop/package.json
  packages/shared/components/filters/Filter.svelte
  packages/shared/components/filters/FilterItem.svelte
  packages/shared/components/modals/FilterModal.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/AccountIndexView.svelte
  patches/node-hid+2.1.1.patch
  patches/usb+1.7.1.patch
  yarn.lock
Labels: package:desktop, stardust

#4394 chore: add address click to copy for activity details
  packages/shared/components/ActivityDetail.svelte
Labels: platform:mobile

#4396 fix: mobile language change reactivity
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
Labels: type:fix, platform:mobile

#4241 feat: enables privacy screen capacitor plugin
  packages/mobile/capacitor.config.ts
Labels: status:do-not-merge, type:feature, platform:mobile, package:shared

#4398 fix: force the right decimal sign for the amount calculation
  packages/shared/components/inputs/Amount.svelte
  packages/shared/components/inputs/Input.svelte
Labels: type:fix, platform:mobile

#4400 fix: changes toast dismiss button color to message color
  packages/shared/components/Toast.svelte
Labels: platform:mobile

#4333 feat: Ledger Shimmer claiming flow
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/components/popups/CreateAccountPopup.svelte
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/LedgerTransactionPopup.svelte
  packages/shared/components/popups/ManageAccountPopup.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/features/onboarding.features.ts
  packages/shared/lib/contexts/onboarding/actions/claimShimmerRewards.ts
  packages/shared/lib/contexts/onboarding/actions/createShimmerClaimingProfileManager.ts
  packages/shared/lib/contexts/onboarding/actions/initialiseFirstShimmerClaimingAccount.ts
  packages/shared/lib/contexts/onboarding/stores/onboarding-profile.store.ts
  packages/shared/lib/core/account/actions/syncSelectedAccount.ts
  packages/shared/lib/core/account/actions/tryCreateAdditionalAccount.ts
  packages/shared/lib/core/account/actions/tryEditSelectedAccountMetadata.ts
  packages/shared/lib/core/ledger/actions/handleLedgerError.ts
  packages/shared/lib/core/network/utils/getOfficialExplorerUrl.ts
  packages/shared/lib/core/profile-manager/actions/subscribeToWalletApiEvents.ts
  packages/shared/lib/core/profile-manager/actions/unsubscribeFromWalletApiEvents.ts
  packages/shared/lib/core/profile-manager/api/events/transaction-progress.event.ts
  packages/shared/lib/core/profile-manager/utils/buildProfileManagerOptionsFromProfileData.ts
  packages/shared/lib/core/profile-manager/utils/getSecretManagerFromProfileType.ts
  packages/shared/lib/core/profile-manager/utils/index.ts
  packages/shared/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/lib/core/profile/constants/initial-account-gap-limit.constant.ts
  packages/shared/lib/core/profile/constants/initial-address-gap-limit.constant.ts
  packages/shared/lib/core/profile/enums/profile-type.enum.ts
  packages/shared/lib/core/profile/stores/index.ts
  packages/shared/lib/core/profile/stores/is-active-ledger-profile.store.ts
  packages/shared/lib/core/profile/stores/is-ledger-profile.store.ts
  packages/shared/lib/core/profile/utils/index.ts
  packages/shared/lib/core/profile/utils/isLedgerProfile.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountPrecise.ts
  packages/shared/lib/stronghold.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
  packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
  packages/shared/routes/dashboard/settings/views/advanced/Advanced.svelte
  packages/shared/routes/login/views/SelectProfileView.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/ConnectView.svelte
  packages/shared/routes/onboarding/views/profile-backup/ProfileBackupRouter.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/BackupMnemonicView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/BackupStrongholdView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/VerifyMnemonicView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/ViewMnemonicView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/index.js
  packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
  packages/shared/routes/onboarding/views/shimmer-claiming/views/SuccessView.svelte
Labels: type:feature, scope:ledger, context:onboarding, stardust

#4426 refactor: cleanup ledger popups
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/LedgerAddress.svelte
  packages/shared/components/popups/LedgerAppGuidePopup.svelte
  packages/shared/components/popups/LedgerConfirmation.svelte
  packages/shared/components/popups/LedgerConnectionGuidePopup.svelte
  packages/shared/components/popups/LedgerLegacyTransaction.svelte
  packages/shared/components/popups/LedgerMigrateIndex.svelte
  packages/shared/components/popups/PromptLedgerConnectionPopup.svelte
  packages/shared/components/popups/VerifyLedgerTransactionPopup.svelte
  packages/shared/lib/core/ledger/actions/getLedgerDeviceStatus.ts
  packages/shared/lib/core/ledger/utils/openLedgerConfirmationPopup.ts
  packages/shared/lib/core/ledger/utils/openLedgerNotConnectedPopup.ts
  packages/shared/lib/migration.ts
Labels: scope:ledger, type:refactor, stardust

#4401 fix: add correct spacing between cta buttons in send drawer
  packages/shared/components/popups/Transaction.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: platform:mobile

#4428 ui: new ledger icon
  packages/shared/components/Profile.svelte
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/lib/auxiliary/icon/svgs/ledger.svg.ts
  packages/shared/routes/login/views/EnterPinView.svelte
Labels: scope:ledger, type:ui, stardust

#4427 fix: style of Ledger connect prompt
  packages/shared/components/Animation.svelte
  packages/shared/components/atoms/LedgerAnimation.svelte
  packages/shared/components/atoms/index.js
  packages/shared/components/popups/PromptLedgerConnectionPopup.svelte
  packages/shared/lib/core/ledger/utils/openLedgerNotConnectedPopup.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/lib/core/network/utils/isShimmerNetworkProtocol.ts
  packages/shared/lib/core/utils/function.utils.ts
  packages/shared/lib/core/utils/index.ts
  packages/shared/locales/en.json
Labels: type:enhancement, scope:ledger, type:ui, stardust

#4464 refactor: simplify scroll styles and remove old styles
  packages/desktop/App.svelte
  packages/shared/components/TransactionTabs.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/inputs/Dropdown.svelte
  packages/shared/components/inputs/Dropdown2.svelte
  packages/shared/components/inputs/ImportTextfield.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/molecules/ShimmerClaimingAccountList.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/routes/login/views/SelectProfileView.svelte
  packages/shared/routes/onboarding/views/app-setup/views/LegalView.svelte
Labels: type:ui, stardust

#4467 chore: update @iota/wallet to 2.0.2-alpha.23
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#4422 enhancement: download vc redist on windows if latest is not installed
  packages/desktop/electron-builder-config.js
  packages/desktop/nsis/amd64-unicode/INetC.dll
  packages/desktop/nsis/installer.nsh
  packages/desktop/nsis/x86-ansi/INetC.dll
  packages/desktop/nsis/x86-unicode/INetC.dll
  packages/desktop/webpack.config.js
Labels: type:enhancement, type:fix, context:wallet, stardust

#4429 refactor: fix and clean up ledger polling and status checks
  packages/shared/components/atoms/buttons/ExportStrongholdButton.svelte
  packages/shared/components/atoms/iconButtons/SyncSelectedAccountIconButton.svelte
  packages/shared/components/atoms/tiles/TransactionActivityTile.svelte
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/ConnectLedgerPopup.svelte
  packages/shared/components/popups/CreateAccountPopup.svelte
  packages/shared/components/popups/EnableLedgerBlindSigningPopup.svelte
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/ManageAccountPopup.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/PromptLedgerConnectionPopup.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/components/popups/UnlockStrongholdPopup.svelte
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/lib/auxiliary/icon/svgs/ledger.svg.ts
  packages/shared/lib/core/ledger/actions/checkOrConnectLedger.ts
  packages/shared/lib/core/ledger/actions/displayNotificationForLedgerProfile.ts
  packages/shared/lib/core/ledger/actions/getAndUpdateLedgerNanoStatus.ts
  packages/shared/lib/core/ledger/actions/getLedgerDeviceStatus.ts
  packages/shared/lib/core/ledger/actions/index.ts
  packages/shared/lib/core/ledger/actions/pollLedgerNanoStatus.ts
  packages/shared/lib/core/ledger/actions/promptUserToConnectLedger.ts
  packages/shared/lib/core/ledger/constants/ledger-status-poll-interval.constant.ts
  packages/shared/lib/core/ledger/enums/ledger-app-name.enum.ts
  packages/shared/lib/core/ledger/interfaces/index.ts
  packages/shared/lib/core/ledger/interfaces/ledger-connection-state.interface.ts
  packages/shared/lib/core/ledger/interfaces/ledger-extended-status.interface.ts
  packages/shared/lib/core/ledger/interfaces/ledger-status.interface.ts
  packages/shared/lib/core/ledger/stores/index.ts
  packages/shared/lib/core/ledger/stores/is-polling-ledger-device-status.ts
  packages/shared/lib/core/ledger/stores/ledger-connection-state.store.ts
  packages/shared/lib/core/ledger/stores/ledger-device-status.store.ts
  packages/shared/lib/core/ledger/stores/ledger-nano-status.store.ts
  packages/shared/lib/core/ledger/utils/determineLedgerConnectionState.ts
  packages/shared/lib/core/ledger/utils/determineLedgerDeviceState.ts
  packages/shared/lib/core/ledger/utils/index.ts
  packages/shared/lib/core/ledger/utils/openLedgerNotConnectedPopup.ts
  packages/shared/lib/core/profile-manager/api/events/transaction-progress.event.ts
  packages/shared/lib/core/profile-manager/api/getLedgerNanoStatus.ts
  packages/shared/lib/core/profile-manager/api/getLedgerStatus.ts
  packages/shared/lib/core/profile-manager/api/index.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/profile/actions/active-profile/checkActiveProfileAuth.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/lib/core/stronghold/actions/checkOrUnlockStronghold.ts
  packages/shared/lib/core/stronghold/actions/index.ts
  packages/shared/lib/core/stronghold/index.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/stronghold.ts
  packages/shared/lib/tests/__mocks__/profile-manager.mock.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/ConnectView.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/InstallationGuideView.svelte
Labels: type:chore, scope:ledger, type:fix, package:wallet.rs, stardust

#4430 enhancement: add vertical variant of key value box to be used in Ledger popups
  packages/shared/components/atoms/boxes/Box.svelte
  packages/shared/components/atoms/boxes/KeyValueBox.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
Labels: type:enhancement, type:ui, stardust

#4437 enhancement: cleanup ledger connection view
  package.json
  packages/shared/components/popups/ConnectLedgerPopup.svelte
  packages/shared/locales/en.json
  packages/shared/package.json
  packages/shared/routes/onboarding/views/ledger-setup/views/ConnectLedgerView.svelte
Labels: type:enhancement, scope:ledger, context:onboarding, stardust

#4465 refactor: lib/password.ts into @core/stronghold
  packages/shared/lib/core/stronghold/constants/index.ts
  packages/shared/lib/core/stronghold/constants/password-reason-map.constant.ts
  packages/shared/lib/core/stronghold/index.ts
  packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
  packages/shared/routes/onboarding/views/stronghold-setup/views/SetupStrongholdPasswordView.svelte
Labels: type:refactor, stardust

#4484 fix: wrong url for issue report
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
Labels: type:fix, platform:mobile

#4481 chore: cleanup ledger animations
  packages/shared/assets/animations/ledger-choose-index-desktop-darkmode.json
  packages/shared/assets/animations/ledger-choose-index-desktop.json
  packages/shared/assets/animations/ledger-generate-address-desktop.json
  packages/shared/assets/animations/ledger-migrate-desktop-darkmode.json
  packages/shared/assets/animations/ledger-migrate-desktop.json
  packages/shared/assets/animations/ledger-switch-app-desktop.json
  packages/shared/assets/animations/ledger/ledger-app-closed-desktop.json
  packages/shared/assets/animations/ledger/ledger-bg-desktop-darkmode.json
  packages/shared/assets/animations/ledger/ledger-bg-desktop.json
  packages/shared/assets/animations/ledger/ledger-confirm-prompt-desktop.json
  packages/shared/assets/animations/ledger/ledger-connected-desktop.json
  packages/shared/assets/animations/ledger/ledger-disconnected-desktop.json
  packages/shared/assets/animations/ledger/ledger-prompt-confirmed-desktop.json
  packages/shared/components/Animation.svelte
  packages/shared/components/atoms/LedgerAnimation.svelte
  packages/shared/components/popups/LedgerAppGuidePopup.svelte
  packages/shared/components/popups/LedgerConnectionGuidePopup.svelte
  packages/shared/components/popups/VerifyLedgerTransactionPopup.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/ConnectLedgerView.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/LedgerInstallationGuideView.svelte
Labels: type:chore, context:wallet, stardust

#4485 feat: add async tx support ledger
  packages/shared/components/TextHint.svelte
  packages/shared/components/atoms/buttons/SendButton.svelte
  packages/shared/components/atoms/tiles/TransactionActivityTile.svelte
  packages/shared/components/popups/EnableLedgerBlindSigningPopup.svelte
  packages/shared/components/popups/VerifyLedgerTransactionPopup.svelte
  packages/shared/lib/core/ledger/stores/index.ts
  packages/shared/lib/core/ledger/stores/ledger-prepared-output.store.ts
  packages/shared/lib/core/ledger/stores/show-internal-verification-popup.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/locales/en.json
Labels: type:feature, scope:ledger, stardust

#4489 fix: filter polishing
  packages/shared/components/filters/Filter.svelte
  packages/shared/components/filters/FilterItem.svelte
  packages/shared/components/inputs/Dropdown.svelte
  packages/shared/components/inputs/Dropdown2.svelte
  packages/shared/components/modals/FilterModal.svelte
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/general/Currency.svelte
  packages/shared/routes/dashboard/settings/views/general/Language.svelte
  packages/shared/routes/onboarding/views/app-setup/views/LanguageAndAppearanceView.svelte
  packages/shared/tailwind.config.js
Labels: type:fix, context:wallet, stardust

#4496 fix: input polishing
  packages/shared/components/atoms/buttons/AddInputButton.svelte
  packages/shared/components/inputs/AmountInput.svelte
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/inputs/InputContainer.svelte
  packages/shared/components/inputs/TextInput.svelte
  packages/shared/locales/en.json
Labels: type:fix, context:wallet, type:ui, stardust

#4495 enhancement: date filter
  packages/shared/components/filters/Filter.svelte
  packages/shared/components/filters/FilterItem.svelte
  packages/shared/components/filters/items/AssetFilterItem.svelte
  packages/shared/components/filters/items/DateFilterItem.svelte
  packages/shared/components/filters/items/NumberFilterItem.svelte
  packages/shared/components/filters/items/SelectionFilterItem.svelte
  packages/shared/components/filters/items/index.js
  packages/shared/components/inputs/DateTimePicker.svelte
  packages/shared/components/inputs/Dropdown.svelte
  packages/shared/components/inputs/ExpirationDateTimePicker.svelte
  packages/shared/components/molecules/DateInputButton.svelte
  packages/shared/components/molecules/index.js
  packages/shared/lib/core/wallet/enums/filters/date-filter-option.enum.ts
  packages/shared/lib/core/wallet/enums/filters/date-unit.enum.ts
  packages/shared/lib/core/wallet/enums/filters/index.ts
  packages/shared/lib/core/wallet/interfaces/filter.interface.ts
  packages/shared/lib/core/wallet/interfaces/filter/date-filter-input.interface.ts
  packages/shared/lib/core/wallet/interfaces/filter/filter-unit.interface.ts
  packages/shared/lib/core/wallet/interfaces/filter/filter.interface.ts
  packages/shared/lib/core/wallet/interfaces/filter/index.ts
  packages/shared/lib/core/wallet/interfaces/filter/number-filter-input.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
  packages/shared/lib/core/wallet/utils/isVisibleActivity.ts
  packages/shared/lib/utils/dateUtils.ts
  packages/shared/locales/en.json
Labels: type:enhancement, type:refactor, context:wallet, stardust

#4504 enhancement: validate tag and metadata length
  packages/shared/components/inputs/ClosableInput.svelte
  packages/shared/components/inputs/ClosableInputContainer.svelte
  packages/shared/components/inputs/Input.svelte
  packages/shared/components/inputs/NumberInput.svelte
  packages/shared/components/inputs/TextInput.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/lib/auxiliary/deep-link/errors/index.ts
  packages/shared/lib/auxiliary/deep-link/errors/metadata-length.error.ts
  packages/shared/lib/auxiliary/deep-link/errors/tag-length.error.ts
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
  packages/shared/lib/core/wallet/utils/isVisibleActivity.ts
  packages/shared/lib/utils/getByteLengthOfString.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, type:ui, stardust

#4537 chore: merge `release/desktop-2.0.0-beta-6` into `stardust-develop`
  packages/desktop/package.json
  packages/shared/features/onboarding.features.ts
Labels: type:chore, stardust

#4528 chore: upgrade electron
  package.json
  packages/desktop/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#4536 chore: polish send native token
  packages/shared/components/popups/TokenInformationPopup.svelte
Labels: type:chore, type:ui, stardust

#4534 fix: use getters instead of meta properties on account
  packages/shared/lib/core/wallet/actions/activities/generateAndStoreActivitiesForAccount.ts
  packages/shared/lib/core/wallet/actions/activities/preprocessOutputsForAccount.ts
  packages/shared/lib/core/wallet/actions/activities/preprocessTransactionsForAccount.ts
Labels: type:fix, context:wallet, stardust

#4560 chore: update onboarding animations
  packages/shared/assets/animations/onboarding-desktop-darkmode.json
  packages/shared/assets/animations/onboarding-desktop.json
  packages/shared/components/Animation.svelte
  packages/shared/routes/onboarding/views/network-setup/views/SetupPrivateNetworkConnectionView.svelte
  packages/shared/routes/onboarding/views/profile-setup/views/EnterNameView.svelte
  packages/shared/routes/onboarding/views/profile-setup/views/SetupView.svelte
Labels: type:chore, context:onboarding, stardust

#4563 fix: rename unused locale
  packages/shared/locales/af.json
  packages/shared/locales/ar.json
  packages/shared/locales/bg.json
  packages/shared/locales/ca.json
  packages/shared/locales/cs.json
  packages/shared/locales/da.json
  packages/shared/locales/de.json
  packages/shared/locales/el.json
  packages/shared/locales/en.json
  packages/shared/locales/eo.json
  packages/shared/locales/es-ES.json
  packages/shared/locales/es-LA.json
  packages/shared/locales/et.json
  packages/shared/locales/fa.json
  packages/shared/locales/fi.json
  packages/shared/locales/fr.json
  packages/shared/locales/he.json
  packages/shared/locales/hi.json
  packages/shared/locales/hr.json
  packages/shared/locales/hu.json
  packages/shared/locales/id.json
  packages/shared/locales/it.json
  packages/shared/locales/ja.json
  packages/shared/locales/ko.json
  packages/shared/locales/ku.json
  packages/shared/locales/lv.json
  packages/shared/locales/mk.json
  packages/shared/locales/nl.json
  packages/shared/locales/no.json
  packages/shared/locales/pl.json
  packages/shared/locales/pt-BR.json
  packages/shared/locales/pt-PT.json
  packages/shared/locales/ro.json
  packages/shared/locales/ru.json
  packages/shared/locales/si.json
  packages/shared/locales/sk.json
  packages/shared/locales/sl.json
  packages/shared/locales/sq.json
  packages/shared/locales/sr.json
  packages/shared/locales/sv.json
  packages/shared/locales/tr.json
  packages/shared/locales/uk.json
  packages/shared/locales/ur.json
  packages/shared/locales/vi.json
  packages/shared/locales/zh-CN.json
  packages/shared/locales/zh-TW.json
Labels: scope:ledger, type:fix, type:ui, stardust

#4562 Fixed wrong links for FAQ and documentation sites
  packages/shared/lib/core/router/enums/routes.ts
Labels: type:fix

#4555 enhancement: add official verification status
  packages/shared/components/atoms/tiles/FoundryActivityTile.svelte
  packages/shared/components/atoms/tiles/TransactionActivityTile.svelte
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/components/molecules/VerificationBadge.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
  packages/shared/lib/auxiliary/icon/constants/icon-svg.ts
  packages/shared/lib/auxiliary/icon/enums/icon.enum.ts
  packages/shared/lib/auxiliary/icon/svgs/index.ts
  packages/shared/lib/auxiliary/icon/svgs/verification-status-new.svg.ts
  packages/shared/lib/auxiliary/icon/svgs/verification-status-official.svg.ts
  packages/shared/lib/auxiliary/icon/svgs/verification-status-self.svg.ts
  packages/shared/lib/core/wallet/actions/mintNativeToken.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/actions/requestAndStorePersistedAsset.ts
  packages/shared/lib/core/wallet/constants/animated-token-ids.constant.ts
  packages/shared/lib/core/wallet/constants/index.ts
  packages/shared/lib/core/wallet/constants/official-token-ids.constant.ts
  packages/shared/lib/core/wallet/constants/special-token-id.constant.ts
  packages/shared/lib/core/wallet/enums/index.ts
  packages/shared/lib/core/wallet/enums/not-verified-status.enum.ts
  packages/shared/lib/core/wallet/enums/verification-status.enum.ts
  packages/shared/lib/core/wallet/enums/verified-status.enum.ts
  packages/shared/lib/core/wallet/helpers/buildPersistedAssetFromIrc30Metadata.ts
  packages/shared/lib/core/wallet/interfaces/persisted-asset.interface.ts
  packages/shared/lib/core/wallet/stores/persisted-assets.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-assets.store.ts
  packages/shared/lib/core/wallet/types/asset-verification.type.ts
  packages/shared/lib/core/wallet/types/index.ts
  packages/shared/lib/core/wallet/utils/isVisibleAsset.ts
  packages/shared/locales/en.json
Labels: type:enhancement, type:ui, stardust

#4590 refactor: remove sync account button from activity pane
  packages/shared/components/atoms/iconButtons/SyncSelectedAccountIconButton.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/lib/core/account/actions/index.ts
  packages/shared/lib/core/account/actions/syncSelectedAccount.ts
Labels: type:refactor, stardust

#4589 fix: allow http on developer profiles
  packages/shared/lib/core/network/utils/checkNodeUrlValidity.ts
Labels: type:fix, context:settings, stardust

#4593 fix: activity search logic
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
Labels: type:fix, context:wallet, stardust

#4597 fix: remove leftover import
  packages/shared/components/atoms/iconButtons/index.js
Labels: type:fix, stardust

#4591 fix: sync incoming transactions
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/lib/core/account/actions/createNewAccount.ts
  packages/shared/lib/core/account/actions/loadAccount.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
Labels: type:fix, stardust

#4512 fix: stronghold error upon claim shimmer
  packages/desktop/electron/electronApi.js
  packages/shared/components/popups/LedgerAppGuidePopup.svelte
  packages/shared/components/popups/LedgerConnectionGuidePopup.svelte
  packages/shared/routes/dashboard/Dashboard.svelte
Labels: type:fix, context:onboarding, stardust

#4600 fix: fix default expiration time
  packages/shared/components/popups/SendConfirmationPopup.svelte
Labels: type:fix, context:wallet, stardust

#4604 chore: change app name to "Firefly Shimmer"
  packages/desktop/electron-builder-config.js
  packages/desktop/package.json
  packages/desktop/scripts/fix-productName.js
  packages/desktop/webpack.config.js
Labels: type:chore, stardust

#4603 fix: initiate Ledger Nano polling earlier in the onboarding flow
  packages/shared/routes/onboarding/views/ledger-setup/views/ConnectLedgerView.svelte
  packages/shared/routes/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte
Labels: type:fix, context:onboarding, stardust

#4599 fix: remove gray from potential icon colours
  packages/shared/lib/core/account/utils/getIconColorFromString.ts
Labels: type:fix, type:ui, stardust

#4602 fix: use isStringTrue instead of Boolean
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
  packages/shared/lib/core/utils/index.ts
  packages/shared/lib/core/utils/string.utils.ts
Labels: type:fix, stardust

#4482 fix: content scroll overflow
  packages/shared/components/BottomNavigation.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
Labels: type:fix, platform:mobile, type:ui

#4493 fix: qr scanner back button closes app
  packages/shared/components/QRScanner.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:fix, platform:mobile

#4606 ui: add scroll positions
  packages/shared/components/modals/AccountSwitcherModal.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/locales/en.json
Labels: context:wallet, type:ui, stardust

#4502 chore: upgrade wallet rs
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#4596 fix: displaying storage deposit when gifting storage deposit
  packages/shared/components/popups/SendConfirmationPopup.svelte
Labels: type:fix, context:wallet, stardust

#4608 fix: only show delete wallet when available
  packages/shared/components/modals/AccountActionsMenu.svelte
  packages/shared/components/popups/DeleteAccount.svelte
  packages/shared/lib/core/profile-manager/actions/deleteAccount.ts
Labels: type:fix, stardust

#4592 chore: get rid of todos in locale
  packages/shared/locales/en.json
  packages/shared/routes/onboarding/views/profile-setup/views/SetupView.svelte
Labels: type:chore, stardust, translations

#4607 fix: delete profile
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/contexts/settings/actions/deleteProfile.ts
  packages/shared/lib/core/profile/constants/stronghold-password-clear-interval.constant.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/security/DeleteProfile.svelte
Labels: type:fix, context:settings, stardust

#4409 fix: restoration logic for Stronghold Shimmer claiming flow
  packages/shared/lib/contexts/onboarding/actions/restoreBackupForShimmerClaimingProfileManager.ts
  packages/shared/lib/contexts/onboarding/constants/index.ts
  packages/shared/lib/contexts/onboarding/constants/iota-profile-manager-directory-name.constant.ts
  packages/shared/lib/contexts/onboarding/constants/shimmer-claiming-profile-manager-directory-name.constant.ts
  packages/shared/lib/contexts/onboarding/errors/index.ts
  packages/shared/lib/contexts/onboarding/errors/unable-to-copy-stronghold-backup-file.error.ts
  packages/shared/lib/contexts/onboarding/errors/unable-to-restore-backup-for-profile-manager.error.ts
  packages/shared/lib/contexts/onboarding/helpers/copyStrongholdFileToProfileDirectory.ts
  packages/shared/lib/contexts/onboarding/helpers/getShimmerClaimingProfileManagerStorageDirectory.ts
  packages/shared/lib/contexts/onboarding/helpers/index.ts
  packages/shared/lib/contexts/onboarding/helpers/restoreBackupForProfileManager.ts
  packages/shared/locales/en.json
  packages/shared/routes/onboarding/views/profile-recovery/views/BackupPasswordView.svelte
Labels: type:fix, context:onboarding, stardust

#4544 enhancement: handle large token supplies and metadata
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/core/wallet/actions/getAccountAssetsForSelectedAccount.ts
  packages/shared/lib/core/wallet/constants/index.ts
  packages/shared/lib/core/wallet/constants/max-supported-decimals.constants.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
  packages/shared/lib/core/wallet/tests/formatTokenAmountDefault.test.ts
  packages/shared/lib/core/wallet/utils/convertToRawAmount.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts
  packages/shared/lib/core/wallet/utils/generateRawAmount.ts
  packages/shared/lib/core/wallet/utils/getOutputOptions.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/isVisibleActivity.ts
  packages/shared/lib/currency.ts
  packages/shared/lib/tests/currency.test.ts
  packages/shared/lib/utils/isValidIRC30.ts
Labels: type:fix, context:wallet, stardust

#4615 fix: remove hardcoded hrp in newOutputEvent
  packages/shared/lib/core/profile-manager/actions/events-handlers/handleNewOutputEvent.ts
Labels: type:fix, stardust

#4610 ui: qr code style
  packages/shared/components/QR.svelte
  packages/shared/components/atoms/buttons/ReceiveAddressButton.svelte
  packages/shared/tailwind.config.js
Labels: type:ui, stardust

#4628 ui: filter accordeon
  packages/shared/components/filters/Filter.svelte
  packages/shared/components/filters/FilterItem.svelte
Labels: context:wallet, type:ui, stardust

#4611 refactor: cleanup crash reporting
  packages/shared/lib/core/app/constants/default-app-settings.constant.ts
  packages/shared/lib/core/app/constants/index.ts
  packages/shared/lib/core/app/stores/app-settings.store.ts
  packages/shared/lib/core/app/stores/crash-reporting.store.ts
  packages/shared/lib/core/app/stores/index.ts
Labels: type:refactor, context:settings, stardust

#4506 fix: button polishing
  packages/shared/components/Button.svelte
  packages/shared/components/Spinner.svelte
  packages/shared/components/atoms/buttons/ExportStrongholdButton.svelte
  packages/shared/components/inputs/DateTimePicker.svelte
  packages/shared/components/inputs/Dropzone.svelte
  packages/shared/components/modals/FilterModal.svelte
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/components/popups/AddNodePopup.svelte
  packages/shared/components/popups/BackupStrongholdPopup.svelte
  packages/shared/components/popups/ConfirmationPopup.svelte
  packages/shared/components/popups/ConnectLedgerPopup.svelte
  packages/shared/components/popups/CreateAccountPopup.svelte
  packages/shared/components/popups/DeleteAccount.svelte
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/components/popups/Diagnostics.svelte
  packages/shared/components/popups/ErrorLog.svelte
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/FaucetRequestPopup.svelte
  packages/shared/components/popups/LedgerAppGuidePopup.svelte
  packages/shared/components/popups/LedgerConnectionGuidePopup.svelte
  packages/shared/components/popups/ManageAccountPopup.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/NodeInfoPopup.svelte
  packages/shared/components/popups/RemoveNode.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/components/popups/TestDeepLinkFormPopup.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
  packages/shared/components/popups/UnlockStrongholdPopup.svelte
  packages/shared/components/popups/Version.svelte
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/advanced/Diagnostics.svelte
  packages/shared/routes/dashboard/settings/views/advanced/ErrorLog.svelte
  packages/shared/routes/dashboard/settings/views/advanced/MigrateLedgerIndex.svelte
  packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
  packages/shared/routes/dashboard/settings/views/advanced/WalletFinder.svelte
  packages/shared/routes/dashboard/settings/views/general/ChangeProfileName.svelte
  packages/shared/routes/dashboard/settings/views/help/HelpSection.svelte
  packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
  packages/shared/routes/dashboard/settings/views/security/ChangePincode.svelte
  packages/shared/routes/dashboard/settings/views/security/DeleteProfile.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/ConnectLedgerView.svelte
  packages/shared/routes/onboarding/views/network-setup/views/SetupPrivateNetworkConnectionView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/BackupStrongholdView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/VerifyMnemonicView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/ViewMnemonicView.svelte
  packages/shared/routes/onboarding/views/profile-recovery/views/ImportMnemonicPhraseView.svelte
  packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
  packages/shared/routes/onboarding/views/storage-protection-setup/views/ChooseProtectionMethodView.svelte
  packages/shared/routes/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte
  packages/shared/routes/onboarding/views/stronghold-setup/views/SetupStrongholdPasswordView.svelte
  packages/shared/tailwind.config.js
Labels: type:refactor, type:fix, package:shared, stardust

#4616 enhancement: validate send confirmation before stronhold pw
  packages/shared/components/popups/SendConfirmationPopup.svelte
Labels: type:enhancement, context:wallet, stardust

#4629 fix: ledger connection checks in onboarding
  packages/shared/components/popups/ConnectLedgerPopup.svelte
  packages/shared/lib/core/wallet/utils/getOutputOptions.ts
  packages/shared/routes/onboarding/views/CongratulationsView.svelte
  packages/shared/routes/onboarding/views/ledger-setup/views/ConnectLedgerView.svelte
  packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
Labels: type:fix, context:onboarding, stardust

#4605 enhancement: improve continue button UX for Shimmer claiming flow
  packages/shared/lib/contexts/onboarding/utils/hasNoUnclaimedRewards.ts
  packages/shared/lib/contexts/onboarding/utils/index.ts
  packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
Labels: type:enhancement, context:onboarding, stardust

#4609 fix: menu item styles
  packages/shared/components/atoms/MenuItem.svelte
  packages/shared/components/modals/AccountActionsMenu.svelte
  packages/shared/components/modals/AssetActionsMenu.svelte
  packages/shared/components/modals/ExpirationTimePickerMenu.svelte
  packages/shared/components/modals/NodeActionsMenu.svelte
Labels: type:ui, stardust

#4634 chore: fix `NaN` issue with Shimmer claiming flow
  packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts
  packages/shared/lib/contexts/onboarding/helpers/getSortedRenamedBoundAccounts.ts
  packages/shared/lib/core/profile-manager/api/recoverAccounts.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/tests/__mocks__/profile-manager.mock.ts
  packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
Labels: type:fix, context:onboarding, stardust

#4635 enhancemnet: add spinners to specific onboarding views
  packages/shared/locales/en.json
  packages/shared/routes/onboarding/views/profile-recovery/views/BackupPasswordView.svelte
  packages/shared/routes/onboarding/views/storage-protection-setup/views/SetupPinProtectionView.svelte
Labels: type:enhancement, context:onboarding, type:ui, stardust

#4636 fix: update checkmark design
  packages/shared/lib/auxiliary/icon/svgs/status-success.svg.ts
Labels: type:fix, type:ui, stardust

#4497 fix: allow popup swipe for balance finder
  packages/shared/components/Drawer.svelte
  packages/shared/components/popups/BalanceFinder.svelte
  packages/shared/routes/dashboard/settings/views/advanced/BalanceFinder.svelte
Labels: platform:mobile, package:mobile

#4633 chore: merge `release/desktop-2.0.0-beta-7` into `stardust-develop`
  packages/desktop/package.json
  packages/shared/features/onboarding.features.ts
Labels: type:chore, stardust

#4637 fix: width expiration time picker
  packages/shared/components/modals/ExpirationTimePickerMenu.svelte
Labels: type:fix, type:ui, stardust

#4631 chore: update to wallet.rs v28
  packages/shared/components/popups/DeleteAccount.svelte
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts
  packages/shared/lib/core/account/api/claimOutputs.ts
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/core/profile-manager/api/recoverAccounts.ts
  packages/shared/lib/core/profile-manager/enums/wallet-api-event.enum.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/actions/mintNativeToken.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/lib/tests/__mocks__/profile-manager.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: package:wallet.rs, stardust

#4651 fix: unlock profile with click
  packages/shared/components/Button.svelte
  packages/shared/routes/dashboard/settings/views/general/ChangeProfileName.svelte
  packages/shared/routes/dashboard/settings/views/security/ChangePincode.svelte
Labels: type:fix, type:ui, stardust

#4654 enhancement: improve robustness onboarding and login
  packages/shared/lib/contexts/onboarding/actions/completeOnboardingProcess.ts
  packages/shared/lib/contexts/onboarding/actions/createNewProfileFromOnboardingProfile.ts
  packages/shared/lib/contexts/onboarding/actions/index.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/routes/onboarding/views/CongratulationsView.svelte
Labels: type:enhancement, context:onboarding, stardust

#4642 ui: add tooltips to transaction details
  packages/shared/components/Tooltip.svelte
  packages/shared/components/atoms/boxes/KeyValueBox.svelte
  packages/shared/components/atoms/buttons/TooltipIcon.svelte
  packages/shared/components/atoms/buttons/index.js
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/locales/en.json
Labels: context:wallet, type:ui, stardust

#4612 enhancement: create log file for each session
  packages/desktop/electron/preload.js
Labels: type:enhancement, stardust

#4656 fix: randomly missing activities
  packages/shared/lib/core/wallet/actions/activities/linkTransactionsWithClaimingTransactions.ts
Labels: type:fix, context:wallet, stardust

#4663 fix: recover account gap limit
  packages/shared/lib/core/profile/constants/initial-address-gap-limit.constant.ts
Labels: type:fix, context:onboarding, stardust

#4662 fix: reset active profile in onboarding
  packages/shared/routes/onboarding/views/network-setup/views/ChooseProtocolView.svelte
Labels: type:fix, context:onboarding, stardust

#4653 enhancement: add warning for ledger onboarding on congratulations page
  packages/shared/locales/en.json
  packages/shared/routes/onboarding/views/CongratulationsView.svelte
Labels: type:enhancement, context:onboarding, stardust

#4668 chore: update doc and faq links
  packages/shared/lib/contexts/settings/constants/documentation-url.constant.ts
  packages/shared/lib/contexts/settings/constants/faq-url.constant.ts
Labels: type:chore, context:wallet, type:ui, stardust

#4658 feat: optional input tooltip
  packages/shared/components/Tooltip.svelte
  packages/shared/components/atoms/buttons/AddInputButton.svelte
  packages/shared/components/inputs/OptionalInput.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/locales/en.json
Labels: type:feature, type:refactor, type:ui, stardust

#4670 fix: enforce one claiming transaction per account
  packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
Labels: type:fix, context:onboarding, stardust

#4671 ui: show available balance and tooltip on the send form
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/locales/en.json
Labels: context:wallet, type:ui, stardust

#4566 feat: parse deep link
  packages/shared/lib/address.ts
  packages/shared/lib/app.ts
  packages/shared/lib/common/deep-links/enums/wallet-context.enum.ts
  packages/shared/lib/common/deep-links/types/deep-link-request.type.ts
  packages/shared/lib/common/deep-links/types/wallet-context.type.ts
  packages/shared/lib/common/deep-links/wallet-context-handler.ts
  packages/shared/lib/typings/sendParams.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
Labels: type:feature, platform:desktop, desktop-1.7.0

#4685 fix: unit resets after back
  packages/shared/components/inputs/AssetAmountInput.svelte
Labels: type:fix, context:wallet, stardust

#4693 enhancement: expiration date picker menu
  packages/shared/components/atoms/MenuItem.svelte
  packages/shared/components/modals/ExpirationTimePickerMenu.svelte
Labels: type:ui, stardust

#4697 fix: stardust build workflow
  .github/workflows/build-desktop.yml
Labels: type:chore, scope:ci, stardust

#4701 fix: mint native tokens
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/lib/core/account/api/createAliasIfNecessary.ts
  packages/shared/lib/core/account/api/index.ts
  packages/shared/lib/core/wallet/actions/mintNativeToken.ts
Labels: type:fix, stardust

#4716 fix: mint native token form tooltip text
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/locales/en.json
Labels: type:fix, stardust

#4711 fix: hide expiration time on claimed activity popup
  packages/shared/components/popups/ActivityDetailsPopup.svelte
Labels: type:ui, stardust

#4712 fix: remove autofocus all buttons
  packages/shared/components/popups/FaucetRequestPopup.svelte
  packages/shared/components/popups/LegalUpdate.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/components/popups/TestDeepLinkFormPopup.svelte
  packages/shared/components/popups/TokenInformationPopup.svelte
  packages/shared/routes/onboarding/views/CongratulationsView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/BackupMnemonicView.svelte
  packages/shared/routes/onboarding/views/profile-backup/views/VerifyMnemonicView.svelte
  packages/shared/routes/onboarding/views/shimmer-claiming/views/SuccessView.svelte
Labels: type:fix, stardust

#4705 fix: changes from native button to Button component in ActivityDetailsPopup
  packages/shared/components/popups/ActivityDetailsPopup.svelte
Labels: type:ui, stardust

#4694 fix: reject tx confirmation popup styling
  packages/shared/components/popups/ActivityDetailsPopup.svelte
Labels: type:ui, stardust

#4699 enhancement: set expiration date none after gift storage deposit toggle
  packages/shared/components/molecules/ExpirationTimePicker.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
Labels: type:enhancement, stardust

#4715 fix: error handling on wrong stronghold password in claiming flow
  packages/shared/lib/contexts/onboarding/actions/restoreBackupForShimmerClaimingProfileManager.ts
  packages/shared/lib/contexts/onboarding/helpers/restoreBackupForProfileManager.ts
  packages/shared/lib/core/error/constants/error-regex.constant.ts
  packages/shared/lib/core/error/enums/client-error.enum.ts
  packages/shared/routes/onboarding/views/profile-recovery/views/BackupPasswordView.svelte
Labels: type:fix, context:onboarding, stardust

#4722 fix: fix claim status for native tokens
  packages/shared/lib/core/profile-manager/actions/events-handlers/handleSpentOutputEvent.ts
Labels: type:fix, context:wallet, stardust

#4698 fix: optional input tooltip styling
  packages/shared/components/Text.svelte
  packages/shared/components/inputs/OptionalInput.svelte
Labels: type:fix, type:ui, stardust

#4678 feat: tooltip icon for expiration and timelock
  packages/shared/components/atoms/buttons/TooltipIcon.svelte
  packages/shared/components/atoms/tiles/TransactionActivityTile.svelte
  packages/shared/lib/auxiliary/icon/constants/icon-svg.ts
  packages/shared/lib/auxiliary/icon/enums/icon.enum.ts
  packages/shared/lib/auxiliary/icon/svgs/expiration-time.svg.ts
  packages/shared/lib/auxiliary/icon/svgs/index.ts
  packages/shared/lib/auxiliary/icon/svgs/timelock.svg.ts
Labels: type:feature, type:refactor, type:fix, stardust

#4729 fix: tooltips icons buttons
  packages/shared/components/atoms/buttons/TooltipIcon.svelte
  packages/shared/components/atoms/tiles/TransactionActivityTile.svelte
  packages/shared/components/inputs/OptionalInput.svelte
Labels: type:ui, stardust

#4727 fix: multi import stronghold android
  packages/mobile/capacitor/plugins/secure-filesystem-access/android/src/main/java/org/iota/plugins/securefilesystemaccess/SecureFilesystemAccessPlugin.java
Labels: bug report, platform:mobile

#4726 feat: remove protocol selection page
  packages/desktop/App.svelte
  packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingProfile.ts
  packages/shared/lib/contexts/onboarding/actions/resetOnboardingProfile.ts
  packages/shared/lib/contexts/onboarding/helpers/buildOnboardingProfile.ts
  packages/shared/lib/core/router/onboarding-router.ts
  packages/shared/lib/core/router/subrouters/onboarding/network-setup-router.ts
  packages/shared/routes/login/views/SelectProfileView.svelte
  packages/shared/routes/onboarding/views/app-setup/views/LanguageAndAppearanceView.svelte
  packages/shared/routes/onboarding/views/profile-setup/views/SetupView.svelte
Labels: type:enhancement, stardust

#4657 enhancement: reward balance finding algorithm
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts
  packages/shared/lib/contexts/onboarding/actions/index.ts
  packages/shared/lib/contexts/onboarding/actions/syncShimmerClaimingAccount.ts
  packages/shared/lib/contexts/onboarding/constants/default-shimmer-claiming-sync-options.constant.ts
  packages/shared/lib/contexts/onboarding/constants/index.ts
  packages/shared/lib/contexts/onboarding/constants/shimmer-claiming-account-recovery-configuration.constant.ts
  packages/shared/lib/contexts/onboarding/constants/shimmer-claiming-account-sync-options.constant.ts
  packages/shared/lib/contexts/onboarding/errors/shimmer-rewards.errors.ts
  packages/shared/lib/contexts/onboarding/helpers/prepareShimmerClaimingAccount.ts
  packages/shared/lib/contexts/onboarding/utils/hasUserClaimedRewards.ts
  packages/shared/lib/core/account/utils/getBoundAccount.ts
  packages/shared/lib/core/error/classes/base-error.class.ts
  packages/shared/lib/core/ledger/constants/ledger-error-locales.constant.ts
  packages/shared/lib/core/ledger/enums/ledger-error.enum.ts
  packages/shared/lib/core/ledger/helpers/deriveLedgerError.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/constants/default-account-recovery-configuration.constant.ts
  packages/shared/lib/core/profile/constants/index.ts
  packages/shared/lib/core/profile/constants/initial-account-gap-limit.constant.ts
  packages/shared/lib/core/profile/constants/initial-address-gap-limit.constant.ts
  packages/shared/lib/core/profile/index.ts
  packages/shared/lib/core/profile/types/account-recovery-configuration.type.ts
  packages/shared/lib/core/profile/types/index.ts
  packages/shared/package.json
  packages/shared/routes/onboarding/views/profile-setup/views/SetupClaimedView.svelte
  packages/shared/routes/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
  yarn.lock
Labels: type:enhancement, context:onboarding, stardust

#4731 fix: electron menu create profile button visibility
  packages/desktop/App.svelte
  packages/desktop/electron/lib/menu.js
  packages/desktop/electron/lib/menuState.js
  packages/shared/components/OnboardingLayout.svelte
  packages/shared/lib/core/app/stores/has-completed-app-setup.store.ts
  packages/shared/lib/core/app/stores/index.ts
  packages/shared/lib/core/router/app-router.ts
  packages/shared/lib/core/router/onboarding-router.ts
  packages/shared/routes/onboarding/views/app-setup/views/LanguageAndAppearanceView.svelte
  packages/shared/routes/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/shared/routes/onboarding/views/profile-setup/views/SetupView.svelte
Labels: type:hotfix, stardust

#4734 feat: update wallet rs
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#4735 fix: ledger guide string
  packages/shared/components/popups/LedgerAppGuidePopup.svelte
Labels: type:fix, stardust

#4738 fix: snyk issues
  package.json
  packages/desktop/package.json
  packages/shared/package.json
  yarn.lock
Labels: type:chore, stardust

#4757 ui: fix closable input styling
  packages/shared/components/inputs/OptionalInput.svelte
  packages/shared/components/popups/MintNativeTokenFormPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
Labels: context:wallet, type:ui, stardust

#4526 fix: set system language as initial language
  packages/mobile/App.svelte
  packages/mobile/capacitor/capacitorApi.ts
  packages/shared/lib/tests/mocks/platform.ts
  packages/shared/lib/typings/platform.ts
Labels: type:fix, package:mobile

#4492 chore: adds tab change between input fields for iOS
  packages/shared/lib/keyboard.ts
  packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
  packages/shared/routes/setup/Password.svelte
Labels: type:chore, os:ios, platform:mobile

#4728 chore: prepare for launch
  README.md
  docs/retype.yml
  packages/desktop/App.svelte
  packages/desktop/electron-builder-config.js
  packages/desktop/package.json
  packages/shared/components/Sidebar.svelte
  packages/shared/features/features.ts
  packages/shared/features/onboarding.features.ts
  packages/shared/lib/core/network/constants/explorer-urls.constant.ts
  packages/shared/lib/core/network/constants/official-node-urls.constant.ts
  packages/shared/lib/core/network/tests/network.test.ts
Labels: status:do-not-merge, type:chore, stardust
