Repository iotaledger/firefly, pull requests merged in 2022-06, with the labels that each got.

#3351 feat: improve voting timeline in darkmode
  packages/shared/components/GovernanceInfoTooltip.svelte
Labels: context:voting

#3379 chore: fix Pods installation
  packages/mobile/ios/App/Podfile
  packages/mobile/ios/App/Podfile.lock
Labels: type:chore, os:ios, package:mobile

#3375 feat: transaction history animations
  packages/shared/components/TransactionTabs.svelte
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
Labels: type:feature, platform:mobile

#3381 chore: make Capacitor setup easier and CI-friendly
  packages/mobile/.gitignore
  packages/mobile/README.md
  packages/mobile/capacitor.config.ts
Labels: type:chore, package:mobile

#3358 feat: adds public note input component
  packages/shared/components/inputs/PublicNoteInput.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/locales/en.json
Labels: type:feature, package:shared, stardust

#3388 chore: merge handbook into `stardust-develop`
  .github/workflows/handbook.yml
  .gitignore
  docs/glossary.md
  docs/guides/coding-conventions/comments.md
  docs/guides/coding-conventions/formatting.md
  docs/guides/coding-conventions/imports.md
  docs/guides/coding-conventions/index.md
  docs/guides/coding-conventions/internationalization.md
  docs/guides/coding-conventions/naming.md
  docs/guides/coding-conventions/svelte-components.md
  docs/guides/coding-conventions/typescript-library.md
  docs/guides/developer-tips.md
  docs/guides/environment-setup/desktop.md
  docs/guides/environment-setup/extension.md
  docs/guides/environment-setup/index.md
  docs/guides/environment-setup/ledger.md
  docs/guides/environment-setup/mobile.md
  docs/guides/environment-setup/tools.md
  docs/guides/git/branches.md
  docs/guides/git/commits.md
  docs/guides/git/index.md
  docs/guides/git/pull-requests.md
  docs/guides/index.md
  docs/guides/testing.md
  docs/index.md
  docs/retype.yml
  docs/specifications/index.md
  docs/standard-operating-procedures/development/documentation.md
  docs/standard-operating-procedures/development/index.md
  docs/standard-operating-procedures/development/issues.md
  docs/standard-operating-procedures/development/releases.md
  docs/standard-operating-procedures/index.md
  docs/standard-operating-procedures/security/dependencies.md
  docs/standard-operating-procedures/security/incidents.md
  docs/standard-operating-procedures/security/index.md
  docs/standard-operating-procedures/security/vulnerabilities.md
  docs/static/icon_firefly.png
  docs/static/icon_firefly.svg
Labels: type:chore, stardust

#3390 chore: update branch for triggering handbook workflow
  .github/workflows/handbook.yml
Labels: type:chore, scope:ci, stardust

#3389 feat: update send form's asset button style
  packages/shared/components/inputs/AssetDropdown.svelte
Labels: type:feature, package:shared, stardust

#3377 feat: update wallet 1.20
  packages/shared/package.json
  yarn.lock
Labels: package:wallet.rs, stardust

#3400 fix: password strength text color
  packages/shared/components/inputs/Password.svelte
Labels: type:fix, stardust

#3406 feat: android capacitor webview settings new*
  packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/MainActivity.java
  packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/WebViewSettingsPlugin.java
Labels: type:feature, os:android, platform:mobile

#3404 Fix/unsubscribe all subscribed variables
  packages/desktop/App.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/core/app/actions/downloadAppUpdate.ts
  packages/shared/routes/dashboard/wallet/views/Send.svelte
  packages/shared/routes/setup/Balance.svelte
  packages/shared/routes/setup/migrate/views/TransferFragmentedFunds.svelte
Labels: type:chore, context:wallet, stardust

#3403 feat: manual sync to activity history
  packages/shared/components/Text.svelte
  packages/shared/components/atoms/iconButtons/SyncSelectedAccountIconButton.svelte
  packages/shared/components/atoms/iconButtons/index.js
  packages/shared/components/atoms/index.js
  packages/shared/components/inputs/TextInput.svelte
  packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/lib/core/account/actions/buildAccountState.ts
  packages/shared/lib/core/account/actions/index.ts
  packages/shared/lib/core/account/actions/loadAccount.ts
  packages/shared/lib/core/account/actions/syncSelectedAccount.ts
  packages/shared/lib/core/account/interfaces/account-state.interface.ts
  packages/shared/lib/core/account/stores/selected-account.store.ts
  packages/shared/lib/core/profile/actions/active-accounts/updateActiveAccountMetadata.ts
  packages/shared/lib/core/profile/actions/active-profile/loadAccounts.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivies.ts
  packages/shared/lib/core/wallet/actions/loadAllAccountActivies.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
Labels: type:enhancement, type:feature, context:wallet, stardust

#3405 chore: updated wallet.rs to 1.0.21
  packages/shared/components/NetworkIndicator.svelte
  packages/shared/lib/core/network/actions/getAndUpdateNodeInfo.ts
  packages/shared/lib/core/network/interfaces/node-info-response.interface.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#3397 feat: add image qr generator
  packages/shared/components/QRImage.svelte
  packages/shared/components/index.js
  packages/shared/package.json
  packages/shared/routes/dashboard/wallet/views/Receive.svelte
  yarn.lock
Labels: type:feature, platform:mobile

#3399 fix: init performance on mobile
  packages/mobile/App.svelte
  packages/mobile/public/index.html
Labels: type:fix, platform:mobile

#3423 fix: build issues to do with types
  packages/shared/lib/core/profile/actions/add-node.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/utils/isAsyncActivity.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/lib/validator.ts
Labels: type:chore, type:fix, stardust

#3427 Feat: Handle Transaction inclusion event
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/lib/core/profile-manager/api/events/newOutput.ts
  packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts
  packages/shared/lib/core/profile-manager/api/events/subscribe.ts
  packages/shared/lib/core/profile-manager/api/events/unsubscribe.ts
  packages/shared/lib/core/profile-manager/api/index.ts
  packages/shared/lib/core/profile-manager/api/types/transactionInclusionEvent.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/lib/core/wallet/actions/trySend.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
Labels: type:enhancement, type:feature, context:wallet, stardust

#3431 enhancement: initial feature flags
  packages/shared/components/Sidebar.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/panes/Pane.svelte
  packages/shared/components/panes/wallet/AccountActivityPane.svelte
  packages/shared/components/panes/wallet/AccountSummaryAndAssetsPane.svelte
  packages/shared/components/panes/wallet/BarChartPane.svelte
  packages/shared/components/panes/wallet/LineChartPane.svelte
  packages/shared/featureFlags.config.js
Labels: type:chore, type:refactor, stardust

#3458 enhancement: limit protocol and network routes with featureFlags
  packages/shared/featureFlags.config.js
  packages/shared/routes/setup/OnboardingNetwork.svelte
  packages/shared/routes/setup/OnboardingProtocol.svelte
  packages/shared/routes/setup/Profile.svelte
Labels: type:enhancement, context:onboarding, stardust

#3430 refactor: export backup with stardust api
  packages/shared/components/atoms/buttons/ExportStrongholdButton.svelte
  packages/shared/components/atoms/buttons/index.js
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/components/popups/Backup.svelte
  packages/shared/components/popups/BackupStrongholdPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/lib/contexts/settings/actions/exportStronghold.ts
  packages/shared/lib/contexts/settings/actions/index.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
  packages/shared/routes/dashboard/settings/views/security/ExportStronghold.svelte
  packages/shared/routes/dashboard/settings/views/security/Security.svelte
Labels: type:refactor, context:settings, stardust

#3385 feat: update asset dropdown list
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/components/atoms/tiles/ButtonTile.svelte
  packages/shared/components/atoms/tiles/Tile.svelte
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/lib/core/wallet/stores/assets.store.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts
  packages/shared/tailwind.config.js
Labels: type:feature, package:shared, stardust

#3476 feat: track stronghold lock status locally
  packages/shared/lib/core/app/stores/index.ts
  packages/shared/lib/core/app/stores/time.store.ts
  packages/shared/lib/core/profile-manager/api/index.ts
  packages/shared/lib/core/profile-manager/api/setStrongholdPasswordClearInterval.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/profile/actions/active-profile/lockStronghold.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/logout.ts
  packages/shared/lib/core/profile/actions/active-profile/reflectLockedStronghold.ts
  packages/shared/lib/core/profile/actions/active-profile/unlockStronghold.ts
  packages/shared/lib/core/profile/constants/index.ts
  packages/shared/lib/core/profile/constants/stronghold-password-clear-interval.constant.ts
  packages/shared/lib/core/profile/stores/hasStrongholdLocked.store.ts
  packages/shared/lib/core/profile/stores/index.ts
  packages/shared/lib/core/profile/stores/timeSinceStrongholdUnlocked.store.ts
  packages/shared/lib/core/profile/stores/timeStrongholdLastUnlocked.store.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/Dashboard.svelte
Labels: type:feature, context:settings, stardust

#3428 chore: update wallet-stardust to 1.0.23
  packages/shared/lib/core/account/actions/buildAccountState.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/lib/tests/__mocks__/accountBalance.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#3478 feat: handle spent output event
  packages/shared/lib/core/profile-manager/api/events/newOutput.ts
  packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts
  packages/shared/lib/core/profile-manager/api/events/spentOutput.ts
  packages/shared/lib/core/profile-manager/api/events/subscribe.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
Labels: type:feature, context:wallet, stardust

#3489 chore: update wallet to 1.0.24
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#3391 chore: comment documentation
  docs/guides/coding-conventions/comments.md
  docs/guides/environment-setup/tools.md
  docs/standard-operating-procedures/development/documentation.md
  package.json
  yarn.lock
Labels: type:documentation, type:chore, stardust

#3394 enhancement: adds custom datetime picker
  packages/shared/components/Tooltip.svelte
  packages/shared/components/inputs/DateTimePicker.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/modals/ExpirationTimePickerMenu.svelte
  packages/shared/components/molecules/ExpirationTimePicker.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/package.json
  yarn.lock
Labels: type:enhancement, scope:dependencies, package:shared, stardust

#3497 ui: align onboarding buttons to bottom and update icons
  packages/shared/components/OnboardingLayout.svelte
  packages/shared/components/icon/icons.js
  packages/shared/routes/setup/Create.svelte
  packages/shared/routes/setup/OnboardingNetwork.svelte
  packages/shared/routes/setup/OnboardingProtocol.svelte
  packages/shared/routes/setup/import/views/Import.svelte
Labels: context:onboarding, type:ui, stardust

#3501 refactor: remove single account guide
  packages/shared/assets/illustrations/onboarding/single-account-guide-desktop.svg
  packages/shared/assets/videos/single-account-guide.mp4
  packages/shared/components/AccountSwitcher.svelte
  packages/shared/components/Illustration.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/SingleAccountGuide.svelte
  packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/TopNavigation.svelte
Labels: type:refactor, context:onboarding, stardust

#3502 fix: display error messages on profile name
  packages/shared/routes/setup/Profile.svelte
Labels: type:fix, context:onboarding, stardust

#3463 feat: handle newOutput event
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/HideAccount.svelte
  packages/shared/components/popups/StakingConfirmation.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/core/account/actions/syncBalance.ts
  packages/shared/lib/core/profile-manager/api/events/newOutput.ts
  packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts
  packages/shared/lib/core/profile-manager/api/events/spentOutput.ts
  packages/shared/lib/core/profile-manager/api/events/subscribe.ts
  packages/shared/lib/core/profile-manager/api/types/newOutputEvent.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivies.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/constants.ts
  packages/shared/lib/core/wallet/constants/address-type.constants.ts
  packages/shared/lib/core/wallet/constants/index.ts
  packages/shared/lib/core/wallet/constants/output-type.constants.ts
  packages/shared/lib/core/wallet/constants/unlock-condition.constants.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
Labels: type:feature, context:wallet, stardust

#3425 enhancement: update send transactions flow for mobile
  packages/desktop/electron/electronApi.js
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/ios/App/Podfile
  packages/mobile/ios/App/Podfile.lock
  packages/mobile/package.json
  packages/shared/components/inputs/Amount.svelte
  packages/shared/lib/tests/mocks/platform.ts
  packages/shared/lib/typings/actionSheet.ts
  packages/shared/lib/typings/platform.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/wallet/views/Send.svelte
  yarn.lock
Labels: type:enhancement, package:mobile

#3505 fix: settings routes
  packages/desktop/electron/lib/menuState.js
  packages/desktop/lib/helpers.ts
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
  packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
Labels: type:fix, context:settings, stardust

#3481 feat: polish profiles list UI
  packages/shared/components/NetworkIcon.svelte
  packages/shared/components/NetworkIconBadge.svelte
  packages/shared/components/icon/icons.js
  packages/shared/routes/login/views/SelectProfile.svelte
Labels: type:feature, context:onboarding, stardust

#3504 feat: polish recipient modal
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/modals/RecipientAccountSelector.svelte
Labels: type:enhancement, type:ui, stardust

#3320 refactor: app logic in `router`
  packages/desktop/App.svelte
  packages/shared/jest.config.js
  packages/shared/lib/app.ts
  packages/shared/lib/contexts/onboarding/actions/backupInitialStronghold.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupOnboarding.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupOnboardingStores.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupProtectionOnboarding.ts
  packages/shared/lib/contexts/onboarding/actions/index.ts
  packages/shared/lib/contexts/onboarding/actions/storeAndCleanMnemonic.ts
  packages/shared/lib/contexts/onboarding/index.ts
  packages/shared/lib/contexts/onboarding/stores/index.ts
  packages/shared/lib/contexts/onboarding/stores/mnemonic.store.ts
  packages/shared/lib/contexts/onboarding/stores/stronghold-password.store.ts
  packages/shared/lib/contexts/onboarding/stores/wallet-pin.store.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/profile/actions/active-profile/isActiveProfileOutdated.ts
  packages/shared/lib/core/profile/actions/active-profile/migrateActiveProfile.ts
  packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/lib/core/profile/actions/index.ts
  packages/shared/lib/core/profile/actions/new-profile.ts
  packages/shared/lib/core/profile/constants/index.ts
  packages/shared/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/lib/core/profile/helpers/buildNewProfile.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/lib/core/router/app-router.ts
  packages/shared/lib/core/router/subrouters/backup-router.ts
  packages/shared/lib/core/router/subrouters/import-router.ts
  packages/shared/lib/core/router/subrouters/login-router.ts
  packages/shared/lib/core/router/subrouters/protect-router.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/Password.svelte
  packages/shared/routes/setup/backup/Backup.svelte
  packages/shared/routes/setup/backup/views/BackupToFile.svelte
  packages/shared/routes/setup/backup/views/RecoveryPhrase.svelte
  packages/shared/routes/setup/protect/Protect.svelte
  packages/shared/routes/setup/protect/views/Pin.svelte
  packages/shared/routes/setup/protect/views/RepeatPin.svelte
Labels: type:refactor, stardust

#3517 fix: checkbox text component
  packages/shared/components/Text.svelte
Labels: type:fix, stardust

#3518 fix: import router errors
  packages/shared/lib/contexts/onboarding/actions/index.ts
  packages/shared/lib/contexts/onboarding/actions/resetImportState.ts
  packages/shared/lib/contexts/onboarding/actions/restoreBackupFromFile.ts
  packages/shared/lib/contexts/onboarding/stores/import-file-path.store.ts
  packages/shared/lib/contexts/onboarding/stores/import-type.store.ts
  packages/shared/lib/contexts/onboarding/stores/index.ts
  packages/shared/lib/contexts/onboarding/stores/is-getting-migration-data.store.ts
  packages/shared/lib/core/profile-manager/api/restoreBackup.ts
  packages/shared/lib/core/router/app-router.ts
  packages/shared/lib/core/router/subrouters/import-router.ts
  packages/shared/routes/setup/backup/views/Backup.svelte
  packages/shared/routes/setup/backup/views/BackupToFile.svelte
  packages/shared/routes/setup/import/views/BackupPassword.svelte
  packages/shared/routes/setup/import/views/FileImport.svelte
  packages/shared/routes/setup/import/views/Success.svelte
  packages/shared/routes/setup/import/views/TextImport.svelte
  packages/shared/routes/setup/protect/Protect.svelte
  packages/shared/routes/setup/protect/views/Pin.svelte
Labels: type:fix, context:onboarding, stardust

#3525 enhancement: back button on send flow
  packages/shared/components/Button.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
Labels: type:enhancement, context:wallet, stardust

#3545 fix: fix import onboarding
  packages/shared/components/inputs/ImportTextfield.svelte
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/import/views/TextImport.svelte
Labels: type:fix, stardust

#3514 ui: hide migration flows and adjust onboarding text
  packages/shared/components/Button.svelte
  packages/shared/featureFlags.config.js
  packages/shared/lib/core/network/utils/formatProtocolName.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/locales/en.json
  packages/shared/routes/setup/OnboardingNetwork.svelte
  packages/shared/routes/setup/OnboardingProtocol.svelte
  packages/shared/routes/setup/Profile.svelte
  packages/shared/routes/setup/Setup.svelte
  packages/shared/routes/setup/Welcome.svelte
  packages/shared/routes/setup/import/views/Import.svelte
  packages/shared/routes/setup/import/views/Ledger.svelte
Labels: context:onboarding, type:ui, stardust

#3536 fix: use wallet name for senders
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/components/molecules/TransactionDetails.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/components/popups/SendFormPopup.svelte
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/types/index.ts
  packages/shared/lib/core/wallet/types/recipient.type.ts
  packages/shared/lib/core/wallet/types/sender.type.ts
  packages/shared/lib/core/wallet/types/subject.type.ts
  packages/shared/lib/core/wallet/utils/getSubjectFromAddress.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/isSubjectInternal.ts
  packages/shared/lib/core/wallet/utils/outputs/getRecipientFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getSenderFromOutput.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromTransaction.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromTransactionInputs.ts
Labels: type:fix, context:wallet, stardust

#3549 refactor: improve onboarding feature flags
  packages/shared/components/SettingsMenu.svelte
  packages/shared/components/Sidebar.svelte
  packages/shared/components/organisms/AccountActivity.svelte
  packages/shared/components/panes/wallet/AccountActivityPane.svelte
  packages/shared/components/panes/wallet/AccountSummaryAndAssetsPane.svelte
  packages/shared/components/panes/wallet/BarChartPane.svelte
  packages/shared/components/panes/wallet/LineChartPane.svelte
  packages/shared/features/features.js
  packages/shared/features/onboardingFeatures.js
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
  packages/shared/routes/dashboard/settings/views/SettingsViewer.svelte
  packages/shared/routes/dashboard/settings/views/advanced/Advanced.svelte
  packages/shared/routes/dashboard/settings/views/general/General.svelte
  packages/shared/routes/dashboard/settings/views/help/Help.svelte
  packages/shared/routes/dashboard/settings/views/security/Security.svelte
  packages/shared/routes/setup/Create.svelte
  packages/shared/routes/setup/OnboardingNetwork.svelte
  packages/shared/routes/setup/OnboardingProtocol.svelte
  packages/shared/routes/setup/Setup.svelte
  packages/shared/routes/setup/Welcome.svelte
  packages/shared/routes/setup/import/views/Import.svelte
Labels: type:refactor, context:onboarding, stardust

#3551 chore: update wallet rs to 1.0.25
  packages/shared/lib/contexts/onboarding/actions/resetImportState.ts
  packages/shared/lib/contexts/settings/actions/deleteProfile.ts
  packages/shared/lib/core/account/api/getOutputsWithAdditionalUnlockConditions.ts
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/core/profile-manager/api/deleteStorage.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: type:chore, package:wallet.rs, stardust

#3528 feat: reset `appRouter` before creating profile from electron menu
  packages/desktop/App.svelte
Labels: type:fix, stardust

#3516 chore: cleanup PR template
  .github/pull_request_template.md
Labels: type:chore

#3554 fix: stronghold status on first login
  packages/shared/lib/contexts/settings/actions/deleteProfile.ts
  packages/shared/lib/core/profile-manager/api/deleteAccountAndDatabase.ts
  packages/shared/lib/core/profile-manager/api/index.ts
  packages/shared/lib/core/profile-manager/api/startBackgroundSync.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/stronghold.ts
Labels: type:fix, stardust

#3559 enhancement: optimise scroll bar position on activity list
  packages/shared/components/organisms/AccountActivity.svelte
Labels: type:enhancement, stardust

#3561 fix: fix onboarding route network selection and back buttons
  packages/shared/routes/setup/OnboardingNetwork.svelte
  packages/shared/routes/setup/OnboardingProtocol.svelte
  packages/shared/routes/setup/Profile.svelte
Labels: type:fix, context:onboarding, stardust

#3556 fix: strings used on wallet finder button
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/locales/en.json
Labels: type:fix, stardust

#3552 fix: persist unit on back from send confirmation popup
  packages/shared/components/inputs/UnitInput.svelte
Labels: type:fix, context:wallet, stardust

#3564 fix: expiration date/time validation
  packages/shared/components/inputs/ExpirationDateTimePicker.svelte
  packages/shared/components/modals/ExpirationTimePickerMenu.svelte
  packages/shared/components/molecules/ExpirationTimePicker.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/core/utils/index.ts
  packages/shared/lib/core/utils/time.ts
  packages/shared/locales/en.json
Labels: type:fix, stardust

#3571 fix: tile background and hover colours
  packages/shared/components/HR.svelte
  packages/shared/components/atoms/tiles/ClickableTile.svelte
Labels: type:fix, stardust

#3565 enhancement: enable custom network configuration
  packages/shared/components/organisms/NodeConfigurationForm.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/features/onboardingFeatures.js
  packages/shared/lib/core/network/actions/index.ts
  packages/shared/lib/core/network/actions/updateNewProfileClientOptions.ts
  packages/shared/lib/core/network/actions/updateNewProfileNetwork.ts
  packages/shared/lib/core/network/actions/updateNewProfileNetworkType.ts
  packages/shared/lib/core/network/constants/official-node-urls.constant.ts
  packages/shared/lib/core/network/helpers/buildClientOptions.ts
  packages/shared/lib/core/network/utils/getDefaultClientOptions.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/add-node.ts
  packages/shared/lib/core/profile/actions/addCustomNodeToNewProfile.ts
  packages/shared/lib/core/profile/actions/new-profile.ts
  packages/shared/lib/core/profile/helpers/buildNewProfile.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
  packages/shared/routes/setup/OnboardingCustomNetwork.svelte
  packages/shared/routes/setup/OnboardingNetwork.svelte
  packages/shared/routes/setup/OnboardingProtocol.svelte
Labels: type:enhancement, stardust

#3573 fix: polish activity tile 2
  packages/shared/components/atoms/pills/ActivityAsyncStatusPill.svelte
  packages/shared/components/atoms/pills/ActivityStatusPill.svelte
  packages/shared/components/atoms/pills/Pill.svelte
  packages/shared/components/atoms/tiles/ActivityTile.svelte
Labels: type:fix, type:ui, stardust

#3577 enhancement: switch toggle
  packages/shared/components/modals/ProfileActions.svelte
Labels: scope:ux

#3562 fix: change stronghold password with new api
  packages/shared/components/index.js
  packages/shared/components/inputs/PasswordInput.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/components/organisms/NodeConfigurationForm.svelte
  packages/shared/components/popups/DeleteAccount.svelte
  packages/shared/components/popups/DeleteProfile.svelte
  packages/shared/components/popups/ExportTransactionHistory.svelte
  packages/shared/components/popups/HideAccount.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/PasswordPopup.svelte
  packages/shared/features/features.ts
  packages/shared/features/onboardingFeatures.ts
  packages/shared/lib/contexts/settings/actions/deleteProfile.ts
  packages/shared/lib/core/profile-manager/actions/changePasswordAndUnlockStronghold.ts
  packages/shared/lib/core/profile-manager/actions/index.ts
  packages/shared/lib/core/profile-manager/api/changeStrongholdPassword.ts
  packages/shared/lib/core/profile-manager/api/index.ts
  packages/shared/lib/core/profile-manager/api/setStrongholdPassword.ts
  packages/shared/lib/core/profile-manager/api/storeMnemonic.ts
  packages/shared/lib/core/profile/actions/active-profile/unlockStronghold.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
  packages/shared/routes/setup/Password.svelte
  packages/shared/routes/setup/backup/views/BackupToFile.svelte
  packages/shared/routes/setup/import/views/BackupPassword.svelte
  packages/shared/tsconfig.json
Labels: package:wallet.rs, stardust

#3574 feat: integrate removeLatestAccount API
  docs/guides/coding-conventions/errors.md
  docs/standard-operating-procedures/security/dependencies.md
  packages/shared/components/modals/AccountActionsMenu.svelte
  packages/shared/lib/core/error/classes/base-error.class.ts
  packages/shared/lib/core/error/classes/index.ts
  packages/shared/lib/core/error/index.ts
  packages/shared/lib/core/error/interfaces/error-parameters.interface.ts
  packages/shared/lib/core/error/interfaces/index.ts
  packages/shared/lib/core/profile-manager/actions/deleteAccount.ts
  packages/shared/lib/core/profile-manager/actions/index.ts
  packages/shared/lib/core/profile-manager/api/index.ts
  packages/shared/lib/core/profile-manager/api/removeLatestAccount.ts
  packages/shared/lib/core/profile-manager/errors/cannot-remove-account.error.ts
  packages/shared/lib/core/profile-manager/errors/index.ts
  packages/shared/lib/core/profile-manager/index.ts
  packages/shared/lib/core/profile/stores/active-accounts.store.ts
  packages/shared/locales/en.json
Labels: type:enhancement, package:shared, context:wallet, stardust

#3610 fix: small number of fixes applied for v2 alpha 0.0.3
  packages/desktop/package.json
  packages/shared/features/features.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/utils/getSenderAddressFromUnlockCondition.ts
  packages/shared/lib/core/wallet/utils/outputs/calculateStoragetDepositFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getExpirationDateFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getMetadataFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getSenderFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getStorageDepositFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/getTagFromOutput.ts
  packages/shared/lib/core/wallet/utils/outputs/isOutputAsync.ts
Labels: type:fix, stardust

#3616 Allow changing wallets on pending transaction
  packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, stardust

#3524 fix: disables "calt" font feature in Input [stardust-develop]
  packages/shared/components/inputs/Input.svelte
Labels: type:fix, package:shared, stardust

#3590 fix: adds truncate to profile name [develop]
  packages/shared/components/Profile.svelte
Labels: type:fix, package:shared

#3586 fix: input tabbing
  packages/shared/components/inputs/InputContainer.svelte
Labels: type:fix, stardust

#3557 enhancement: mobile beta UI update for activity details
  packages/shared/components/ActivityDetail.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, platform:mobile

#3588 fix: disables "calt" font feature in Input [develop]
  packages/shared/components/inputs/Input.svelte
Labels: type:fix, package:shared

#3624 enhancement: auto add an expiration date if a storage deposit is needed for a transaction 2
  packages/shared/components/molecules/ExpirationTimePicker.svelte
  packages/shared/components/popups/SendConfirmationPopup.svelte
Labels: type:fix, context:wallet, stardust

#3587 fix: import success layout
  packages/shared/routes/setup/import/views/Success.svelte
Labels: type:fix, stardust

#3585 fix: password key submit
  packages/shared/components/Button.svelte
  packages/shared/components/inputs/InputContainer.svelte
  packages/shared/components/popups/PasswordPopup.svelte
Labels: type:fix, stardust

#3632 feat: add success and error messages on claim/reject
  packages/shared/components/Error.svelte
  packages/shared/components/Sidebar.svelte
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/actions/hideActivity.ts
  packages/shared/locales/en.json
Labels: type:enhancement, context:wallet, stardust

#3626 refactor: PIN onboarding views
  docs/guides/coding-conventions/naming.md
  packages/desktop/App.svelte
  packages/mobile/App.svelte
  packages/shared/components/inputs/PinInput.svelte
  packages/shared/components/inputs/index.js
  packages/shared/lib/contexts/onboarding/actions/cleanupOnboardingStores.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupProtectionOnboarding.ts
  packages/shared/lib/contexts/onboarding/stores/index.ts
  packages/shared/lib/contexts/onboarding/stores/wallet-pin.store.ts
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/lib/core/router/subrouters/login-router.ts
  packages/shared/lib/core/router/subrouters/protect-router.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/settings/views/security/ChangePincode.svelte
  packages/shared/routes/index.js
  packages/shared/routes/login/LoginRouter.svelte
  packages/shared/routes/login/views/EnterPinView.svelte
  packages/shared/routes/login/views/SelectProfileView.svelte
  packages/shared/routes/login/views/index.js
  packages/shared/routes/setup/protect/ProtectRouter.svelte
  packages/shared/routes/setup/protect/views/ChooseProtectionMethodView.svelte
  packages/shared/routes/setup/protect/views/Pin.svelte
  packages/shared/routes/setup/protect/views/RepeatPin.svelte
  packages/shared/routes/setup/protect/views/SetupPinProtectionView.svelte
  packages/shared/routes/setup/protect/views/index.js
Labels: type:refactor, context:onboarding, stardust

#3647 ui: persist activity tile width
  packages/shared/components/atoms/tiles/ActivityTile.svelte
Labels: stardust

#3628 fix: don't restore accounts on new profile
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/routes/setup/Congratulations.svelte
Labels: type:fix, context:onboarding, stardust

#3589 fix: freezing long password [develop]
  packages/shared/components/inputs/Password.svelte
  packages/shared/routes/setup/Password.svelte
Labels: type:fix, package:shared

#3522 fix: freezing long password [stardust-develop]
  packages/shared/components/inputs/PasswordInput.svelte
  packages/shared/routes/setup/Password.svelte
Labels: type:fix, package:shared, stardust

#3619 chore: update onboarding mobile (new PR)
  packages/shared/components/Animation.svelte
  packages/shared/components/OnboardingLayout.svelte
  packages/shared/components/RecoveryPhrase.svelte
  packages/shared/components/inputs/Checkbox.svelte
  packages/shared/lib/core/router/app-router.ts
  packages/shared/lib/core/router/subrouters/backup-router.ts
  packages/shared/locales/en.json
  packages/shared/routes/setup/Balance.svelte
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/Create.svelte
  packages/shared/routes/setup/Password.svelte
  packages/shared/routes/setup/Profile.svelte
  packages/shared/routes/setup/Secure.svelte
  packages/shared/routes/setup/Setup.svelte
  packages/shared/routes/setup/Welcome.svelte
  packages/shared/routes/setup/import/views/BackupPassword.svelte
  packages/shared/routes/setup/import/views/FileImport.svelte
  packages/shared/routes/setup/import/views/Import.svelte
  packages/shared/routes/setup/import/views/Success.svelte
  packages/shared/routes/setup/import/views/TextImport.svelte
  packages/shared/routes/setup/legal/Legal.svelte
  packages/shared/routes/setup/migrate/views/Migrate.svelte
  packages/shared/routes/setup/migrate/views/SecureSpentAddresses.svelte
  packages/shared/routes/setup/migrate/views/SecurityCheckCompleted.svelte
  packages/shared/routes/setup/protect/views/Pin.svelte
  packages/shared/routes/setup/protect/views/RepeatPin.svelte
Labels: type:chore, platform:mobile

#3424 feat: update profile settings
  packages/mobile/android/app/src/main/java/org/iota/firefly/mobile/alpha/WebViewSettingsPlugin.java
  packages/shared/components/Animation.svelte
  packages/shared/components/Drawer.svelte
  packages/shared/components/MainMenu.svelte
  packages/shared/components/ProfileActions.svelte
  packages/shared/components/SettingsMenu.svelte
  packages/shared/components/TransactionTabs.svelte
  packages/shared/components/index.js
  packages/shared/components/modals/ProfileActions.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/NetworkStatus.svelte
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/lib/core/router/helper.ts
  packages/shared/lib/core/router/index.ts
  packages/shared/lib/core/router/profile-router.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/Settings.svelte
  packages/shared/routes/dashboard/settings/views/SettingsHome.svelte
  packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
  yarn.lock
Labels: type:feature, platform:mobile

#3613 enhancement: mobile header update
  packages/shared/components/AccountNavigation.svelte
  packages/shared/components/BottomNavigation.svelte
  packages/shared/components/MainMenu.svelte
  packages/shared/lib/animation/actions.ts
  packages/shared/lib/animation/index.ts
  packages/shared/lib/animation/stores.ts
  packages/shared/lib/animation/types.ts
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/TopNavigation.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
  packages/shared/routes/dashboard/wallet/views/AccountAssets.svelte
  packages/shared/routes/dashboard/wallet/views/AccountBalance.svelte
  packages/shared/routes/dashboard/wallet/views/AccountHistory.svelte
Labels: type:enhancement, platform:mobile

#3666 chore: update wallet.rs
  packages/shared/package.json
  yarn.lock
Labels: package:wallet.rs, stardust

#3671 chore: bump desktop version to 2.0.0-alpha-0.1.0
  packages/desktop/package.json
Labels: type:chore, stardust

#3661 refactor: activity initialization flow
  docs/specifications/activity/index.md
  packages/desktop/README.md
  packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts
  packages/shared/lib/core/profile-manager/api/events/spentOutput.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/actions/hideActivity.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/linkActivityAndClaimingTransaction.ts
  packages/shared/lib/core/wallet/actions/loadAccountActivies.ts
  packages/shared/lib/core/wallet/actions/updateActivityAsyncStateFromTransactions.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/interfaces/account-activities.interface.ts
  packages/shared/lib/core/wallet/interfaces/activity.interface.ts
  packages/shared/lib/core/wallet/interfaces/claimed-activities.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
  packages/shared/lib/core/wallet/stores/selected-account-activities.store.ts
Labels: type:refactor, context:wallet, stardust

#3677 fix: build script for various versions
  .github/workflows/build-desktop.yml
  packages/shared/lib/core/wallet/classes/activity.class.ts
Labels: type:chore, stardust

#3678 chore: add close buttons to mobile popups
  packages/shared/components/Drawer.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/locales/de.json
  packages/shared/locales/en.json
Labels: type:chore, platform:mobile

#3617 feat: add busy state to to ActivityPopup claim button
  packages/shared/components/popups/ActivityDetailsPopup.svelte
Labels: context:wallet, stardust

#3679 chore: update wallet rs
  docs/guides/coding-conventions/naming.md
  package.json
  packages/shared/components/popups/NodeInfoPopup.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/core/network/enums/index.ts
  packages/shared/lib/core/network/enums/node-plugin.enum.ts
  packages/shared/lib/core/network/helpers/getNetworkStatusFromNodeInfo.ts
  packages/shared/lib/core/network/interfaces/network-status.interface.ts
  packages/shared/lib/core/network/stores/network-status.store.ts
  packages/shared/lib/core/network/stores/node-info.store.ts
  packages/shared/lib/core/network/utils/doesNodeHavePlugin.ts
  packages/shared/lib/core/wallet/classes/activity.class.ts
  packages/shared/lib/core/wallet/utils/getOutputOptions.ts
  packages/shared/lib/participation/stores.ts
  packages/shared/lib/shell/walletApi.ts
  packages/shared/lib/tests/__mocks__/profileManager.mock.ts
  packages/shared/locales/en.json
  packages/shared/package.json
  packages/shared/routes/dashboard/staking/views/StakingSummary.svelte
  yarn.lock
Labels: type:chore, stardust

#3682 feat: confirmation popup before rejecting async activity
  packages/mobile/App.svelte
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/index.js
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/ConfirmationPopup.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/locales/en.json
Labels: type:enhancement, type:feature, context:wallet, stardust

#3683 fix: change stronghold password
  packages/shared/components/atoms/buttons/ExportStrongholdButton.svelte
  packages/shared/components/inputs/PasswordInput.svelte
  packages/shared/components/popups/PasswordPopup.svelte
  packages/shared/lib/core/profile-manager/actions/changePasswordAndUnlockStronghold.ts
  packages/shared/lib/core/profile-manager/api/changeStrongholdPassword.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/routes/dashboard/settings/views/security/ChangePassword.svelte
Labels: type:fix, stardust

#3695 fix: transaction inclusion event type
  packages/shared/lib/core/profile-manager/api/events/newTransactionInclusionEvent.ts
  packages/shared/lib/core/profile-manager/api/types/transactionInclusionEvent.ts
Labels: type:fix, context:wallet, stardust

#3696 fix: change reject activity wording to hide
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/lib/core/wallet/actions/hideActivity.ts
  packages/shared/locales/en.json
Labels: type:fix, stardust

#3686 fix: listen to events for new accounts
  packages/shared/lib/core/account/actions/createNewAccount.ts
  packages/shared/lib/core/wallet/stores/all-account-activities.store.ts
Labels: type:fix, context:wallet, stardust

#3685 enhancement: close or update activity popup on claim reject
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/lib/core/wallet/actions/claimActivity.ts
Labels: type:enhancement, type:feature, context:wallet, stardust

#3705 fix: desktop settings homepage wrong icons color
  packages/shared/components/SettingsMenu.svelte
Labels: type:fix, platform:desktop, type:ui

#3697 fix: wrong locals are loaded on mobile
  packages/mobile/App.svelte
Labels: type:fix, platform:mobile

#3712 chore: remove old handlers
  packages/shared/lib/core/profile-manager/api/events/subscribe.ts
  packages/shared/lib/walletApiListeners.ts
  packages/shared/routes/dashboard/wallet/Wallet.svelte
Labels: type:chore, context:wallet, stardust

#3704 fix: permanent inline CSS `transform` property in `Animation.svelte` breaks any other custom `transform`
  packages/shared/components/Animation.svelte
  packages/shared/routes/dashboard/wallet/views/Send.svelte
  packages/shared/routes/setup/Appearance.svelte
  packages/shared/routes/setup/Balance.svelte
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/CrashReporting.svelte
  packages/shared/routes/setup/Create.svelte
  packages/shared/routes/setup/Password.svelte
  packages/shared/routes/setup/Profile.svelte
  packages/shared/routes/setup/Secure.svelte
  packages/shared/routes/setup/Setup.svelte
  packages/shared/routes/setup/Welcome.svelte
  packages/shared/routes/setup/backup/views/Backup.svelte
  packages/shared/routes/setup/backup/views/BackupToFile.svelte
  packages/shared/routes/setup/import/views/BackupPassword.svelte
  packages/shared/routes/setup/import/views/FileImport.svelte
  packages/shared/routes/setup/import/views/Import.svelte
  packages/shared/routes/setup/import/views/Success.svelte
  packages/shared/routes/setup/import/views/TextImport.svelte
  packages/shared/routes/setup/protect/views/Pin.svelte
  packages/shared/routes/setup/protect/views/RepeatPin.svelte
  packages/shared/tailwind.config.js
Labels: type:fix, type:ui

#3687 fix: remove duplicated close buttons on mobile popups
  packages/shared/components/Drawer.svelte
  packages/shared/components/popups/Index.svelte
  packages/shared/components/popups/NetworkStatus.svelte
Labels: type:fix, platform:mobile

#3715 style: set profile icon circle always blue
  packages/shared/components/MainMenu.svelte
Labels: platform:mobile, type:ui

#3690 feat: add node call to check validity
  packages/desktop/App.svelte
  packages/shared/components/organisms/NodeConfigOptions.svelte
  packages/shared/components/organisms/NodeConfigurationForm.svelte
  packages/shared/components/popups/AddNodePopup.svelte
  packages/shared/components/popups/Diagnostics.svelte
  packages/shared/lib/contexts/onboarding/actions/backupInitialStronghold.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupOnboarding.ts
  packages/shared/lib/contexts/onboarding/actions/cleanupProtectionOnboarding.ts
  packages/shared/lib/contexts/onboarding/actions/createNewProfile.ts
  packages/shared/lib/contexts/onboarding/actions/deleteNewProfile.ts
  packages/shared/lib/contexts/onboarding/actions/index.ts
  packages/shared/lib/contexts/onboarding/actions/initProfileManagerFromNewProfile.ts
  packages/shared/lib/contexts/onboarding/actions/restoreBackupFromFile.ts
  packages/shared/lib/contexts/onboarding/actions/setNewProfileClientOptions.ts
  packages/shared/lib/contexts/onboarding/actions/setNewProfileType.ts
  packages/shared/lib/contexts/onboarding/helpers/buildNewProfile.ts
  packages/shared/lib/contexts/onboarding/helpers/index.ts
  packages/shared/lib/contexts/onboarding/stores/index.ts
  packages/shared/lib/contexts/onboarding/stores/new-profile.store.ts
  packages/shared/lib/core/profile-manager/actions/initialiseProfileManager.ts
  packages/shared/lib/core/profile/actions/active-profile/addNodeToActiveProfile.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/profile/actions/active-profile/migrateActiveProfile.ts
  packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/lib/core/profile/actions/add-node.ts
  packages/shared/lib/core/profile/actions/index.ts
  packages/shared/lib/core/profile/actions/new-profile.ts
  packages/shared/lib/core/profile/constants/default-active-profile-values.constant.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/lib/core/profile/interfaces/profile-settings.interface.ts
  packages/shared/lib/core/profile/stores/index.ts
  packages/shared/lib/core/router/app-router.ts
  packages/shared/lib/core/router/subrouters/import-router.ts
  packages/shared/lib/tests/network.test.ts
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/advanced/NetworkConfiguration.svelte
  packages/shared/routes/login/views/SelectProfileView.svelte
  packages/shared/routes/onboarding/CongratulationsView.svelte
  packages/shared/routes/onboarding/CreateView.svelte
  packages/shared/routes/onboarding/OnboardingCustomNetworkView.svelte
  packages/shared/routes/onboarding/OnboardingNetworkView.svelte
  packages/shared/routes/onboarding/OnboardingProtocolView.svelte
  packages/shared/routes/onboarding/PasswordView.svelte
  packages/shared/routes/onboarding/ProfileView.svelte
  packages/shared/routes/onboarding/SetupView.svelte
  packages/shared/routes/onboarding/import/views/ImportView.svelte
  packages/shared/routes/onboarding/import/views/LedgerView.svelte
  packages/shared/routes/onboarding/migrate/views/MigrateView.svelte
  packages/shared/routes/onboarding/migrate/views/TransferFragmentedFundsView.svelte
Labels: type:enhancement, context:wallet, stardust

#3719 chore: bump mobile alpha version
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/App/App.xcodeproj/project.pbxproj
  packages/mobile/ios/App/App/Info.plist
Labels: type:chore, platform:mobile

#3729 feat: re-enable last logged profile for mobile
  packages/shared/routes/login/Login.svelte
Labels: platform:mobile

#3728 fix: route components mounted before locale loaded (mobile)
  packages/mobile/App.svelte
Labels: type:fix, platform:mobile

#3726 update: adapt ui for confirmation popup
  packages/shared/components/TextHint.svelte
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/popups/ActivityDetailsPopup.svelte
  packages/shared/components/popups/ConfirmationPopup.svelte
  packages/shared/components/popups/NewStakingPeriodNotification.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/components/popups/WalletFinderPopup.svelte
  packages/shared/locales/en.json
  packages/shared/routes/dashboard/Dashboard.svelte
  packages/shared/routes/dashboard/settings/views/advanced/CrashReporting.svelte
  packages/shared/routes/dashboard/settings/views/general/Theme.svelte
Labels: context:wallet, type:ui, stardust

#3739 fix: settings bottom safe area
  packages/shared/routes/dashboard/settings/Settings.svelte
Labels: type:fix, platform:mobile, type:ui

#3740 fix: crash idle logout & mobile initialization
  packages/shared/components/Idle.svelte
  packages/shared/routes/dashboard/wallet/Wallet.svelte
Labels: type:fix, platform:mobile

#3684 feat: validate amount storage deposit before send
  packages/shared/components/popups/SendConfirmationPopup.svelte
  packages/shared/lib/core/error/classes/index.ts
  packages/shared/lib/core/error/classes/send/index.ts
  packages/shared/lib/core/error/classes/send/insufficient-funds-for-storage-deposit-error.class.ts
  packages/shared/lib/core/error/classes/send/invalid-expiration-date-time-error.class.ts
  packages/shared/lib/core/wallet/actions/index.ts
  packages/shared/lib/core/wallet/actions/sendOutput.ts
  packages/shared/lib/core/wallet/actions/trySendOutput.ts
  packages/shared/lib/core/wallet/utils/index.ts
  packages/shared/lib/core/wallet/utils/send/index.ts
  packages/shared/lib/core/wallet/utils/send/validateSendConfirmation.ts
  packages/shared/lib/stronghold.ts
  packages/shared/locales/en.json
Labels: type:feature, stardust

#3745 chore: use if wallet package
  packages/shared/lib/core/account/api/claimOutputs.ts
  packages/shared/lib/core/account/api/collectOutputs.ts
  packages/shared/lib/core/account/api/getOutputsWithAdditionalUnlockConditions.ts
  packages/shared/lib/core/account/api/index.ts
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/core/profile-manager/api/setClientOptions.ts
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/enums/inclusion-state.enum.ts
  packages/shared/lib/core/wallet/utils/send/validateSendConfirmation.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: package:wallet.rs, stardust
