Repository iotaledger/firefly, pull requests merged in 2023-08, with the labels that each got.

#7261 refactor: cleanup component `Spinner`
  packages/desktop/components/popups/NodeInfoPopup.svelte
  packages/desktop/views/dashboard/settings/views/security/ChangePassword.svelte
  packages/desktop/views/dashboard/settings/views/security/ExportStronghold.svelte
  packages/shared/components/Button.svelte
  packages/shared/components/MenuItem.svelte
  packages/shared/components/Spinner.svelte
  packages/shared/components/buttons/OnboardingButton.svelte
Labels: type:refactor

#7303 fix: macos build
  .github/workflows/build-desktop.yml
  patches/dmg-builder+22.9.1.patch
Labels: scope:ci

#7136 refactor: cleanup component `ProfilePicture`
  packages/desktop/views/dashboard/Sidebar.svelte
  packages/shared/components/Profile.svelte
  packages/shared/components/ProfilePicture.svelte
  packages/shared/components/enums/index.ts
  packages/shared/components/enums/size.enum.ts
  packages/shared/components/index.js
  packages/shared/components/modals/ProfileActions.svelte
Labels: type:refactor

#7186 refactor: cleanup `AccountInput` and remove `RecipientAccountSelector`
  packages/desktop/components/popups/AccountSwitcherPopup.svelte
  packages/shared/components/inputs/AccountInput.svelte
  packages/shared/components/inputs/AccountSelector.svelte
  packages/shared/components/inputs/index.js
  packages/shared/components/modals/RecipientAccountSelector.svelte
  packages/shared/components/modals/index.js
Labels: type:refactor

#7267 refactor: cleanup `ProposalsDetailsMenu`
  packages/desktop/components/ProposalsDetails.svelte
  packages/shared/components/modals/ProposalsDetailsMenu.svelte
  packages/shared/components/modals/index.js
Labels: type:refactor

#7263 refactor: cleanup `NodeActionsMenu`
  packages/shared/components/NodeListRow.svelte
  packages/shared/components/NodeListTable.svelte
  packages/shared/components/index.js
  packages/shared/components/modals/NodeActionsMenu.svelte
  packages/shared/components/modals/index.js
Labels: type:refactor

#7265 refactor: cleanup `ProfileActions`
  packages/shared/components/modals/ProfileActionsModal.svelte
  packages/shared/components/modals/index.js
Labels: type:refactor

#7308 fix: avoid error when trying to burn a token with one decimal
  packages/shared/lib/core/i18n/utils/formatNumber.ts
Labels: type:fix
