Repository iotaledger/firefly, pull requests merged in 2023-04, with the labels that each got.

#6330 chore: update dependencies
  packages/desktop/components/filter/FilterItem.svelte
  packages/desktop/components/popups/EnableLedgerBlindSigningPopup.svelte
  packages/desktop/components/popups/RemoveNode.svelte
  packages/desktop/package.json
  packages/desktop/views/dashboard/Sidebar.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/mobile/package.json
  packages/shared/components/atoms/boxes/KeyValueBox.svelte
  packages/shared/components/inputs/PasswordInput.svelte
  packages/shared/components/inputs/Toggle.svelte
  packages/shared/components/molecules/NftImageOrIconBox.svelte
  yarn.lock
Labels: scope:security

#6316 enhancement: remove old log files
  packages/desktop/electron/preload.js
Labels: type:enhancement, v2

#6362 chore: add conditionNames
  packages/desktop/webpack.config.js
Labels: type:enhancement, context:developer

#6255 enhancement: fiat balance on switcher
  packages/desktop/components/modals/AccountSwitcherModal.svelte
  packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
Labels: type:enhancement, platform:desktop, v2

#6339 feat: adjust update stronghold flow for onboarding
  packages/shared/lib/core/router/enums/routes.ts
  packages/shared/lib/core/router/subrouters/import-router.ts
  packages/shared/lib/core/router/subrouters/login-router.ts
  packages/shared/lib/core/router/subrouters/update-stronghold-router.ts
  packages/shared/locales/en.json
  packages/shared/routes/login/Login.svelte
  packages/shared/routes/login/views/index.js
  packages/shared/routes/setup/import/Import.svelte
  packages/shared/routes/setup/import/views/BackupPassword.svelte
  packages/shared/routes/update-stronghold/UpdateStrongholdRouter.svelte
  packages/shared/routes/update-stronghold/views/ChangePasswordView.svelte
  packages/shared/routes/update-stronghold/views/SaveBackupView.svelte
  packages/shared/routes/update-stronghold/views/UpdateStrongholdView.svelte
  packages/shared/routes/update-stronghold/views/index.js
Labels: type:feature

#6353 enhancement: tests speed
  packages/shared/jest.config.js
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/core/utils/tests/crypto.test.ts
  packages/shared/lib/core/wallet/tests/getOutputOptions.test.ts
  packages/shared/package.json
  packages/shared/tsconfig.test.json
  yarn.lock
Labels: type:enhancement, scope:dependencies, type:tests, v2

#6354 feat: add nft activity
  packages/shared/components/atoms/tiles/tileContents/NftActivityTileContent.svelte
  packages/shared/components/molecules/ActivityInformation.svelte
  packages/shared/components/molecules/BasicActivityDetails.svelte
  packages/shared/components/molecules/FoundryActivityDetails.svelte
  packages/shared/components/molecules/NftActivityDetails.svelte
  packages/shared/lib/core/wallet/types/index.ts
  packages/shared/lib/core/wallet/types/sender-info.type.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateSingleBasicActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateSingleNftActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/getLayer2ActivityInformation.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/getSendingInformation.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/getSubjectFromActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/index.ts
  packages/shared/lib/core/wallet/utils/generateActivity/index.ts
Labels: type:enhancement, v2, context:collectibles

#6317 fix: disable vote button after voting
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  yarn.lock
Labels: type:fix, context:governance, platform:desktop, v2

#6350 enhancement: remove or download NFT media if MaxMediaSize setting is changed
  packages/desktop/electron/electronApi.js
  packages/desktop/electron/main.js
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/desktop/views/dashboard/settings/views/collectibles/MaxMediaSize.svelte
  packages/shared/lib/core/app/interfaces/platform.interface.ts
  packages/shared/lib/core/nfts/actions/addNftsToDownloadQueue.ts
  packages/shared/lib/core/nfts/actions/index.ts
  packages/shared/lib/tests/__mocks__/platform.mock.ts
Labels: type:enhancement, platform:desktop, v2, context:collectibles

#6395 fix: add missing `on:keydown` event on textarea
  packages/shared/components/inputs/ImportTextfield.svelte
Labels: type:fix, v2

#6423 chore: update `yarn.lock` file
  yarn.lock
Labels: type:chore

#6415 fix: add patch for debug mode to enable devtools in iOS 16
  packages/mobile/ios/App/App/AppDelegate.swift
Labels: os:ios, platform:mobile, v2

#6396 Fix: l2 to l1 activities
  packages/shared/components/atoms/boxes/AddressBox.svelte
  packages/shared/components/atoms/tiles/tileContents/NftActivityTileContent.svelte
  packages/shared/components/atoms/tiles/tileContents/TransactionActivityTileContent.svelte
  packages/shared/lib/core/layer-2/utils/getLayer2NetworkFromAddress.ts
  packages/shared/lib/core/layer-2/utils/index.ts
  packages/shared/lib/core/ledger/helpers/deconstructLedgerVerificationProps.ts
  packages/shared/lib/core/wallet/utils/generateActivity/helper/getSubjectFromActivity.ts
  packages/shared/lib/core/wallet/utils/getSubjectFromAddress.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderAddressFromInputs.ts
Labels: type:fix, context:layer-2

#6435 chore: remove `rust` linting job
  .github/workflows/ci.lint.yml
Labels: type:chore

#6398 refactor: replace network-configuration with network-information
  packages/mobile/components/NodeListTable.svelte
  packages/mobile/components/drawers/profile/ProfileDrawer.svelte
  packages/mobile/components/drawers/profile/views/settings/views/index.js
  packages/mobile/components/drawers/profile/views/settings/views/networkConfiguration/NetworkConfigurationRouter.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkConfiguration/index.js
  packages/mobile/components/drawers/profile/views/settings/views/networkConfiguration/views/index.js
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/NetworkInformationRouter.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/index.js
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationAddUpdateNodeView.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationInitView.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationNodeConfirmationView.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationNodeInfoView.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/index.js
  packages/mobile/features/features.ts
  packages/mobile/lib/auxiliary/drawer/utils/get-drawer-router.util.ts
  packages/mobile/lib/contexts/settings/constants/settings-route-meta.constant.ts
  packages/mobile/lib/contexts/settings/enums/index.ts
  packages/mobile/lib/contexts/settings/enums/network-information-settings-action.enum.ts
  packages/mobile/lib/routers/actions/initialiseRouters.ts
  packages/mobile/lib/routers/actions/resetRouters.ts
  packages/mobile/lib/routers/enums/settings-route.enum.ts
  packages/mobile/lib/routers/enums/settings/index.ts
  packages/mobile/lib/routers/enums/settings/network-information-settings-route.enum.ts
  packages/mobile/lib/routers/interfaces/index.ts
  packages/mobile/lib/routers/interfaces/network-configuration-settings-router-event.interface.ts
  packages/mobile/lib/routers/interfaces/network-information-settings-router-event.interface.ts
  packages/mobile/lib/routers/routers/dashboard/profile-router.ts
  packages/mobile/lib/routers/routers/settings/index.ts
  packages/mobile/lib/routers/routers/settings/network-configuration-settings-router.ts
  packages/mobile/lib/routers/routers/settings/network-information-settings-router.ts
  packages/mobile/lib/routers/utils/getSubroutersForAppContext.ts
Labels: type:refactor, platform:mobile, v2

#6397 fix: activity tile footer fast claim & reject actions
  packages/mobile/components/ActivityTile.svelte
Labels: type:fix, platform:mobile, v2

#6401 feat: polish mobile onboarding heights
  packages/mobile/components/OnboardingLayout.svelte
  packages/mobile/views/onboarding/views/profile-recovery/views/ImportMnemonicPhraseView.svelte
  packages/mobile/views/onboarding/views/stronghold-setup/views/SetupStrongholdPasswordView.svelte
  packages/shared/components/inputs/ImportTextfield.svelte
Labels: type:enhancement, platform:mobile, type:ui, v2

#6391 fix: add missing approved legal versions during onboarding
  packages/mobile/views/onboarding/views/app-setup/views/WelcomeView.svelte
Labels: type:fix, platform:mobile, v2

#6443 feat: add mobile version details
  packages/mobile/App.svelte
  packages/mobile/capacitor/capacitorApi.ts
Labels: type:feature, os:android, os:ios, platform:mobile, v2

#6458 fix: not visible enter password input in import from stronghold flow
  packages/mobile/views/onboarding/views/profile-recovery/views/BackupPasswordView.svelte
Labels: type:fix, platform:mobile, v2

#6441 feat: set language based on device on first startup
  packages/mobile/App.svelte
  packages/mobile/capacitor/capacitorApi.ts
  packages/shared/lib/core/app/interfaces/platform.interface.ts
  packages/shared/lib/tests/__mocks__/platform.mock.ts
Labels: type:enhancement, os:android, os:ios, platform:mobile, v2

#6462 refactor: create getCoinType for active profile
  packages/shared/components/molecules/GovernanceActivityDetails.svelte
  packages/shared/lib/core/profile/actions/active-profile/getCoinType.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/wallet/actions/getAccountAssetsForSelectedAccount.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateSingleBasicActivity.ts
  packages/shared/lib/core/wallet/utils/generateActivity/generateSingleFoundryActivity.ts
Labels: type:refactor, v2

#6461 refactor: create getBaseToken for active profile
  packages/desktop/components/modals/AccountSwitcherModal.svelte
  packages/desktop/components/popups/AliasConfirmationPopup.svelte
  packages/desktop/components/popups/MintNativeTokenConfirmationPopup.svelte
  packages/desktop/components/popups/MintNftConfirmationPopup.svelte
  packages/desktop/components/popups/VoteForProposalPopup.svelte
  packages/desktop/components/popups/WalletFinderPopup.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/mobile/components/drawers/AccountSwitcherDrawer.svelte
  packages/mobile/components/drawers/profile/views/settings/views/WalletFinderView.svelte
  packages/mobile/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
  packages/mobile/views/dashboard/DashboardView.svelte
  packages/shared/components/modals/RecipientAccountSelector.svelte
  packages/shared/components/molecules/GovernanceActivityDetails.svelte
  packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte
  packages/shared/components/molecules/activity-info/GovernanceActivityInformation.svelte
  packages/shared/components/molecules/menu-items/AccountSwitcherMenuItem.svelte
  packages/shared/lib/core/profile/actions/active-profile/getBaseToken.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/utils/outputs/getFormattedVotingPowerFromGovernanceActivity.ts
Labels: type:refactor, v2

#6464 refactor: remove unused functions
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/core/network/utils/getNetwork.ts
  packages/shared/lib/core/network/utils/getOfficialNetwork.ts
  packages/shared/lib/core/network/utils/index.ts
Labels: type:refactor, v2

#6465 refactor: remove protocol selection view/routes
  packages/desktop/views/onboarding/views/network-setup/NetworkSetupRouter.svelte
  packages/desktop/views/onboarding/views/network-setup/views/ChooseProtocolView.svelte
  packages/desktop/views/onboarding/views/network-setup/views/index.js
  packages/mobile/lib/routers/enums/onboarding/network-setup-route.enum.ts
  packages/mobile/lib/routers/routers/onboarding/network-setup-router.ts
  packages/mobile/views/onboarding/views/network-setup/NetworkSetupRouter.svelte
  packages/mobile/views/onboarding/views/network-setup/views/ChooseProtocolView.svelte
  packages/mobile/views/onboarding/views/network-setup/views/index.js
  packages/shared/lib/core/router/enums/onboarding/network-setup-route.enum.ts
  packages/shared/lib/core/router/subrouters/onboarding/network-setup-router.ts
Labels: type:refactor, platform:mobile, platform:desktop, v2

#6411 chore: update wallet rs
  packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte
  packages/shared/lib/core/account/actions/buildAccountState.ts
  packages/shared/lib/core/account/api/getVotingPower.ts
  packages/shared/lib/core/account/interfaces/account.interface.ts
  packages/shared/lib/core/profile-manager/actions/subscribeToWalletApiEvents.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/wallet/actions/mintNativeToken.ts
  packages/shared/lib/core/wallet/constants/default-transaction-options.constant.ts
  packages/shared/lib/tests/__mocks__/account.mock.ts
  packages/shared/lib/tests/__mocks__/profile-manager.mock.ts
  packages/shared/package.json
  yarn.lock
Labels: scope:dependencies, platform:desktop

#6473 fix: fix GitHub actions
  .github/workflows/build-and-release-desktop.yml
  .github/workflows/build-desktop.yml
Labels: type:chore, scope:ci, type:fix

#6471 fix: `error accessing storage: IO error` in mobile during onboarding
  packages/mobile/views/onboarding/views/profile-setup/views/SetupView.svelte
Labels: type:fix, platform:mobile, v2

#6449 enhancement: improve dropdown component quality
  packages/desktop/views/dashboard/settings/views/collectibles/MaxMediaSize.svelte
  packages/desktop/views/dashboard/settings/views/general/Language.svelte
  packages/desktop/views/dashboard/settings/views/profile/Currency.svelte
  packages/desktop/views/dashboard/settings/views/security/AppLock.svelte
  packages/desktop/views/dashboard/settings/views/security/StrongholdPasswordTimeout.svelte
  packages/desktop/views/onboarding/views/app-setup/views/LanguageAndAppearanceView.svelte
  packages/mobile/components/drawers/profile/views/settings/views/AppLockView.svelte
  packages/mobile/components/drawers/profile/views/settings/views/CurrencyView.svelte
  packages/mobile/components/molecules/filter-items/AssetFilterItem.svelte
  packages/mobile/components/molecules/filter-items/DateFilterItem.svelte
  packages/mobile/components/molecules/filter-items/NumberFilterItem.svelte
  packages/mobile/components/molecules/filter-items/OrderFilterItem.svelte
  packages/mobile/components/molecules/filter-items/SelectionFilterItem.svelte
  packages/shared/components/inputs/Dropdown.svelte
  packages/shared/components/inputs/Dropdown2.svelte
  packages/shared/components/inputs/UnitInput.svelte
  packages/shared/components/molecules/filter-items/AssetFilterItem.svelte
  packages/shared/components/molecules/filter-items/DateFilterItem.svelte
  packages/shared/components/molecules/filter-items/NumberFilterItem.svelte
  packages/shared/components/molecules/filter-items/OrderFilterItem.svelte
  packages/shared/components/molecules/filter-items/SelectionFilterItem.svelte
  packages/shared/components/types/dropdown-item.type.ts
  packages/shared/components/types/index.ts
  packages/shared/lib/core/utils/interfaces/dropdown-item.interface.ts
  packages/shared/lib/core/utils/interfaces/dropdown.interface.ts
  packages/shared/lib/core/utils/interfaces/filter/filter-unit.interface.ts
  packages/shared/lib/core/utils/interfaces/index.ts
Labels: type:enhancement, type:refactor, v2

#6460 refactor: move networkHrp store to profile package
  packages/desktop/components/popups/MintNftFormPopup.svelte
  packages/mobile/components/inputs/RecipientInput.svelte
  packages/shared/components/inputs/AliasInput.svelte
  packages/shared/components/inputs/NetworkInput.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
  packages/shared/lib/core/network/stores/index.ts
  packages/shared/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/lib/core/profile/stores/index.ts
  packages/shared/lib/core/profile/stores/network-hrp.store.ts
  packages/shared/lib/core/utils/crypto/utils/validateEthereumAddress.ts
  packages/shared/lib/core/wallet/utils/convertBech32ToHexAddress.ts
  packages/shared/lib/core/wallet/utils/convertHexAddressToBech32.ts
Labels: type:refactor, v2

#6442 feat: set theme based on device on first startup
  packages/shared/lib/core/app/constants/default-app-settings.constant.ts
Labels: type:enhancement, v2

#6426 feature: max download time setting
  packages/desktop/features/settings.features.ts
  packages/desktop/views/dashboard/settings/views/collectibles/MaxMediaDownloadTime.svelte
  packages/desktop/views/dashboard/settings/views/collectibles/collectibles-settings.constant.js
  packages/desktop/views/dashboard/settings/views/collectibles/index.js
  packages/shared/lib/auxiliary/icon/constants/settings-icon-svg.ts
  packages/shared/lib/core/nfts/actions/interruptNftDownloadAfterTimeout.ts
  packages/shared/lib/core/nfts/constants/default-max-nft-downloading-time-in-seconds.constant.ts
  packages/shared/lib/core/nfts/constants/default-max-nft-size-in-megabytes.constant.ts
  packages/shared/lib/core/nfts/constants/index.ts
  packages/shared/lib/core/nfts/constants/max-nft-downloading-time.constant.ts
  packages/shared/lib/core/nfts/stores/persisted-nft-data.store.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/lib/core/profile/interfaces/profile-settings.interface.ts
  packages/shared/lib/core/router/enums/settings/collectibles-settings-route.enum.ts
  packages/shared/lib/features/interfaces/settings-features.interface.ts
  packages/shared/locales/en.json
Labels: type:feature, v2, context:collectibles

#6431 fix: snyk
  .eslintrc.js
  .github/workflows/build-desktop.yml
  .github/workflows/ci.lint.yml
  .github/workflows/ci.test.yml
  .github/workflows/ci.ts.yml
  package.json
  packages/desktop/components/ProposalQuestion.svelte
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/mobile/components/AssetList.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/lib/contexts/onboarding/actions/syncShimmerClaimingAccount.ts
  packages/shared/lib/contexts/onboarding/helpers/getSortedRenamedBoundAccounts.ts
  packages/shared/lib/contexts/onboarding/helpers/prepareShimmerClaimingAccount.ts
  packages/shared/lib/contexts/onboarding/stores/onboarding-profile.store.ts
  packages/shared/lib/contexts/onboarding/utils/getWordChoices.ts
  packages/shared/lib/contexts/onboarding/utils/sumTotalUnclaimedRewards.ts
  packages/shared/lib/core/network/actions/addNodeToClientOptions.ts
  packages/shared/lib/core/profile/stores/active-profile.store.ts
  packages/shared/lib/core/utils/convert.ts
  packages/shared/lib/core/wallet/utils/getMetadataFromFoundryOutput.ts
  packages/shared/package.json
  yarn.lock
Labels: type:chore

#6463 refactor: add network to persisted profile
  packages/shared/lib/core/network/actions/getAndUpdateNodeInfo.ts
  packages/shared/lib/core/network/constants/network.constant.ts
  packages/shared/lib/core/network/enums/index.ts
  packages/shared/lib/core/network/enums/network-id.enum.ts
  packages/shared/lib/core/network/enums/token-supply.enum.ts
  packages/shared/lib/core/network/interfaces/index.ts
  packages/shared/lib/core/network/interfaces/network.interface.ts
  packages/shared/lib/core/network/interfaces/protocol.interface.ts
  packages/shared/lib/core/network/interfaces/rent-structure.interface.ts
  packages/shared/lib/core/network/utils/buildNetworkFromNodeInfoResponse.ts
  packages/shared/lib/core/network/utils/getNetworkIdFromNetworkName.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/lib/core/profile/actions/active-profile/checkAndUpdateActiveProfileNetwork.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/lib/core/profile/constants/profile-version.constant.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
Labels: type:refactor, v2

#6452 chore: implement mobile export logic (iOS)
  packages/shared/lib/contexts/settings/actions/exportStronghold.ts
Labels: type:feature, os:ios, platform:mobile, v2

#6523 fix: fix unknown activity
  packages/shared/lib/core/wallet/utils/generateActivity/helper/getSubjectFromActivity.ts
Labels: type:fix, context:wallet, v2

#6529 fix: update node
  .github/workflows/build-and-release-desktop.yml
Labels: scope:dependencies, scope:ci

#6530 chore: make shimmer icon non clickable
  packages/desktop/views/dashboard/Sidebar.svelte
  packages/shared/components/NetworkIndicator.svelte
  packages/shared/components/index.js
  packages/shared/components/modals/NetworkSummaryModal.svelte
  packages/shared/components/modals/index.js
Labels: type:chore, v2, context:layer-2

#6514 chore: prepare feature flags
  packages/mobile/capacitor.config.ts
  packages/mobile/features/capacitor.features.ts
  packages/mobile/features/features.ts
  packages/mobile/features/onboarding.features.ts
Labels: type:feature, type:chore, platform:mobile, v2

#6532 chore: bump version
  packages/mobile/android/app/build.gradle
  packages/mobile/ios/App/App.xcodeproj/project.pbxproj
  packages/mobile/package.json
Labels: type:chore, platform:mobile, v2

#6535 feat: add network config drawer router
  packages/desktop/App.svelte
  packages/desktop/components/SidebarTab.svelte
  packages/desktop/components/drawers/Drawer.svelte
  packages/desktop/components/drawers/DrawerHeader.svelte
  packages/desktop/components/drawers/index.ts
  packages/desktop/components/drawers/network-config/NetworkConfigDrawerRouter.svelte
  packages/desktop/components/drawers/network-config/drawers/AddChainDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/ChainDepositAddressDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/ChainInformationDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/ConnectedChainsDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/EditChainDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/RemoveChainDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/index.ts
  packages/desktop/components/index.js
  packages/desktop/lib/routers/enums/index.ts
  packages/desktop/lib/routers/enums/network-config-route.enum.ts
  packages/desktop/lib/routers/index.ts
  packages/desktop/lib/routers/routers/index.ts
  packages/desktop/lib/routers/routers/network-config.router.ts
  packages/desktop/lib/routers/types/drawer-route.type.ts
  packages/desktop/lib/routers/types/index.ts
  packages/desktop/views/dashboard/Sidebar.svelte
  packages/shared/lib/core/router/classes/router.class.ts
  packages/shared/lib/core/router/interfaces/router.interface.ts
  packages/shared/locales/en.json
Labels: type:feature, platform:desktop, context:layer-2

#6507 enhancement: merge welcome and legal
  packages/desktop/components/popups/LegalUpdatePopup.svelte
  packages/desktop/views/onboarding/views/app-setup/AppSetupRouter.svelte
  packages/desktop/views/onboarding/views/app-setup/views/LegalView.svelte
  packages/desktop/views/onboarding/views/app-setup/views/WelcomeView.svelte
  packages/desktop/views/onboarding/views/app-setup/views/index.js
  packages/mobile/components/drawers/LegalUpdateDrawer.svelte
  packages/shared/components/Link.svelte
  packages/shared/components/inputs/Checkbox.svelte
  packages/shared/lib/core/app/constants/index.ts
  packages/shared/lib/core/app/constants/privacy-policy-url.constant.ts
  packages/shared/lib/core/app/constants/terms-of-service-url.constant.ts
  packages/shared/lib/core/router/subrouters/onboarding/app-setup-router.ts
Labels: type:enhancement, context:onboarding, v2

#6565 fix: use correct unit on confirmation
  packages/desktop/components/popups/send/SendConfirmationPopup.svelte
  packages/shared/components/molecules/BasicActivityDetails.svelte
Labels: type:fix, context:wallet, v2

#6474 refactor: use base token from network
  packages/desktop/components/popups/TokenInformationPopup.svelte
  packages/mobile/components/TokenUnitSwapper.svelte
  packages/mobile/components/drawers/SelectedTokenDrawer.svelte
  packages/mobile/components/drawers/send/views/AmountView.svelte
  packages/shared/components/atoms/AmountBox.svelte
  packages/shared/components/inputs/AssetAmountInput.svelte
  packages/shared/components/inputs/UnitInput.svelte
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/components/molecules/BasicActivityDetails.svelte
  packages/shared/components/molecules/FoundryActivityDetails.svelte
  packages/shared/components/molecules/GovernanceActivityDetails.svelte
  packages/shared/components/molecules/activity-info/TokenActivityInformation.svelte
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendFormOperation.ts
  packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts
  packages/shared/lib/contexts/onboarding/actions/syncShimmerClaimingAccount.ts
  packages/shared/lib/core/layer-2/helpers/encodeAssetAllowance.ts
  packages/shared/lib/core/network/constants/base-token.constant.ts
  packages/shared/lib/core/network/interfaces/network.interface.ts
  packages/shared/lib/core/profile/actions/active-profile/getBaseToken.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/token/utils/getMaxDecimalsFromTokenMetadata.ts
  packages/shared/lib/core/token/utils/index.ts
  packages/shared/lib/core/token/utils/isValidIrc30.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/enums/token-standard.enum.ts
  packages/shared/lib/core/wallet/helpers/buildPersistedAssetFromIrc30Metadata.ts
  packages/shared/lib/core/wallet/interfaces/base-token.interface.ts
  packages/shared/lib/core/wallet/interfaces/index.ts
  packages/shared/lib/core/wallet/interfaces/persisted-asset.interface.ts
  packages/shared/lib/core/wallet/interfaces/token-metadata.interface.ts
  packages/shared/lib/core/wallet/tests/getOutputOptions.test.ts
  packages/shared/lib/core/wallet/types/index.ts
  packages/shared/lib/core/wallet/types/token-metadata.type.ts
  packages/shared/lib/core/wallet/utils/convertToRawAmount.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountBestMatch.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountDefault.ts
  packages/shared/lib/core/wallet/utils/formatTokenAmountPrecise.ts
  packages/shared/lib/core/wallet/utils/getAssetInitials.ts
  packages/shared/lib/core/wallet/utils/getUnitFromTokenMetadata.ts
  packages/shared/lib/core/wallet/utils/index.ts
Labels: type:refactor, v2

#6494 refactor: profile icon from persisted profile network
  packages/desktop/views/login/views/EnterPinView.svelte
  packages/desktop/views/login/views/SelectProfileView.svelte
  packages/mobile/components/buttons/ProfileButton.svelte
  packages/mobile/components/drawers/profile/views/ActionsView.svelte
  packages/mobile/views/login/views/EnterPinView.svelte
  packages/mobile/views/login/views/SelectProfileView.svelte
  packages/shared/components/Profile.svelte
  packages/shared/components/atoms/NetworkIcon.svelte
  packages/shared/components/atoms/badges/NetworkIconBadge.svelte
Labels: type:enhancement, type:refactor, v2

#6503 refactor: getNetworkHrp from active profile network
  packages/desktop/components/popups/MintNftFormPopup.svelte
  packages/mobile/components/inputs/RecipientInput.svelte
  packages/shared/components/inputs/AliasInput.svelte
  packages/shared/components/inputs/NetworkInput.svelte
  packages/shared/components/inputs/RecipientInput.svelte
  packages/shared/lib/auxiliary/deep-link/handlers/wallet/operations/handleDeepLinkSendConfirmationOperation.ts
  packages/shared/lib/core/nfts/utils/parseNftMetadata.ts
  packages/shared/lib/core/profile/actions/active-profile/getNetworkHrp.ts
  packages/shared/lib/core/profile/actions/active-profile/index.ts
  packages/shared/lib/core/profile/stores/index.ts
  packages/shared/lib/core/profile/stores/network-hrp.store.ts
  packages/shared/lib/core/utils/crypto/utils/validateEthereumAddress.ts
  packages/shared/lib/core/wallet/utils/convertBech32ToHexAddress.ts
  packages/shared/lib/core/wallet/utils/convertHexAddressToBech32.ts
Labels: type:refactor, v2

#6557 refactor: remove redundant network health layer
  packages/desktop/views/dashboard/settings/views/network/NetworkInformation.svelte
  packages/mobile/components/buttons/NetworkStatusButton.svelte
  packages/mobile/components/drawers/NetworkStatusDrawer.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationInitView.svelte
  packages/shared/lib/core/network/constants/index.ts
  packages/shared/lib/core/network/constants/network-status-description.constant.ts
  packages/shared/lib/core/network/enums/network-health.enum.ts
  packages/shared/lib/core/network/helpers/getNetworkStatusFromNodeInfo.ts
  packages/shared/lib/core/network/interfaces/network-status.interface.ts
  packages/shared/lib/core/network/stores/network-status.store.ts
  yarn.lock
Labels: type:refactor, v2

#6553 feature: add new chain
  packages/desktop/components/drawers/Drawer.svelte
  packages/desktop/components/drawers/DrawerHeader.svelte
  packages/desktop/components/drawers/network-config/drawers/AddChainDrawer.svelte
  packages/shared/locales/en.json
Labels: type:feature, v2, context:layer-2

#6578 enhancement: add exit button to About Window for windowsOS
  packages/desktop/electron/main.js
Labels: type:enhancement, context:settings

#6524 fix: max amount send flow
  packages/mobile/components/drawers/send/views/AmountView.svelte
Labels: type:fix, platform:mobile, v2

#6502 refactor: network in onboarding flows
  packages/desktop/App.svelte
  packages/desktop/features/onboarding.features.ts
  packages/desktop/views/onboarding/views/app-setup/views/LanguageAndAppearanceView.svelte
  packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/desktop/views/onboarding/views/network-setup/views/SetupPrivateNetworkConnectionView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/EnterNameView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/SetupClaimedView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/SetupNewView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/SetupRecoveredView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/SetupView.svelte
  packages/mobile/features/onboarding.features.ts
  packages/mobile/lib/routers/routers/onboarding/network-setup-router.ts
  packages/mobile/views/login/views/SelectProfileView.svelte
  packages/mobile/views/onboarding/views/app-setup/views/WelcomeView.svelte
  packages/mobile/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/EnterNameView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupClaimedView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupRecoveredView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupView.svelte
  packages/mobile/webpack.config.ts
  packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingFlow.ts
  packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingProfile.ts
  packages/shared/lib/contexts/onboarding/actions/resetOnboardingProfile.ts
  packages/shared/lib/contexts/onboarding/helpers/buildInitialOnboardingProfile.ts
  packages/shared/lib/contexts/onboarding/helpers/convertOnboardingProfileToPersistedProfile.ts
  packages/shared/lib/contexts/onboarding/helpers/index.ts
  packages/shared/lib/contexts/onboarding/interfaces/onboarding-initialisation-options.interface.ts
  packages/shared/lib/core/network/actions/addOfficialNodesToClientOptions.ts
  packages/shared/lib/core/network/constants/official-node-urls.constant.ts
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/core/network/utils/formatProtocolName.ts
  packages/shared/lib/core/network/utils/getDefaultClientOptions.ts
  packages/shared/lib/core/network/utils/getOfficialNodes.ts
  packages/shared/lib/core/profile-manager/utils/buildProfileManagerOptionsFromProfileData.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/router/subrouters/onboarding/network-setup-router.ts
  packages/shared/lib/features/interfaces/index.ts
  packages/shared/lib/features/interfaces/onboarding-features-for-network.interface.ts
  packages/shared/lib/features/types/onboarding-features.type.ts
  packages/shared/locales/en.json
Labels: type:refactor, v2

#6367 feat: add burn native tokens to mobile
  packages/mobile/components/drawers/BurnNativeTokensDrawer.svelte
  packages/mobile/components/drawers/DrawerManager.svelte
  packages/mobile/components/drawers/SelectedTokenDrawer.svelte
  packages/mobile/components/drawers/index.js
  packages/mobile/lib/auxiliary/drawer/enums/drawer-id.enum.ts
Labels: type:feature, platform:mobile, v2

#6591 refactor: faucet to use `NetworkId`
  packages/desktop/components/buttons/popup-buttons/FaucetRequestButton.svelte
  packages/shared/lib/contexts/developer/actions/requestTokensFromFaucet.ts
  packages/shared/lib/core/network/constants/faucet-urls.constant.ts
Labels: type:refactor, v2

#6589 refactor: official nodes and official network to use `NetworkId`
  packages/mobile/components/NodeListTable.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationNodeInfoView.svelte
  packages/shared/components/modals/NodeActionsMenu.svelte
  packages/shared/components/organisms/NodeListTable.svelte
  packages/shared/lib/contexts/governance/utils/createProposalFromEvent.ts
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/core/network/utils/isNetworkOfficial.ts
Labels: type:refactor, v2

#6593 refactor: explorer to use `NetworkId`
  packages/desktop/components/popups/ActivityDetailsPopup.svelte
  packages/desktop/views/dashboard/collectibles/views/CollectiblesDetailsView.svelte
  packages/shared/components/molecules/activity-info/GenericActivityInformation.svelte
  packages/shared/lib/core/network/constants/explorer-urls.constant.ts
  packages/shared/lib/core/network/utils/getOfficialExplorerUrl.ts
Labels: type:refactor, v2

#6603 fix: add missing translation string
  packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts
  packages/shared/lib/contexts/onboarding/actions/syncShimmerClaimingAccount.ts
  packages/shared/locales/en.json
Labels: type:fix

#6615 feat: add network icon map using network id
  packages/desktop/views/dashboard/Sidebar.svelte
  packages/shared/components/atoms/NetworkIcon.svelte
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/lib/auxiliary/icon/constants/index.ts
  packages/shared/lib/auxiliary/icon/constants/network-icon-svg.ts
Labels: type:enhancement, v2

#6617 refactor: `NETWORK_ADDRESS` to use `NetworkId`
  packages/shared/components/inputs/NetworkInput.svelte
  packages/shared/lib/core/layer-2/constants/network-address.constant.ts
  packages/shared/lib/core/layer-2/utils/getDestinationNetworkFromAddress.ts
  packages/shared/lib/core/layer-2/utils/getLayer2NetworkFromAddress.ts
  packages/shared/lib/core/layer-2/utils/isLayer1Destination.ts
Labels: type:enhancement, type:refactor, v2

#6612 refactor: format protocol name to use network id
  packages/desktop/components/popups/ConnectLedgerPopup.svelte
  packages/desktop/views/onboarding/views/app-setup/views/WelcomeView.svelte
  packages/desktop/views/onboarding/views/ledger-setup/views/LedgerInstallationGuideView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/EnterNameView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/SetupRecoveredView.svelte
  packages/desktop/views/onboarding/views/profile-setup/views/SetupView.svelte
  packages/mobile/views/onboarding/views/app-setup/views/WelcomeView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/EnterNameView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupRecoveredView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupView.svelte
  packages/shared/lib/core/network/utils/formatProtocolName.ts
  packages/shared/lib/core/network/utils/getNetworkNameFromNetworkId.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/locales/af.json
  packages/shared/locales/ar.json
  packages/shared/locales/bg.json
  packages/shared/locales/ca.json
  packages/shared/locales/cs.json
  packages/shared/locales/da.json
  packages/shared/locales/de.json
  packages/shared/locales/el.json
  packages/shared/locales/en.json
  packages/shared/locales/eo.json
  packages/shared/locales/es-ES.json
  packages/shared/locales/es-LA.json
  packages/shared/locales/et.json
  packages/shared/locales/fa.json
  packages/shared/locales/fi.json
  packages/shared/locales/fr.json
  packages/shared/locales/he.json
  packages/shared/locales/hi.json
  packages/shared/locales/hr.json
  packages/shared/locales/hu.json
  packages/shared/locales/id.json
  packages/shared/locales/it.json
  packages/shared/locales/ja.json
  packages/shared/locales/ko.json
  packages/shared/locales/ku.json
  packages/shared/locales/lv.json
  packages/shared/locales/mk.json
  packages/shared/locales/nl.json
  packages/shared/locales/no.json
  packages/shared/locales/pl.json
  packages/shared/locales/pt-BR.json
  packages/shared/locales/pt-PT.json
  packages/shared/locales/ro.json
  packages/shared/locales/ru.json
  packages/shared/locales/si.json
  packages/shared/locales/sk.json
  packages/shared/locales/sl.json
  packages/shared/locales/sq.json
  packages/shared/locales/sr.json
  packages/shared/locales/sv.json
  packages/shared/locales/tr.json
  packages/shared/locales/uk.json
  packages/shared/locales/ur.json
  packages/shared/locales/vi.json
  packages/shared/locales/zh-CN.json
  packages/shared/locales/zh-TW.json
Labels: type:refactor, v2

#6526 enhancement: disable onboarding buttons while async loading
  packages/mobile/views/onboarding/views/profile-recovery/views/ImportMnemonicPhraseView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupClaimedView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupRecoveredView.svelte
  packages/mobile/views/onboarding/views/profile-setup/views/SetupView.svelte
  packages/shared/components/atoms/buttons/OnboardingButton.svelte
Labels: type:enhancement, platform:mobile, v2

#6444 fix: `TypeError: cannot read property 'usd' of null`
  .github/workflows/ci.lint.yml
  .github/workflows/ci.snyk.yml
  .github/workflows/ci.test.yml
  packages/shared/components/inputs/Amount.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/assets.ts
  packages/shared/lib/chart.ts
  packages/shared/lib/core/router/subrouters/login-router.ts
  packages/shared/lib/currency.ts
  packages/shared/lib/market.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/wallet/views/Send.svelte
  packages/shared/routes/setup/Balance.svelte
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/migrate/views/Migrate.svelte
Labels: type:fix, platform:desktop, v1

#6613 enhancement: correct coin type for testnet and custom coin type
  packages/desktop/components/OnboardingLayout.svelte
  packages/desktop/views/onboarding/views/network-setup/views/SetupCustomNetworkConnectionView.svelte
  packages/shared/components/organisms/NodeConfigurationForm.svelte
  packages/shared/lib/contexts/onboarding/actions/claimShimmerRewards.ts
  packages/shared/lib/contexts/onboarding/actions/createShimmerClaimingProfileManager.ts
  packages/shared/lib/core/network/constants/coin-type.constant.ts
  packages/shared/lib/core/network/constants/network.constant.ts
  packages/shared/lib/core/network/interfaces/network.interface.ts
  packages/shared/lib/core/network/utils/buildNetworkFromNodeInfoResponse.ts
  packages/shared/lib/core/profile-manager/utils/buildProfileManagerOptionsFromProfileData.ts
  packages/shared/lib/core/profile/actions/active-profile/getCoinType.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/locales/en.json
Labels: type:enhancement, type:refactor, v2

#6607 refactor: reduce usage of hardcoded `BASE_TOKEN`
  packages/desktop/views/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
  packages/desktop/views/onboarding/views/shimmer-claiming/views/SuccessView.svelte
  packages/mobile/components/molecules/ShimmerClaimingAccountList.svelte
  packages/mobile/views/onboarding/views/shimmer-claiming/views/ClaimRewardsView.svelte
  packages/mobile/views/onboarding/views/shimmer-claiming/views/SuccessView.svelte
  packages/shared/components/atoms/tiles/ShimmerClaimingAccountTile.svelte
  packages/shared/components/molecules/ShimmerClaimingAccountList.svelte
  packages/shared/lib/contexts/onboarding/actions/findShimmerRewards.ts
  packages/shared/lib/contexts/onboarding/actions/syncShimmerClaimingAccount.ts
  packages/shared/lib/contexts/onboarding/stores/onboarding-profile.store.ts
  packages/shared/lib/core/network/constants/base-token.constant.ts
  packages/shared/lib/core/network/constants/default-base-token.constant.ts
  packages/shared/lib/core/network/constants/index.ts
  packages/shared/lib/core/network/constants/network.constant.ts
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/core/network/utils/buildNetworkFromNodeInfoResponse.ts
  packages/shared/lib/core/profile/actions/active-profile/getBaseToken.ts
  packages/shared/lib/core/wallet/actions/refreshAccountAssetsForActiveProfile.ts
  packages/shared/lib/core/wallet/interfaces/base-token.interface.ts
  packages/shared/lib/core/wallet/types/token-metadata.type.ts
Labels: type:refactor, v2

#6587 fix-mobile: currency undefined
  packages/mobile/components/drawers/profile/views/settings/views/DiagnosticsView.svelte
Labels: type:fix, platform:mobile, v2

#6584 fix-mobile: disable confirm when no date selected in DateTimePickerDrawer
  packages/mobile/components/drawers/DateTimePickerDrawer.svelte
Labels: type:fix, platform:mobile, v2

#6618 refactor: cleanup debris of `networkProtocol` and `networkType` except profile & migrations
  packages/desktop/views/dashboard/settings/views/network/ConfigureNodeList.svelte
  packages/desktop/views/onboarding/views/profile-recovery/views/LedgerView.svelte
  packages/mobile/components/drawers/profile/views/settings/views/networkInformation/views/NetworkInformationInitView.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/lib/contexts/onboarding/helpers/convertOnboardingProfileToPersistedProfile.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/lib/core/network/utils/isNetworkOfficial.ts
  packages/shared/lib/core/network/utils/isShimmerNetworkProtocol.ts
  packages/shared/lib/core/profile/actions/active-profile/saveActiveProfile.ts
  packages/shared/lib/core/profile/constants/default-persisted-profile-object.constant.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
  packages/shared/lib/core/wallet/actions/getAccountAssetsForSelectedAccount.ts
Labels: type:enhancement, type:refactor, v2

#6620 feat: add migration to remove networkProtocol and networkType from persisted profiles
  packages/shared/lib/core/network/enums/index.ts
  packages/shared/lib/core/network/enums/network-protocol.enum.ts
  packages/shared/lib/core/network/enums/network-type.enum.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
Labels: type:feature, v2

#6601 fix: firefly freezes on invalid send input
  packages/shared/lib/core/i18n/tests/parseCurrency.test.ts
  packages/shared/lib/core/i18n/utils/parseCurrency.ts
Labels: type:fix, context:wallet

#6626 fix: date presentation styling issue
  packages/shared/components/molecules/DateInputButton.svelte
  packages/shared/components/molecules/filter-items/DateFilterItem.svelte
Labels: type:fix

#6627 tests: convert to raw amount
  packages/shared/lib/core/wallet/tests/convertToRawAmount.test.ts
  packages/shared/lib/core/wallet/utils/convertToRawAmount.ts
Labels: type:tests

#6647 chore: add feature flag for adding a L2 chain
  packages/desktop/components/drawers/network-config/drawers/ConnectedChainsDrawer.svelte
  packages/desktop/features/network.features.ts
  packages/shared/lib/features/interfaces/network-features.interface.ts
Labels: type:chore, platform:desktop, context:layer-2

#6602 refactor: rename `INetwork` interface
  packages/desktop/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/desktop/views/onboarding/views/network-setup/views/SetupCustomNetworkConnectionView.svelte
  packages/mobile/views/onboarding/views/network-setup/views/ChooseNetworkView.svelte
  packages/shared/components/atoms/badges/NetworkIconBadge.svelte
  packages/shared/lib/contexts/onboarding/actions/initialiseOnboardingFlow.ts
  packages/shared/lib/core/network/constants/default-network-metadata.constant.ts
  packages/shared/lib/core/network/constants/index.ts
  packages/shared/lib/core/network/index.ts
  packages/shared/lib/core/network/interfaces/index.ts
  packages/shared/lib/core/network/interfaces/persisted-network.interface.ts
  packages/shared/lib/core/network/interfaces/stardust-network-metadata.interface.ts
  packages/shared/lib/core/network/tests/network.test.ts
  packages/shared/lib/core/network/types/index.ts
  packages/shared/lib/core/network/types/network-metadata.type.ts
  packages/shared/lib/core/network/utils/buildPersistedNetworkFromNodeInfoResponse.ts
  packages/shared/lib/core/network/utils/getDefaultPersistedNetwork.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/lib/core/profile/actions/active-profile/checkAndUpdateActiveProfileNetwork.ts
  packages/shared/lib/core/profile/actions/profiles/checkAndMigrateProfiles.ts
  packages/shared/lib/core/profile/interfaces/persisted-profile.interface.ts
Labels: type:refactor

#6558 feature: connected chains
  packages/desktop/components/NetworkCard.svelte
  packages/desktop/components/drawers/network-config/drawers/ConnectedChainsDrawer.svelte
  packages/desktop/components/index.js
  packages/mobile/components/buttons/ProfileButton.svelte
  packages/mobile/components/drawers/profile/views/ActionsView.svelte
  packages/shared/components/atoms/NetworkIcon.svelte
  packages/shared/components/atoms/badges/NetworkIconBadge.svelte
  packages/shared/components/atoms/pills/NetworkStatusPill.svelte
  packages/shared/components/atoms/pills/index.js
  packages/shared/lib/core/network/interfaces/connected-chain.interface.ts
  packages/shared/lib/core/network/interfaces/index.ts
  packages/shared/lib/core/network/utils/buildChainFromNetwork.ts
  packages/shared/lib/core/network/utils/index.ts
  packages/shared/locales/en.json
Labels: v2, context:layer-2

#6633 fix: hidden token activity filtering
  packages/shared/lib/core/wallet/actions/claimActivity.ts
  packages/shared/lib/core/wallet/stores/hidden-activities.store.ts
Labels: bug report, context:wallet

#6635 fix: wallet deletion
  packages/mobile/components/drawers/DeleteAccountDrawer.svelte
  packages/shared/lib/core/profile-manager/actions/deleteAccount.ts
Labels: type:fix, platform:mobile, context:wallet, v2

#6454 fix: `TypeError: cannot read property 'usd' of null`
  .github/workflows/ci.lint.yml
  .github/workflows/ci.snyk.yml
  packages/shared/components/inputs/Amount.svelte
  packages/shared/components/popups/StakingManager.svelte
  packages/shared/lib/assets.ts
  packages/shared/lib/chart.ts
  packages/shared/lib/currency.ts
  packages/shared/lib/market.ts
  packages/shared/lib/wallet.ts
  packages/shared/routes/dashboard/wallet/views/Send.svelte
  packages/shared/routes/setup/Balance.svelte
  packages/shared/routes/setup/Congratulations.svelte
  packages/shared/routes/setup/migrate/views/Migrate.svelte
Labels: type:fix, platform:mobile, v1

#6656 fix: interrupt participation fetch if logged out
  packages/shared/lib/contexts/governance/actions/initializeRegisteredProposals.ts
Labels: type:fix, v2

#6628 feature: network qr view
  packages/desktop/components/NetworkCard.svelte
  packages/desktop/components/drawers/network-config/drawers/ChainDepositAddressDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/ConnectedChainsDrawer.svelte
  packages/shared/lib/core/network/interfaces/index.ts
  packages/shared/lib/core/network/stores/index.ts
  packages/shared/lib/core/network/stores/selected-connected-chain-index.store.ts
Labels: type:feature, v2

#6639 feat: analytics
  .github/workflows/build-and-release-desktop.yml
  .github/workflows/build-desktop.yml
  packages/desktop/App.svelte
  packages/desktop/electron/electronApi.js
  packages/desktop/electron/lib/analytics.js
  packages/desktop/electron/lib/diagnostics.js
  packages/desktop/electron/lib/machineId.js
  packages/desktop/electron/main.js
  packages/desktop/features/analytics.features.ts
  packages/desktop/features/features.ts
  packages/desktop/features/interfaces/analytics-features.interface.ts
  packages/desktop/features/interfaces/desktop-features.interface.ts
  packages/desktop/package.json
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/desktop/views/login/LoginRouter.svelte
  packages/desktop/views/onboarding/OnboardingRouter.svelte
  packages/desktop/views/onboarding/views/app-setup/AppSetupRouter.svelte
  packages/desktop/views/onboarding/views/ledger-setup/LedgerSetupRouter.svelte
  packages/desktop/views/onboarding/views/network-setup/NetworkSetupRouter.svelte
  packages/desktop/views/onboarding/views/profile-backup/ProfileBackupRouter.svelte
  packages/desktop/views/onboarding/views/profile-recovery/ProfileRecoveryRouter.svelte
  packages/desktop/views/onboarding/views/profile-setup/ProfileSetupRouter.svelte
  packages/desktop/views/onboarding/views/shimmer-claiming/ShimmerClaimingRouter.svelte
  packages/desktop/views/onboarding/views/storage-protection-setup/StorageProtectionSetupRouter.svelte
  packages/desktop/views/onboarding/views/stronghold-setup/StrongholdSetupRouter.svelte
  packages/desktop/webpack.config.ts
  packages/shared/lib/core/app/interfaces/platform.interface.ts
  yarn.lock
Labels: type:feature, v2

#6576 enhancement: add chain validation
  packages/desktop/components/drawers/network-config/drawers/AddChainDrawer.svelte
  packages/desktop/components/drawers/network-config/drawers/components/AddIscpChainForm.svelte
  packages/desktop/components/drawers/network-config/drawers/components/index.ts
  packages/shared/lib/core/network/constants/index.ts
  packages/shared/lib/core/network/constants/max-chain-name-length.constant.ts
  packages/shared/lib/core/utils/crypto/utils/index.ts
  packages/shared/lib/core/utils/crypto/utils/isValidHexAddress.ts
  packages/shared/locales/en.json
Labels: type:enhancement, v2
