Repository iotaledger/firefly, pull requests merged in 2023-06, with the labels that each got.

#6938 fix: erc-20 tokens raw amount support
  packages/shared/lib/core/wallet/utils/convertToRawAmount.ts
Labels: type:fix, context:layer-2

#6939 chore: finalize build test schedule
  .github/workflows/build-test.yml
Labels: type:chore

#6958 chore: change workflow name for v2 build
  .github/workflows/build-desktop-test.yml
  .github/workflows/build-desktop.yml
Labels: type:chore, platform:desktop

#6957 chore: rename v1 build workflow
  .github/workflows/build-desktop.yml
Labels: type:chore, platform:desktop, v1

#6959 chore: automated v1 build test
  .github/workflows/build-desktop-test.v1.yml
  .github/workflows/build-desktop-test.v2.yml
Labels: type:chore, platform:desktop, v1

#6963 chore: update text
  packages/shared/components/popups/AirdropNetworkInfo.svelte
Labels: type:chore, v1

#6885 chore: initial update of tailwind to v3
  packages/desktop/App.svelte
  packages/desktop/components/AccountActivity.svelte
  packages/desktop/components/TitleBar.svelte
  packages/desktop/components/popups/AccountSwitcherPopup.svelte
  packages/desktop/components/popups/ActivityDetailsPopup.svelte
  packages/desktop/components/popups/AliasConfirmationPopup.svelte
  packages/desktop/components/popups/BurnNativeTokensConfirmationPopup.svelte
  packages/desktop/components/popups/BurnNativeTokensPopup.svelte
  packages/desktop/components/popups/ConfirmationPopup.svelte
  packages/desktop/components/popups/ConnectLedgerPopup.svelte
  packages/desktop/components/popups/DeepLinkErrorPopup.svelte
  packages/desktop/components/popups/EnableLedgerBlindSigningPopup.svelte
  packages/desktop/components/popups/FaucetRequestPopup.svelte
  packages/desktop/components/popups/MintNftConfirmationPopup.svelte
  packages/desktop/components/popups/ReceiveAddressPopup.svelte
  packages/desktop/components/popups/TokenInformationPopup.svelte
  packages/desktop/components/popups/VerifyLedgerTransactionPopup.svelte
  packages/desktop/components/popups/VoteForProposalPopup.svelte
  packages/desktop/components/popups/send/SendConfirmationPopup.svelte
  packages/desktop/components/popups/send/SendFormPopup.svelte
  packages/desktop/electron/electronApi.js
  packages/desktop/electron/main.js
  packages/desktop/views/dashboard/governance/views/ProposalDetailsView.svelte
  packages/desktop/views/dashboard/send-flow/views/SendFlowTemplate.svelte
  packages/mobile/capacitor/capacitorApi.ts
  packages/mobile/components/ActivityList.svelte
  packages/mobile/components/AssetList.svelte
  packages/mobile/components/NodeListTable.svelte
  packages/mobile/components/OnboardingLayout.svelte
  packages/mobile/components/drawers/BalanceBreakdownDrawer.svelte
  packages/mobile/components/drawers/ConfirmDrawer.svelte
  packages/mobile/components/drawers/DateTimePickerDrawer.svelte
  packages/mobile/components/drawers/DeleteAccountDrawer.svelte
  packages/mobile/components/drawers/ReferencesDrawer.svelte
  packages/mobile/components/molecules/filter-items/DateFilterItem.svelte
  packages/mobile/views/dashboard/tabs/TabNavigator.svelte
  packages/shared/components/Button.svelte
  packages/shared/components/Toast.svelte
  packages/shared/components/atoms/Icon.svelte
  packages/shared/components/atoms/boxes/KeyValueBox.svelte
  packages/shared/components/atoms/tiles/tileContents/FoundryActivityTileContent.svelte
  packages/shared/components/atoms/tiles/tileContents/GovernanceActivityTileContent.svelte
  packages/shared/components/atoms/tiles/tileContents/TransactionActivityTileContent.svelte
  packages/shared/components/inputs/AssetDropdown.svelte
  packages/shared/components/inputs/DateTimePicker.svelte
  packages/shared/components/inputs/Toggle.svelte
  packages/shared/components/molecules/ActivityInformation.svelte
  packages/shared/components/molecules/AssetList.svelte
  packages/shared/components/molecules/NftActivityDetails.svelte
  packages/shared/components/molecules/NftImageOrIconBox.svelte
  packages/shared/components/organisms/NodeListTable.svelte
  packages/shared/lib/core/app/interfaces/platform.interface.ts
  packages/shared/lib/tests/__mocks__/platform.mock.ts
  packages/shared/package.json
  packages/shared/tailwind.config.js
  yarn.lock
Labels: scope:dependencies, type:chore

#6936 feat: limit destination networks to the compatible ones only
  packages/desktop/views/dashboard/send-flow/views/SelectRecipientView.svelte
  packages/shared/lib/core/wallet/utils/transactions/index.ts
Labels: type:enhancement

#6962 feat: adds shimmer EVM badge in NetworkIcon
  packages/shared/components/atoms/NetworkIcon.svelte
  packages/shared/components/atoms/badges/NetworkIconBadge.svelte
  packages/shared/components/molecules/AssetIcon.svelte
  packages/shared/lib/auxiliary/icon/constants/icon-svg.ts
  packages/shared/lib/auxiliary/icon/constants/network-icon-svg.ts
  packages/shared/lib/auxiliary/icon/enums/icon.enum.ts
  packages/shared/lib/auxiliary/icon/svgs/index.ts
  packages/shared/lib/auxiliary/icon/svgs/shimmer-evm.svg.ts
Labels: type:feature, platform:desktop, context:layer-2

#6980 chore: remove dependabot check for mobile
  .github/dependabot.yml
Labels: type:chore, scope:ci

#6979 fix: use separate coin type for ethereum network
  packages/shared/lib/core/layer-2/utils/signIscpTransferTransactionData.ts
  packages/shared/lib/core/network/constants/coin-type.constant.ts
  packages/shared/lib/core/network/constants/default-chain-configurations.constant.ts
  packages/shared/lib/core/network/enums/network-id.enum.ts
  packages/shared/lib/core/network/tests/network.test.ts
Labels: type:fix

#6943 fix: Ledger device and profile mismatch
  packages/shared/lib/core/ledger/actions/registerLedgerDeviceEventHandlers.ts
  packages/shared/lib/core/ledger/utils/index.ts
  packages/shared/lib/core/ledger/utils/isLedgerAppOpen.ts
  packages/shared/lib/core/ledger/utils/isLedgerDeviceMatchingActiveProfile.ts
  packages/shared/lib/core/profile-manager/interfaces/profile-manager.interface.ts
  packages/shared/lib/core/profile-manager/stores/profile-manager.store.ts
Labels: scope:ledger, type:fix, platform:desktop

#6991 chore: update electron
  packages/desktop/package.json
  packages/shared/package.json
  yarn.lock
Labels: scope:security, type:chore

#6975 feat: adds logoUrl in AssetIcon
  packages/desktop/public/index.html
  packages/shared/components/molecules/AssetIcon.svelte
Labels: type:feature, scope:security, platform:desktop, v2

#6861 chore: increase strict mode coverage
  packages/shared/lib/core/ledger/classes/ledger.class.ts
  packages/shared/lib/core/network/actions/editNodeInClientOptions.ts
  packages/shared/lib/core/profile-manager/api/api.ts
  packages/shared/lib/core/wallet/types/activities/base-activity.type.ts
  packages/shared/lib/core/wallet/types/sender-info.type.ts
  packages/shared/lib/core/wallet/utils/getSenderAddressFromUnlockCondition.ts
  packages/shared/lib/core/wallet/utils/isSubjectInternal.ts
  packages/shared/lib/core/wallet/utils/outputs/getSenderFromOutput.ts
  packages/shared/lib/core/wallet/utils/transactions/getSenderFromTransaction.ts
Labels: type:chore

#6989 enhancement: adds gas estimation for l1 -> l2 transactions
  packages/desktop/components/popups/send/SendConfirmationPopup.svelte
  packages/desktop/views/dashboard/send-flow/views/TransactionSummaryView.svelte
  packages/mobile/components/drawers/send/SendRouter.svelte
  packages/shared/lib/contexts/onboarding/actions/claimShimmerRewards.ts
  packages/shared/lib/core/layer-2/utils/getEstimatedGasForTransferFromTransactionDetails.ts
  packages/shared/lib/core/layer-2/utils/getIscpTransferMethod.ts
  packages/shared/lib/core/layer-2/utils/getLayer2MetadataForTransfer.ts
  packages/shared/lib/core/layer-2/utils/index.ts
  packages/shared/lib/core/layer-2/utils/signIscpTransferTransactionData.ts
  packages/shared/lib/core/wallet/tests/getOutputParameters.test.ts
  packages/shared/lib/core/wallet/utils/getOutputParameters.ts
  packages/shared/lib/core/wallet/utils/send/createTransaction.ts
Labels: type:enhancement, v2

#7051 fix: token popup crash when asset missing balance
  packages/shared/components/atoms/tiles/ActivityTile.svelte
  packages/shared/components/atoms/tiles/AssetTile.svelte
  packages/shared/lib/core/wallet/utils/getTokenFromSelectedAccount.ts
  packages/shared/lib/core/wallet/utils/index.ts
Labels: type:fix
