Repository iotaledger/firefly, pull requests merged in 2023-07, with the labels that each got.

#7081 refactor: remove `AccountAssetsList`
  packages/desktop/views/dashboard/wallet/Wallet.svelte
  packages/shared/components/organisms/AccountAssetsList.svelte
  packages/shared/components/organisms/index.js
Labels: type:refactor

#7092 refactor: cleanup `Toggle` component
  packages/desktop/components/popups/send/SendConfirmationPopup.svelte
  packages/mobile/components/buttons/ProfileLockButton.svelte
  packages/mobile/components/drawers/send/views/ReviewView.svelte
  packages/mobile/components/filters/FilterItem.svelte
  packages/shared/components/inputs/Toggle.svelte
  packages/shared/components/modals/ProfileActions.svelte
Labels: type:refactor

#7059 feat: logout on OS lock (macOS & Windows)
  packages/desktop/electron/main.js
  packages/desktop/views/dashboard/Dashboard.svelte
  packages/shared/lib/core/app/interfaces/platform-event-map.interface.ts
Labels: type:feature, v2

#7272 fix: show missing field coin type when connecting to custom network
  packages/shared/components/NodeConfigurationForm.svelte
  packages/shared/components/inputs/Dropdown.svelte
Labels: type:fix

#7273 fix: dropdown not focusing correctly
  packages/shared/components/filter-items/DateFilterItem.svelte
  packages/shared/components/filter-items/NumberFilterItem.svelte
  packages/shared/components/filter-items/OrderFilterItem.svelte
  packages/shared/components/filter-items/SelectionFilterItem.svelte
  packages/shared/components/inputs/Dropdown.svelte
Labels: scope:ux, type:fix

#7275 fix: avoid error when voting power stays the same
  packages/shared/lib/contexts/governance/actions/setVotingPower.ts
Labels: type:fix
