Repository iotaledger/firefly, pull requests merged in 2023-10, with the labels that each got.

#7613 chore: bump electron to 22.3.27
  packages/desktop/package.json
  yarn.lock
Labels: scope:dependencies

#7381 chore(deps): bump svelty-picker from 3.6.1 to 5.0.0
  packages/shared/components/inputs/DateTimePicker.svelte
  packages/shared/package.json
  yarn.lock
Labels: scope:dependencies

#7623 fix: request unlock during login when it has 0 accounts, so we can create a new account
  packages/shared/lib/core/ledger/actions/checkOrConnectLedger.ts
  packages/shared/lib/core/profile/actions/active-profile/checkActiveProfileAuth.ts
  packages/shared/lib/core/profile/actions/active-profile/login.ts
  packages/shared/lib/core/stronghold/actions/checkOrUnlockStronghold.ts
Labels: type:fix

#7601 feat: Output serialization powered by the SDK
  packages/shared/lib/core/layer-2/utils/index.ts
  packages/shared/lib/core/layer-2/utils/outputHexBytes.ts
  packages/shared/lib/core/profile-manager/interfaces/api.interface.ts
  packages/shared/lib/core/utils/index.ts
  packages/shared/lib/core/utils/serializeOutput.ts
  packages/shared/lib/core/wallet/utils/getOutputParameters.ts
Labels: type:enhancement

#7604 feat: Improved l2 estimated gas
  packages/shared/lib/core/wallet/utils/getOutputParameters.ts
Labels: type:enhancement

#7460 chore: update FAQ link
  packages/shared/lib/contexts/settings/constants/faq-url.constant.ts
Labels: type:fix
